force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_ReInsurance__c/VG_ReInsurance__c.object-meta.xml
<CustomObject>
    <label>Capacity Bordereaux</label>
    <nameField>
        <label>ReInsurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Bordereaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VG_EdisonPS_MTA0_Controller_Test.cls
@IsTest(SeeAllData=False)
public class VG_EdisonPS_MTA0_Controller_Test {
    public static testmethod void method1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ApexPages.currentPage().getParameters().put('PSID', ps.id);
        ApexPages.currentPage().getParameters().put('PId', pol.id);
        VG_EdisonPS_MTA0_Controller emc=new VG_EdisonPS_MTA0_Controller();
        emc.Cancel();
        emc.Next();
        emc.seletedType='--Select--';
        emc.Next();
        emc.psListDup=new List<Policy_Schedule__c>();
        emc.psaListDup=new List<VG_Policy_Schedule_Asset__c>();
        emc.pseListDup=new List<VG_Policy_Schedule_Endorsement__c>();
        emc.rcListDup=new List<Risk_Capture__c>();
        emc.RIListDup=new List<VG_ReInsurance__c>();
        emc.psList=new Map<Id, Policy_Schedule__c>();
        emc.psaList=new List<VG_Policy_Schedule_Asset__c> ();
        emc.pseList =new List<VG_Policy_Schedule_Endorsement__c> ();
        emc.RIList =new List<VG_ReInsurance__c> ();
        emc.rcList =new List<Risk_Capture__c> ();
        emc.oldPSIdDupPSRecMap =new Map<Id, Policy_Schedule__c> ();
        emc.oldPSIdDupPSAMap =new Map<Id, List<VG_Policy_Schedule_Asset__c>> ();
        emc.oldPSIdDupPSEMap=new Map<Id, List<VG_Policy_Schedule_Endorsement__c>> ();
        emc.oldPSIdDupRIMap =new Map<Id, List<VG_ReInsurance__c>> ();
        emc.oldPSIdDupRCMap =new Map<Id, List<Risk_Capture__c>> ();
        emc.PID=null;
        emc.cancel();
    }
}