force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Search Field that Searches the contacts for the given broker.</description>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Broker_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3 AND 4) OR 5</booleanFilter>
        <errorMessage>Please select an approved broker or sub-broker</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sub-Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.VG_TOBA_Uploaded__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Regulatory_Check__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy_Status__c</field>
            <operation>equals</operation>
            <value>NTU/Decline</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Broker)</relationshipLabel>
    <relationshipName>Policies_Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChangeBrokerController.cls
Public Class ChangeBrokerController{
    
    public Policy__c policy{get;set;}
    
    public String PolicyId{get;set;}
    
    public ChangeBrokerController(){
        PolicyId =  apexpages.currentpage().getparameters().get('Id');
        policy = [select id, Name, Broker_Contact__c, Broker_Name__c from Policy__c where Id =: PolicyId limit 1];
        policy.Broker_Name__c = null;
        policy.Broker_Contact__c = null;
    }
    
    public PageReference cancel(){
        return new PageReference('/'+policy.id);
    }
    
    public PageReference save(){
        if(policy.Broker_Contact__c == null){
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please fill Broker Cantact.')); 
            return null;
        }
        try{
        
            update policy;
            return new PageReference('/'+policy.id);
        }Catch(Exception e){
            return null;
        }
    }
    
}