force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Insured)</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>NTU/Decline</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
                <isActive>false</isActive>
                <label>Additional Information Required</label>
            </value>
            <value>
                <fullName>Awaiting Submission</fullName>
                <isActive>false</isActive>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Final Terms Quoted After Negotiations</fullName>
                <isActive>false</isActive>
                <label>Final Terms Quoted After Negotiations</label>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
                <isActive>false</isActive>
                <label>NTU - Capacity</label>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
                <isActive>false</isActive>
                <label>NTU - Other</label>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
                <isActive>false</isActive>
                <label>NTU - Price</label>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
                <isActive>false</isActive>
                <label>NTU - Service</label>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
                <isActive>false</isActive>
                <label>NTU - Terms</label>
            </value>
            <value>
                <fullName>Referral Approval</fullName>
                <isActive>false</isActive>
                <label>Referral Approval</label>
            </value>
            <value>
                <fullName>Submission Received</fullName>
                <isActive>false</isActive>
                <label>Submission Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Expiry_Date__c</fullName>
    <label>Risk Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Inception_Date__c</fullName>
    <label>Risk Inception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Capacity_Paper__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Paper__c</fullName>
    <label>Section No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PI Liberty 100%</fullName>
            </value>
            <value>
                <fullName>PI Liberty Co</fullName>
            </value>
            <value>
                <fullName>PI Liberty Lloyds</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual VFP</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - D&amp;O/Crime</fullName>
            </value>
            <value>
                <fullName>Hazardous</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Haulage</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Non Conventional</fullName>
            </value>
            <value>
                <fullName>Bridge Default</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI Open Market (2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI CE (2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI CE (2019)</fullName>
            </value>
            <value>
                <fullName>Written in 2020</fullName>
            </value>
            <value>
                <fullName>PT into 2020</fullName>
            </value>
            <value>
                <fullName>2018 Liberty Company Stamp - 2018 year</fullName>
            </value>
            <value>
                <fullName>2019 - 2019 YOA - 10 MUSD - 60% Liberty, 10% Swiss, 30% Everest</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - 10 MUSD - 60% Liberty, 10% Swiss, 30% Everest</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - after Partner PT</fullName>
            </value>
            <value>
                <fullName>2020 - 4 MUSD (Liberty 3 + Swiss 1)</fullName>
            </value>
            <value>
                <fullName>2020 - 5.5 MUSD (Liberty 3+Swiss 1, Fidelis 0+Partner 1.5)</fullName>
            </value>
            <value>
                <fullName>Special - Inmarsat PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Measat PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Ovzon PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Resurs PT Stamp</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - 10 MUSD - 90% Liberty, 10% Swiss</fullName>
            </value>
            <value>
                <fullName>2020 - 13.5 MUSD (3+1, 1.5, 2.5+2.5+0.5+2.5)</fullName>
            </value>
            <value>
                <fullName>2020 - Liberty and Lineslip (Argentina)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/VG_ReInsurance__c.object-meta.xml
<CustomObject>
    <label>Capacity Bordereaux</label>
    <nameField>
        <label>ReInsurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Bordereaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_UMR__c.field-meta.xml
<CustomField>
    <fullName>VG_UMR__c</fullName>
    <label>Unique Market Reference</label>
    <referenceTo>VG_UMR__c</referenceTo>
    <relationshipLabel>Capacity Bordereaux</relationshipLabel>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Capacity)</relationshipLabel>
    <relationshipName>UMR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Capacity_Paper__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Paper__c</fullName>
    <label>Section No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PI Liberty 100%</fullName>
            </value>
            <value>
                <fullName>PI Liberty Co</fullName>
            </value>
            <value>
                <fullName>PI Liberty Lloyds</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual VFP</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - D&amp;O/Crime</fullName>
            </value>
            <value>
                <fullName>Warranty &amp; Indemnity</fullName>
            </value>
            <value>
                <fullName>CE - VSR</fullName>
            </value>
            <value>
                <fullName>CE - VSR Amwin</fullName>
            </value>
            <value>
                <fullName>Greenlight Re</fullName>
            </value>
            <value>
                <fullName>Fidelis</fullName>
            </value>
            <value>
                <fullName>AGCS</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (FY 2019)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (FY 2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (Section A - 2020)</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Amwin</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (Section A - 2019)</fullName>
            </value>
            <value>
                <fullName>Hazardous</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Haulage</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Non Conventional</fullName>
            </value>
            <value>
                <fullName>Liberty &amp; Everest</fullName>
            </value>
            <value>
                <fullName>Liberty Only</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Allianz</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Aspen</fullName>
            </value>
            <value>
                <fullName>VSR - FI - RSUI</fullName>
            </value>
            <value>
                <fullName>Bridge Default</fullName>
            </value>
            <value>
                <fullName>VSR - AmWINS - Defense Only</fullName>
            </value>
            <value>
                <fullName>VSR - AmWINS - Funds Mgmt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Retrocession__c.field-meta.xml
<CustomField>
    <fullName>VG_Retrocession__c</fullName>
    <label>Retrocession</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Inception_Date__c</fullName>
    <label>Inception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MissingCBXAlert.cls
/*
Every Hour Cron Exp :
MissingCBXAlert mcbx = new MissingCBXAlert();
String sch = '0 0 * * * ?';
system.schedule('MissingCBXAlert', sch, mcbx);
*/
global class MissingCBXAlert implements Schedulable {

    global void execute(SchedulableContext ctx) {
        List<messaging.Email> emailsList = new List<messaging.Email>();
        String MissingCBX='';
        List<VG_ReInsurance__c> RIList = [Select Id, CreatedDate, VG_UMR__c, VG_UMR__r.Name, VG_UMR__r.RecordType.Name, VG_UMR__r.VG_Capacity_Paper__c, VG_UMR__r.VG_Account__r.Name, VG_UMR__r.VG_Retrocession__c, VG_UMR__r.VG_RI_Inception_Date__c, VG_UMR__r.VG_RI_Expiry_Date__c, VG_Policy_Schedule__r.Name, VG_Policy_Schedule__r.Policy__r.Name, VG_Policy_Schedule__r.Policy__r.Policy_Status__c, VG_Policy_Schedule__r.Policy__r.VG_Expiry_Date__c, VG_Policy_Schedule__r.Policy__r.Insured__r.Name, VG_Policy_Schedule__r.RecordType.Name, VG_Policy_Schedule__c, VG_Policy_Schedule__r.VG_Capacity_Paper__c, VG_Policy_Schedule__r.Policy__r.VG_Inception_Date__c from VG_ReInsurance__c];
        Map<Id, Policy_Schedule__c> psMap = new Map<Id, Policy_Schedule__c>([Select Id, Policy__r.Insured__r.Name, Policy__r.Name, Policy__r.Policy_Status__c, Name, Policy__r.VG_Inception_Date__c, Policy__r.VG_Expiry_Date__c, VG_Capacity_Paper__c from Policy_Schedule__c where Policy__r.Policy_Status__c !='NTU/Decline' AND Policy__r.Policy_Status__c !='Prospect']);
        Set<Id> setIds = new Set<Id>();
        Integer count = 0;
        for(VG_ReInsurance__c RI : RIList){
            setIds.add(RI.VG_Policy_Schedule__c);
        }
        for(Id psId : psMap.keySet()){
            if(!setIds.contains(psId)){
                Policy_Schedule__c ps = psMap.get(psId);
                MissingCBX=MissingCBX+ps.Name+'\n';
            }
        }
        string[]toAdd=new string[]{Label.EmailID_DuplicatePolicyNumberDetector};
        string []ccAdd=new string[]{Label.EmailID2_DuplicatePolicyNumberDetector};
        messaging.SingleEmailMessage email1=new messaging.SingleEmailMessage();
        if(MissingCBX != ''){
            email1.setToAddresses(toAdd);
            email1.setCcAddresses(ccAdd);
            email1.setSubject('Missing Capacity Bordereaux Alert');
            email1.setPlainTextBody('Below Policy Schedule Dont have Capacity Bordereaux :\n'+MissingCBX);
            email1.setSenderDisplayName('Developer Team');
            emailsList.add(email1);
            messaging.sendEmail(emailsList);
        }
    }

}