force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Is_MTA__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_MTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Type__c</fullName>
    <label>MTA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Revision of Cover</fullName>
            </value>
            <value>
                <fullName>Declaration</fullName>
            </value>
            <value>
                <fullName>Reduction</fullName>
            </value>
            <value>
                <fullName>Run-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Rate_Per_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>VG_Rate_Per_Vehicle__c</fullName>
    <label>Annual Rate Per Vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Use__c.field-meta.xml
<CustomField>
    <fullName>VG_Use__c</fullName>
    <label>Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SD&amp;P</fullName>
            </value>
            <value>
                <fullName>Hire &amp; Reward</fullName>
            </value>
            <value>
                <fullName>Private Hire</fullName>
            </value>
            <value>
                <fullName>Public Hire</fullName>
            </value>
            <value>
                <fullName>Own Goods</fullName>
            </value>
            <value>
                <fullName>Business Use – Class 1</fullName>
            </value>
            <value>
                <fullName>Business Use – Class 2</fullName>
            </value>
            <value>
                <fullName>Business Use – Class 3</fullName>
            </value>
            <value>
                <fullName>OBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>Cars – High Value</fullName>
            </value>
            <value>
                <fullName>Buses – 17+ seats</fullName>
            </value>
            <value>
                <fullName>Coaches – 17 + seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 7 seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 16 seats</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 3.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 7.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 12t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 18t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 24t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 30t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 44t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles over 44t</fullName>
            </value>
            <value>
                <fullName>Trade Plate</fullName>
            </value>
            <value>
                <fullName>Ghost Vehicle</fullName>
            </value>
            <value>
                <fullName>Motor Cycle</fullName>
            </value>
            <value>
                <fullName>Special Types</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Cars – Bluelight</fullName>
            </value>
            <value>
                <fullName>Vans – Bluelight</fullName>
            </value>
            <value>
                <fullName>Fire Engine</fullName>
            </value>
            <value>
                <fullName>Ambulance</fullName>
            </value>
            <value>
                <fullName>Motorcycle – Bluelight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VG_ShowPolicyAssets_Ext.cls
Public Class VG_ShowPolicyAssets_Ext{
    public List<VG_Policy_Schedule_Asset__c> psaList{get;set;}
    public List<VG_Policy_Schedule_Asset__c> psaList2{get;set;}
    public Map<String,Decimal> psaMap{get;set;}
    public Map<id,Policy_Schedule__c> psMap{get;set;}
    public String PId{get;set;}
    public VG_ShowPolicyAssets_Ext(){
        psaList=new List<VG_Policy_Schedule_Asset__c>();
        psaList2=new List<VG_Policy_Schedule_Asset__c>();
        psaMap=new Map<String,Decimal>();
        PId=apexpages.currentpage().getparameters().get('id');
        psMap=new Map<id,Policy_Schedule__c>([select id,Name,RecordType.Name from Policy_Schedule__c where Policy__c=:PID AND (VG_Is_MTA__c = FALSE OR (VG_MTA_Type__c = 'Declaration' OR VG_MTA_Type__c = 'Revision of Cover'))]);
        
        psaList=[select id,Name,VG_Number_of_Vehicles__c,VG_Vehicle_Type__c,VG_Use__c,VG_Coverage__c,VG_Rate_Per_Vehicle__c  from VG_Policy_Schedule_Asset__c where VG_Policy_Schedule__c IN: psMap.keyset() order by CreatedDate desc];
        Set<String> types=new Set<String>();
        System.debug('16.10::'+psMap.size()+'::'+psaList.size());
        for(VG_Policy_Schedule_Asset__c psa: psaList){
            //psaMap.put(psa.VG_Vehicle_Type__c, psa.VG_Number_of_Vehicles__c);
            if(!types.contains(psa.VG_Vehicle_Type__c)){
                types.add(psa.VG_Vehicle_Type__c);
            }
        }
        for(String s:types){
            for(VG_Policy_Schedule_Asset__c psa: psaList){
                if(s==psa.VG_Vehicle_Type__c){
                    psaList2.add(psa);
                    if(psaMap.containsKey(s)){
                        if(psa.VG_Number_of_Vehicles__c != null){
                            Decimal nov=psa.VG_Number_of_Vehicles__c+psaMap.get(s);
                            psaMap.put(s, nov);
                        }
                    }else{
                        if(psa.VG_Number_of_Vehicles__c != null){
                            psaMap.put(s, psa.VG_Number_of_Vehicles__c);
                        }else{
                            psaMap.put(s, 0);
                        }
                    }
                }
            }
        }
    }
}