force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VG_GetProfile.cls
public with sharing class VG_GetProfile  {
    @AuraEnabled
    public static String getProfileName(){
        Profile p=[select id,Name from Profile where id=:UserInfo.getProfileId() limit 1];
        return p.Name;
    }
    @AuraEnabled
    public static String getUserInfo(Id psid){
        Profile p=[select id,Name from Profile where id=:UserInfo.getProfileId() limit 1];
        Policy_Schedule__c ps=[select id,Name,Policy__c from Policy_Schedule__c where id=:psid];
        String s=p.Name+','+ps.Policy__c;
        return s;
    }
}