force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_LOB__c/Policy_LOB__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy LOB</label>
</CustomObject>

force-app/main/default/objects/Policy_Record_Type__c/Policy_Record_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy Record Type</label>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SystemConstants__c/SystemConstants__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SystemConstants</label>
</CustomObject>

force-app/main/default/classes/VG_Bridge_Quotation_Test.cls
@IsTest(seeAllData =False)
public class VG_Bridge_Quotation_Test {
    public static testMethod void TestMethod1() {
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Bridge';
        prt.Code__c = 'BDG';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        
        Document d6=new Document();
        d6.Name='Bridge Loge For English Quote';
        d6.Body=blob.valueOf('Hai');
        d6.FolderId='0050O0000078Mug';
        insert d6;
        Document d7=new Document();
        d7.Name='Peter Forsberg';
        d7.Body=blob.valueOf('Hai');
        d7.FolderId='0050O0000078Mug';
        insert d7;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Bridge', acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 11, 12);
        ps.Gross_Written_Premium__c=150000;
        Insert ps;
        ApexPages.currentPage().getParameters().put('Id', ps.id);
        VG_Bridge_Quotation quote=new VG_Bridge_Quotation();        
    }
}