force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/recordTypes/VFP.recordType-meta.xml
<RecordType>
    <fullName>VFP</fullName>
    <active>true</active>
    <label>VFP</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/VFP.recordType-meta.xml
<RecordType>
    <fullName>VFP</fullName>
    <active>true</active>
    <label>VFP</label>
</RecordType>

force-app/main/default/classes/PathSettingController_Test.cls
@IsTest(SeeAllData=False)
public class PathSettingController_Test {
    Public Static TestMethod Void testMenthod1(){  
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('VFP', acc.id);        
        List<String> psIds = new List<String>();
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Policy_Schedule__c ps1=VG_TU.createPolicySchedule(pol.id);
        psIds.add(ps.id);
        psIds.add(ps1.id);
        Test.startTest();        
        PathSettingController.getPSGWP(pol.id);
        //PathSettingController.bookPS(psIds);
        //PathSettingController.getPS(pol.id);
        Test.stopTest();
    }
}