force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>VG_Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
            <value>
                <fullName>Personal Accident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Perils__c.field-meta.xml
<CustomField>
    <fullName>VG_Perils__c</fullName>
    <label>Perils</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number of members</fullName>
            </value>
            <value>
                <fullName>Turnover</fullName>
            </value>
            <value>
                <fullName>Buildings</fullName>
            </value>
            <value>
                <fullName>Outbuildings / Storage containers</fullName>
            </value>
            <value>
                <fullName>Machinery, Plant and All Other Contents</fullName>
            </value>
            <value>
                <fullName>Computer and Electronic Equipment</fullName>
            </value>
            <value>
                <fullName>Gaming, Amusement and Entertainment Equipment</fullName>
            </value>
            <value>
                <fullName>Plate Glass</fullName>
            </value>
            <value>
                <fullName>Stock of Food &amp; General</fullName>
            </value>
            <value>
                <fullName>Stock of Wines, Spirits &amp; Tobacco</fullName>
            </value>
            <value>
                <fullName>Detioration of Stock</fullName>
            </value>
            <value>
                <fullName>Rent Payable</fullName>
            </value>
            <value>
                <fullName>Gross Profit</fullName>
            </value>
            <value>
                <fullName>Gross Revenue</fullName>
            </value>
            <value>
                <fullName>ICOW</fullName>
            </value>
            <value>
                <fullName>Book Debts</fullName>
            </value>
            <value>
                <fullName>Per Premises</fullName>
            </value>
            <value>
                <fullName>Any one Transit</fullName>
            </value>
            <value>
                <fullName>Annual Carryings</fullName>
            </value>
            <value>
                <fullName>Money in Safes</fullName>
            </value>
            <value>
                <fullName>Business Hours</fullName>
            </value>
            <value>
                <fullName>Gaming Machine</fullName>
            </value>
            <value>
                <fullName>Non Negotiable</fullName>
            </value>
            <value>
                <fullName>Employee Effects</fullName>
            </value>
            <value>
                <fullName>Private Dwelling</fullName>
            </value>
            <value>
                <fullName>Any one Loss</fullName>
            </value>
            <value>
                <fullName>Clerical &amp; Managerial</fullName>
            </value>
            <value>
                <fullName>Bar/Catering/Retail/Cleaning</fullName>
            </value>
            <value>
                <fullName>Coaches/Instructors/Players</fullName>
            </value>
            <value>
                <fullName>Maintenance/Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>VG_Sum_Insured__c</fullName>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/classes/VG_LS_PSButtons_DocumentController_Test.cls
@IsTest(seeAllData =False)
public class VG_LS_PSButtons_DocumentController_Test {
	public static testMethod void TestMethod1() {
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');                
        List<Document> dList=new List<Document>();
        Document d1=new Document();
        d1.Name='Motor Felt';
        d1.Body=blob.valueOf('Hai');
        d1.FolderId='0050O0000078Mug';
        dList.add(d1);
        Document d2=new Document();
        d2.Name='VG PI Logo';
        d2.Body=blob.valueOf('Hai');
        d2.FolderId='0050O0000078Mug';
        dList.add(d2);
        Document d3=new Document();
        d3.Name='VG_LS_Affnity_Logo';
        d3.Body=blob.valueOf('Hai');
        d3.FolderId='0050O0000078Mug';
        dList.add(d3);
        Document d4=new Document();
        d4.Name='David Sign';
        d4.Body=blob.valueOf('Hai');
        d4.FolderId='0050O0000078Mug';
        dList.add(d4);
        Document d5=new Document();
        d5.Name='LS EL_Image';
        d5.Body=blob.valueOf('Hai');
        d5.FolderId='0050O0000078Mug';
        dList.add(d5);
        Document d6=new Document();
        d6.Name='Talbir Bains';
        d6.Body=blob.valueOf('Hai');
        d6.FolderId='0050O0000078Mug';
        dList.add(d6);
        insert dList;
        Policy__c pol=VG_TU.createPolicy('Affinity', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.Product__c='PA';
        update ps;   
        VG_Policy_Schedule_Asset__c psa9=VG_TU.createPolicyScheduleAsset(ps.id);
        psa9.VG_Coverage__c='Personal Accident';
        psa9.VG_Perils__c ='Death';
        psa9.VG_Sum_Insured__c=100;
        update psa9;
       Risk_Capture__c rc1=VG_TU.createRiskCapture(ps.id);
        rc1.VG_Additional_Information__c='Personal Accident :'+'Covered'+'<br/>'
            +'Benefit :'+'Covered'+'<br/>'
            +'Medical Costs :'+'Covered'+'<br/>'
            +'Loss of Income :'+'Covered'+'<br/>'
            +'Coma Benefit :'+'Covered'+'<br/>'
            +'Childcare Expenses :'+'Yes'+'<br/>'
            +'Continued Education Expenses :'+'Yes'+'<br/>'
            +'Domestic Expenses :'+'Yes'+'<br/>'
            +'Driver Expenses :'+'Yes'+'<br/>'
            +'Funeral Expenses :'+'Yes'+'<br/>'
            +'Hospital In-Patents Expenses  :'+'Yes'+'<br/>'
            +'Home Modification Expenses  :'+'Yes'+'<br/>'
            +'Number of adult members :'+'100'+'<br/>'
            +'Number of Junior members :'+'500'+'<br/>'
            +'Referees / coaches / Officials :'+'54'+'<br/>'
            +'Clubs :'+'150'+'<br/>';
        update rc1;
        ApexPages.currentPage().getParameters().put('Id', ps.id);
        VG_LS_PSButtons_DocumentController fdc=new VG_LS_PSButtons_DocumentController();
    }
}