force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Governance_Compliance__c.field-meta.xml
<CustomField>
    <fullName>VG_Governance_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Governance &amp; Compliance</label>
    <referenceTo>VG_Governance_Compliance__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/VG_Governance_Compliance__c/VG_Governance_Compliance__c.object-meta.xml
<CustomObject>
    <label>Governance &amp; Compliance</label>
    <nameField>
        <label>Governance &amp; Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance &amp; Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_1__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are parties clearly identified?</description>
    <inlineHelpText>Are parties clearly identified?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VG_Governance_Compliance_Controller_Test.cls
@IsTest(SeeAllData=False)
public class VG_Governance_Compliance_Controller_Test {
    public static testmethod void testmethod1(){
	    VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Bridge',acc.id);
        VG_Governance_Compliance__c gcc=new VG_Governance_Compliance__c();
        gcc.VG_Question_1__c=True;
        insert gcc;
        pol.VG_Governance_Compliance__c=gcc.id;
        update pol;
        ApexPages.StandardController stdController = new ApexPages.StandardController(pol);
        VG_Governance_Compliance_Controller gc=new VG_Governance_Compliance_Controller(stdController);
    }   
}