force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Premium_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment__c</fullName>
    <label>UW Adjustment</label>
    <summarizedField>Policy_Schedule__c.Premium_Adjustment__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <formula>IF(Gross_Written_Premium__c = 0,0,( VG_Brokerage_Amount__c / Gross_Written_Premium__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit of indemnity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Net_Premium__c</fullName>
    <label>Net Model Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Premium_Adjustment_2__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment_2__c</fullName>
    <label>Commercial Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Premium_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment__c</fullName>
    <label>UW Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <label>Signed Share (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Technical_Layer_Premium__c.field-meta.xml
<CustomField>
    <fullName>Technical_Layer_Premium__c</fullName>
    <label>Technical Layer Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Co_Insurance_Parent__c.field-meta.xml
<CustomField>
    <fullName>VG_Co_Insurance_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-Insurance Parent</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Schedules (Co-Insurance Parent)</relationshipLabel>
    <relationshipName>CoInsuranceParent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Exposure_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Exposure_Premium__c</fullName>
    <label>Exposure Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Type__c</fullName>
    <label>MTA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Revision of Cover</fullName>
            </value>
            <value>
                <fullName>Declaration</fullName>
            </value>
            <value>
                <fullName>Reduction</fullName>
            </value>
            <value>
                <fullName>Run-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Exposure_Premium__c/VG_Exposure_Premium__c.object-meta.xml
<CustomObject>
    <label>Exposure Premium</label>
    <nameField>
        <label>Exposure Premium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exposure Premiums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Exposure_Premium__c/fields/VG_Factor_Name__c.field-meta.xml
<CustomField>
    <fullName>VG_Factor_Name__c</fullName>
    <label>Factor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Exposure_Premium__c/fields/VG_Other_Factor__c.field-meta.xml
<CustomField>
    <fullName>VG_Other_Factor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Other Factor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Exposure_Premium__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Exposure Premiums</relationshipLabel>
    <relationshipName>Exposure_Premiums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Exposure_Premium__c/fields/VG_Rate__c.field-meta.xml
<CustomField>
    <fullName>VG_Rate__c</fullName>
    <label>Rate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Exposure_Premium__c/fields/VG_Rating_Factor__c.field-meta.xml
<CustomField>
    <fullName>VG_Rating_Factor__c</fullName>
    <label>Rating Factor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Schedule_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VG_ManageCoInsuranceController_Test.cls
@IsTest(SeeAllData=False)
public class VG_ManageCoInsuranceController_Test {
    public static testmethod void testmethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Bridge',acc.id);
        Policy_Schedule__c ps1=VG_Tu.createPolicySchedule(pol.id);
        ps1.Name= 'BDM/MTR/00040/2017/1/PS/1';
        update ps1;
        Policy_Schedule__c ps= new Policy_Schedule__c();
        ps.Policy__c = pol.id; 
        ps.Name= 'BDM/MTR/00040/2017/1/PS/0';
        ps.Net_Premium__c =44;
        ps.Share__c=100;
        ps.Limit__c=800;
        ps.Technical_Layer_Premium__c=7000;
        ps.Premium_Adjustment__c=7800;
        ps.Premium_Adjustment_2__c=8744;
        ps.VG_Brokerage_Percent__c=15;
        ps.VG_Co_Insurance_Parent__c=ps1.id;
        insert ps;
        VG_UMR__c umr=VG_TU.createUMR(acc.id);
        VG_Policy_Schedule_Asset__c rr=VG_TU.createPolicyScheduleAsset(ps.id); 
        VG_Policy_Schedule_Endorsement__c pse=VG_TU.createPolicyScheduleEndorsement(ps.id);        
        Risk_Capture__c rc = VG_TU.createRiskCapture(ps.id);  
        List<VG_Exposure_Premium__c> expList=new List<VG_Exposure_Premium__c>();
        VG_Exposure_Premium__c exp1 =new VG_Exposure_Premium__c();
        exp1.VG_Factor_Name__c='Hazardous Activity';
        exp1.VG_Other_Factor__c=false;
        exp1.VG_Policy_Schedule__c=ps.id;
        exp1.VG_Rate__c=0.8000;
        exp1.VG_Rating_Factor__c='0.80>Low';
        expList.add(exp1);
        VG_Exposure_Premium__c exp2 =new VG_Exposure_Premium__c();
        exp2.VG_Factor_Name__c='Hazardous Product';
        exp2.VG_Other_Factor__c=false;
        exp2.VG_Policy_Schedule__c=ps.id;
        exp2.VG_Rate__c=1.0000;
        exp2.VG_Rating_Factor__c='1.00>Medium Low';
        expList.add(exp2);        
        Insert expList;
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', ps.id);
        VG_ManageCoInsuranceController.CoInsurance coi = new VG_ManageCoInsuranceController.CoInsurance();
        coi.sharePrecent=48;
        VG_ManageCoInsuranceController mc = new VG_ManageCoInsuranceController();
        mc.addCoInsurance();
        mc.cancel();
        mc.finish();
        mc.Index=1;
        mc.removeCoInsurance();
        Test.stopTest();
       
    }
    
    public static testmethod void testmethod2(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Bridge',acc.id);
        Policy_Schedule__c ps1=VG_Tu.createPolicySchedule(pol.id);
        ps1.Name= 'BDM/MTR/00040/2017/1/PS/0';
        ps1.Product__c='Property';
        ps1.Net_Premium__c =44;
        ps1.Share__c=100;
        ps1.Limit__c=800;
        ps1.Technical_Layer_Premium__c=7000;
        ps1.Premium_Adjustment__c=7800;
        ps1.Premium_Adjustment_2__c=8744;
        ps1.VG_Brokerage_Percent__c=25;
        update ps1;
        Policy_Schedule__c ps= new Policy_Schedule__c();
        ps.Policy__c = pol.id; 
        ps.Product__c='Property';
        ps.Name= 'BDM/MTR/00040/2017/1/PS/1';
        ps.VG_MTA_Type__c='Revision of COver';
    ps.Share__c=100;        
        ps.VG_Co_Insurance_Parent__c=ps1.id;
        insert ps;        
        VG_UMR__c umr=VG_TU.createUMR(acc.id);
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', ps1.id);
        VG_ManageCoInsuranceController.CoInsurance coi = new VG_ManageCoInsuranceController.CoInsurance();
        coi.sharePrecent=48;
        VG_ManageCoInsuranceController mc = new VG_ManageCoInsuranceController();
        mc.Index=0;
        mc.addCoInsurance();
        mc.cancel();
        mc.finish();
        mc.removeCoInsurance();
        Test.stopTest();
       
    }

}