force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>NTU/Decline</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
                <isActive>false</isActive>
                <label>Additional Information Required</label>
            </value>
            <value>
                <fullName>Awaiting Submission</fullName>
                <isActive>false</isActive>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Final Terms Quoted After Negotiations</fullName>
                <isActive>false</isActive>
                <label>Final Terms Quoted After Negotiations</label>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
                <isActive>false</isActive>
                <label>NTU - Capacity</label>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
                <isActive>false</isActive>
                <label>NTU - Other</label>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
                <isActive>false</isActive>
                <label>NTU - Price</label>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
                <isActive>false</isActive>
                <label>NTU - Service</label>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
                <isActive>false</isActive>
                <label>NTU - Terms</label>
            </value>
            <value>
                <fullName>Referral Approval</fullName>
                <isActive>false</isActive>
                <label>Referral Approval</label>
            </value>
            <value>
                <fullName>Submission Received</fullName>
                <isActive>false</isActive>
                <label>Submission Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Capacity)</relationshipLabel>
    <relationshipName>UMR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Capacity_Manager__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capacity_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Currency__c.field-meta.xml
<CustomField>
    <fullName>VG_Currency__c</fullName>
    <label>Original Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VG_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_MGA_Commission__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission__c</fullName>
    <label>Commission (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Binder_Broker__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Binder_Broker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Binder Broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (RI Binder Broker)</relationshipLabel>
    <relationshipName>UMR1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Binder_Commission__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Binder_Commission__c</fullName>
    <label>Binder Broker Commission (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Coverage__c</fullName>
    <label>RI Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>7T</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>D4</fullName>
            </value>
            <value>
                <fullName>D5</fullName>
            </value>
            <value>
                <fullName>D6</fullName>
            </value>
            <value>
                <fullName>D7</fullName>
            </value>
            <value>
                <fullName>TR, X3, XC, XR</fullName>
            </value>
            <value>
                <fullName>B4, B5, P3, P5, P7, 6T, 7T, LE</fullName>
            </value>
            <value>
                <fullName>CB, CC</fullName>
            </value>
            <value>
                <fullName>XM, XN</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>KX, XG, XH</fullName>
            </value>
            <value>
                <fullName>BB, D3, D5, D7, D9, E3, E5, E7, E9, F3, F5, NA, W4, FG, GM</fullName>
            </value>
            <value>
                <fullName>GX, TX, VX, X2, XE, XT</fullName>
            </value>
            <value>
                <fullName>B, CT, GS, JB, G, GC, O, T, TS, V</fullName>
            </value>
            <value>
                <fullName>NX</fullName>
            </value>
            <value>
                <fullName>CY, CZ, KS, KT, N, NB</fullName>
            </value>
            <value>
                <fullName>XY, X1</fullName>
            </value>
            <value>
                <fullName>VL, EG, EH, EZ, EA, EB, EF, H2, H3, L2, L3, AO, AP</fullName>
            </value>
            <value>
                <fullName>SC, SO, SL, V &amp; AP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Inception_Date__c</fullName>
    <label>Inception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Product__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Product__c</fullName>
    <label>RI Product</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Casualty</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Financial Lines</fullName>
            </value>
            <value>
                <fullName>Leisure and Sport</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Professions</fullName>
            </value>
            <value>
                <fullName>Facultative and Treaty Property and Casualty Reinsurance</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Referral_Limit_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Referral_Limit_Premium__c</fullName>
    <label>Referral Premium Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Referral_Limit_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Referral_Limit_Sum_Insured__c</fullName>
    <label>Referral Sum Insured Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Share__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Share__c</fullName>
    <label>Cession Share (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Share_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Share_Type__c</fullName>
    <label>Cession Share Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proportional</fullName>
            </value>
            <value>
                <fullName>Non-proportional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Sum_Insured_Limit__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Sum_Insured_Limit__c</fullName>
    <label>Sum Insured Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Type__c</fullName>
    <label>Cession Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gross</fullName>
            </value>
            <value>
                <fullName>Net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/VG_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>ISK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VG_PolicySheduleButton_Controller_Test.cls
@IsTest(seeAllData =False)
public class VG_PolicySheduleButton_Controller_Test {
    public static testMethod void TestMethod1() {
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Vendor');       
        List<VG_UMR__c> uList=new List<VG_UMR__c>();
        VG_UMR__c u=new VG_UMR__c();
        u.VG_Account__c=acc.id;
        u.Name='Test';
        u.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Edison Motor').getRecordTypeId();
        u.VG_RI_Product__c='Cyber';
        u.VG_RI_Coverage__c='M6 - Third Party Only';
        u.VG_RI_Type__c='Net';
        u.VG_RI_Share_Type__c='Proportional';
        u.VG_RI_Inception_Date__c=Date.newInstance(2017, 11, 18);
        u.VG_RI_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        u.VG_RI_Binder_Broker__c=acc.Id;
        u.VG_Currency__c='CAD';
        u.VG_RI_Share__c=52;
        u.VG_MGA_Commission__c=45;
        u.VG_RI_Binder_Commission__c=28;
        u.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u.VG_RI_Referral_Limit_Premium__c=1528;
        u.VG_RI_Sum_Insured_Limit__c=1258888;
        u.VG_Capacity_Manager__c=UserInfo.getUserId();
        uList.add(u);
        VG_UMR__c u2=new VG_UMR__c();
        u2.VG_Account__c=acc.id;
        u2.Name='Test';
        u2.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Edison Motor').getRecordTypeId();
        u2.VG_RI_Product__c='Cyber';
        u2.VG_RI_Coverage__c='M6 - Third Party Only';
        u2.VG_RI_Type__c='Net';
        u2.VG_RI_Share_Type__c='Proportional';
        u2.VG_RI_Inception_Date__c=Date.newInstance(2017, 11, 18);
        u2.VG_RI_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        u2.VG_RI_Binder_Broker__c=acc.Id;
        u2.VG_Currency__c='CAD';
        u2.VG_RI_Share__c=52;
        u2.VG_MGA_Commission__c=45;
        u2.VG_RI_Binder_Commission__c=28;
        u2.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u2.VG_RI_Referral_Limit_Premium__c=1528;
        u2.VG_RI_Sum_Insured_Limit__c=1258888;
        u2.VG_Capacity_Manager__c=UserInfo.getUserId();
        uList.add(u2);
        Insert uList;
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        //Code added by siddik on 26.2.2018
        pol.Policy_Status__c='NTU/Decline';
        pol.VG_Sub_Status__c='NTU - Price';
        pol.NTU_Or_Declined__c='NTU';
        update pol;
        //Code added finished  on 26.2.2018 
        System.debug('Policy Name::'+pol.Name);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        Insert ps; 
        VG_PolicySheduleButton_Controller.getPolicySchedule(ps.id);
        VG_PolicySheduleButton_Controller.getCurrentUser();
        VG_PolicySheduleButton_Controller.bookPolicySchedule(ps.id);
        VG_PolicySheduleButton_Controller.createActiveNoteAttachment(ps.id);
        VG_PolicySheduleButton_Controller.createEdisonQuotationAttachment(ps.id);
        VG_PolicySheduleButton_Controller.createEdisonScheduleAttachment(ps.id);
        VG_PolicySheduleButton_Controller.createMotorCertificateAttachment(ps.Id);
        VG_PolicySheduleButton_Controller.deletePolicySchedule(ps.id);
    }
}