force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Insured)</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/VG_Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment_URL__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment_URL__c</fullName>
    <formula>IF(BEGINS(VG_Attachment__c, &quot;00P&quot;), &quot;servlet/servlet.FileDownload?file=&quot;+ VG_Attachment__c, &quot;sfc/servlet.shepherd/version/download/&quot;+VG_Attachment__c)</formula>
    <label>Attachment_URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Description__c.field-meta.xml
<CustomField>
    <fullName>VG_Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Folder__c.field-meta.xml
<CustomField>
    <fullName>VG_Folder__c</fullName>
    <label>Folder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Policy Documentation</fullName>
                <default>true</default>
                <label>Policy Documentation</label>
            </value>
            <value>
                <fullName>Pricing Spreadsheet</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Reinsurance</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Policy__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Portal_Name__c.field-meta.xml
<CustomField>
    <fullName>VG_Portal_Name__c</fullName>
    <formula>IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Edison&quot;), &quot;/Edison/&quot;, IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Bridge&quot;), &quot;/Bridge/&quot;,IF(CONTAINS($Api.Partner_Server_URL_290, &quot;VFP&quot;), &quot;/VFP/&quot;,IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Horizon&quot;), &quot;/Horizon/&quot;,
IF(CONTAINS($Api.Partner_Server_URL_290, &quot;LS&quot;), &quot;/LS/&quot;, IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Aesir&quot;), &quot;/Aesir/&quot;, IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Imara&quot;), &quot;/Imara/&quot;,IF(CONTAINS($Api.Partner_Server_URL_290, &quot;Gentium&quot;), &quot;/Gentium/&quot;,IF(CONTAINS($Api.Partner_Server_URL_290, &quot;umr&quot;), &quot;/umr/&quot;, &quot;None&quot;)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VG_PolicyDocumentController.cls
public with sharing class VG_PolicyDocumentController {
    @AuraEnabled
    public static List<String> getUserDocRepoList(){
        User usr = [Select Id,Name,Document_Repository_Access__c from User WHERE username=:UserInfo.getUsername()];
        String docRepo = usr.Document_Repository_Access__c;
        String[] docRepolist = docRepo.split(';');
        System.debug('doc::'+docRepolist);
        return docRepolist;        
    }
    
    @AuraEnabled
    public static List<VG_Attachment__c> getPolicyAttachments(String fName, Id polid){        
        Policy__c pol = [select id, Name, Insured__c from Policy__c where id = :polid limit 1];
        String ProName = [select id, Name from Profile where id = :UserInfo.getProfileId() limit 1].Name;
        List<Policy_Schedule__c> psList = new List<Policy_Schedule__c>([select id, Name from Policy_Schedule__c where Policy__c = :polid]);
        Set<ID> psIds = new Set<ID>();
        for(Policy_Schedule__c ps:psList){
            psIds.add(ps.id);  
        } 
        if(fName == 'Policy Documentation'){
            return[select id, Name, VG_Folder__c, VG_Policy__c, VG_Portal_Name__c,VG_Attachment__c,VG_Attachment_URL__c, CreatedDate, VG_Description__c from VG_Attachment__c where (VG_Folder__c = :fName OR VG_Folder__c = :null) AND (VG_Policy_Schedule__c IN:psIds OR VG_Policy__c = :polid) ORDER BY CreatedDate desc];    
        }else if(fName == 'Pricing Spreadsheet'){
            return[select id, Name, VG_Folder__c, VG_Policy__c, VG_Portal_Name__c,VG_Attachment__c,VG_Attachment_URL__c, CreatedDate, VG_Description__c from VG_Attachment__c where VG_Folder__c = :'Pricing Spreadsheet' AND (VG_Policy_Schedule__c IN:psIds OR VG_Policy__c = :polid) ORDER BY CreatedDate desc];   
        }else{
            return[select id, Name, VG_Folder__c, VG_Policy__c, VG_Portal_Name__c,VG_Attachment__c,VG_Attachment_URL__c, CreatedDate, VG_Description__c from VG_Attachment__c where VG_Folder__c = :fName AND (VG_Policy_Schedule__c IN:psIds OR VG_Policy__c = :polid) ORDER BY CreatedDate desc];   
        }              
    }
    
    @AuraEnabled
    public static Attachment getAttachment(Id attid){
        Attachment att = [select id, Name, Body from Attachment where id = :attid limit 1];
        System.debug('Attachment:'+att);        
        return att;
    }
    
    @AuraEnabled
    public static String insertAttachment(Id polId,String fileStr,String folderName, String attId){
        try{
            List<VG_Attachment__c> customAttachmentList=new List<VG_Attachment__c>();
            system.debug('check::'+fileStr);  
            String[] fileNames = fileStr.split(';');
            String[] attamentIds = attId.split(';');
            List<contentversion> filelist= new List<contentversion>([select id,title,ContentDocumentId from contentversion where ContentDocumentId IN: attamentIds]);                
            Map<Id, ContentDocumentLink> docsList = new Map<Id, ContentDocumentLink>([SELECT ContentDocumentID, ContentDocument.Title, LinkedEntity.type, LinkedEntityId FROM ContentDocumentLink where ContentDocumentID IN: attamentIds]);
            System.debug('filelist::'+filelist.size());
            for(contentversion cv: filelist) {                               
                VG_Attachment__c customAttachment;
                customAttachment = new VG_Attachment__c();
                customAttachment.VG_Attachment__c = cv.Id;
                System.debug('test::'+customAttachment.VG_Attachment__c);
                //customAttachment.Name = fileStr;
                String fileNameFull = cv.title;
                if(fileNameFull.length() > 75){
                    fileNameFull = fileNameFull.substring(0, 74) + '...';
                }
                customAttachment.Name = fileNameFull;
                customAttachment.VG_Folder__c = folderName;
                customAttachment.VG_Policy__c = polId;
                customAttachmentList.add(customAttachment);
                System.debug('customAttachmentList::'+customAttachmentList.size());                
            }
            Insert customAttachmentList;            
            for(ContentDocumentLink CDL : docsList.values()){
                CDL.ShareType = 'I';
                CDL.Visibility = 'AllUsers';
            }
            Update docsList.values();
            return 'Success';
        }catch(exception ex){
            return 'Failed';
        }
    }     
  }