force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/classes/PolicyScheduleAssetTriggerFunction_Test.cls
@IsTest(SeeAllData=False)
public class PolicyScheduleAssetTriggerFunction_Test {
    Public Static TestMethod Void testMethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Vendor');
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        VG_Policy_Schedule_Asset__c psa = VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Asset__c psa1 = VG_TU.createPolicyScheduleAsset(ps.id);
        psa1.VG_Number_of_Vehicles__c=20;
        psa1.VG_Coverage__c='Named perils';
        update psa1;
    }
}