force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <summarizedField>Policy_Schedule__c.Levies__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Premium_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment__c</fullName>
    <label>UW Adjustment</label>
    <summarizedField>Policy_Schedule__c.Premium_Adjustment__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <formula>IF(Gross_Written_Premium__c = 0,0,( VG_Brokerage_Amount__c / Gross_Written_Premium__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Expiry_Date__c</fullName>
    <label>Risk Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <summarizedField>Policy_Schedule__c.VG_Fee_Income__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Base_Creation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Base_Creation_End_Date__c</fullName>
    <label>Base Creation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Base_Creation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Base_Creation_Start_Date__c</fullName>
    <label>Base Creation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT_Percent__c.field-meta.xml
<CustomField>
    <fullName>IPT_Percent__c</fullName>
    <label>IPT (%)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Premium_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment__c</fullName>
    <label>UW Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Base_Policy__c.field-meta.xml
<CustomField>
    <fullName>VG_Base_Policy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Base Policy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Declaration_Type_percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Declaration_Type_percent__c</fullName>
    <label>Declaration Type (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_End_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_End_Date__c</fullName>
    <label>MTA End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Pre_MTA_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Pre_MTA_Expiry_Date__c</fullName>
    <label>Pre MTA Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Endorsement_Details__c.field-meta.xml
<CustomField>
    <fullName>VG_Endorsement_Details__c</fullName>
    <label>Endorsement Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Schedule_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Title__c.field-meta.xml
<CustomField>
    <fullName>VG_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/classes/VG_GentiumStep5_Controller_Test.cls
@IsTest(seeAllData=false)
public class VG_GentiumStep5_Controller_Test {
	public static testmethod void method1(){       
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');    
        VG_UMR__c u=VG_TU.createUMR(acc.id,'Gentium');
        Utilities.SkipMethods('Bridge Context');
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        pol.VG_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        update pol;
        Test.startTest();
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.VG_Base_Policy__c=true;
        ps.IPT_Percent__c=null;
        ps.Base_Creation_End_Date__c=Date.newInstance(2018, 12, 19);
        ps.Base_Creation_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_Cancellation_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_Pre_MTA_Expiry_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_End_Date__c=Date.newInstance(2019, 12, 19);
        ps.Name='Testps';
        update ps;
        
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Risk_Capture__c rc1=VG_TU.createRiskCapture(ps.id);
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Asset__c psa1=VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Endorsement__c pse1=vg_tu.createPolicyScheduleEndorsement(ps.id);
        VG_Policy_Schedule_Endorsement__c pse=new VG_Policy_Schedule_Endorsement__c();
        pse.Name='Test';
        pse.VG_Policy_Schedule__c=ps.id;
        pse.VG_Endorsement_Details__c='Test';
        pse.VG_Premium__c=125695;
        pse.VG_Title__c='Test';
        Insert pse;
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        psaList.add(psa);
        List<VG_Policy_Schedule_Endorsement__c> pseList=new List<VG_Policy_Schedule_Endorsement__c>();
        pseList.add(pse);
        Map<Id,Policy_Schedule__c> psMap=new Map<Id,Policy_Schedule__c>();
        psMap.put(ps.id,ps);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>();
        rcList.add(rc);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('policyid', pol.Id);
        ApexPages.currentPage().getParameters().put('OriginalId', ps.Id); 
        ApexPages.currentPage().getParameters().put('MTAType', null);
        VG_GentiumStep5_Controller gen=new VG_GentiumStep5_Controller();       
        ApexPages.currentPage().getParameters().put('MTAType', 'Cancellation');
        VG_GentiumStep5_Controller gen5=new VG_GentiumStep5_Controller();
        gen5.pSchedule=ps;
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.rcList=rcList;
        gen5.psList=psMap;
        gen5.Previous();
        gen5.pSchedule.VG_MTA_Cancellation_Date__c = null;
        gen5.pSchedule.VG_Brokerage_Percent__c=null;
        gen5.pSchedule.Premium_Adjustment__c=null;
        gen5.pSchedule.IPT_Percent__c = null;
        gen5.pSchedule.Levies__c=null;
        gen5.pSchedule.VG_Fee_Income__c=null;
        gen5.technicalPremiumPro=25000;
        gen5.updateCancelExtendCalc();
        gen5.MTAType='Extension';
        gen5.pSchedule.VG_MTA_End_Date__c=Date.newInstance(2018,2,2);
        gen5.pSchedule.VG_MTA_Start_Date__c=Date.newInstance(2017,2,2);
        gen5.updateCancelExtendCalc();
        gen5.pSchedule.VG_MTA_End_Date__c=null;
        gen5.updateCancelExtendCalc();
        Utilities.clearMethods();
        Test.stopTest();
    }
    
    public static testmethod void method2(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Test.startTest();
        Utilities.SkipMethods('Bridge Context');
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.VG_Base_Policy__c=true;
        ps.VG_Declaration_Type_percent__c=25;
        ps.Base_Creation_End_Date__c=Date.newInstance(2018,12,12);
        ps.Base_Creation_Start_Date__c=Date.newInstance(2017,12,12);
        update ps;
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        psa.VG_Premium__c=12555;
        update psa;
        VG_Policy_Schedule_Endorsement__c pse=new VG_Policy_Schedule_Endorsement__c();
        pse.Name='Test';
        pse.VG_Policy_Schedule__c=ps.id;
        pse.VG_Endorsement_Details__c='Test';
        pse.VG_Premium__c=125695;
        pse.VG_Title__c='Test';
        Insert pse;
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        psaList.add(psa);
        Map<Id,Policy_Schedule__c> psMap=new Map<Id,Policy_Schedule__c>();
        psMap.put(ps.id,ps);
        List<VG_Policy_Schedule_Endorsement__c> pseList=new List<VG_Policy_Schedule_Endorsement__c>();
        pseList.add(pse);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>();
        rcList.add(rc);
        
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('policyid', pol.Id);
        ApexPages.currentPage().getParameters().put('OriginalId', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Declaration');
        VG_GentiumStep5_Controller gen5=new VG_GentiumStep5_Controller();
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.rcList=rcList;
        gen5.psList=psMap;
        gen5.Previous();
        gen5.psaList=psaList;
        gen5.rcList=rcList;
        gen5.psList=psMap;
        gen5.pseList=pseList;
        gen5.Finish();
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.psList=psMap;
        gen5.rcList=rcList;
        gen5.Finish();
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.psList=psMap;
        gen5.rcList=rcList;
        gen5.Cancel();
        gen5.psaList=psaList;
        gen5.rcList=rcList;
        gen5.psList=psMap;
        gen5.pseList=pseList;
        gen5.pSchedule.VG_Brokerage_Percent__c=null;
        gen5.pSchedule.Premium_Adjustment__c=null;
        gen5.pSchedule.IPT_Percent__c = null;
        gen5.pSchedule.Levies__c=null;
        gen5.pSchedule.VG_Fee_Income__c=null;
        gen5.technicalPremiumPro=25000;
        gen5.updateCalc();
        gen5.pSchedule.VG_Fee_Income__c=null;
        gen5.pSchedule.Levies__c=2000;
        gen5.updateCalc();
        gen5.pSchedule.VG_Fee_Income__c=2000;
        gen5.pSchedule.Levies__c=null;
        gen5.updateCalc();
        Utilities.clearMethods();
        Test.stopTest();
    }
   
    public static testmethod void method8(){
        //Main focus to Cover all codes for updateCancelExtendCalc()
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');    
        VG_UMR__c u=VG_TU.createUMR(acc.id,'Gentium');
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        pol.VG_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        update pol;
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.VG_Base_Policy__c=true;
        ps.IPT_Percent__c=null;
        ps.Base_Creation_End_Date__c=Date.newInstance(2018, 12, 19);
        ps.Base_Creation_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_Cancellation_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_Pre_MTA_Expiry_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_End_Date__c=Date.newInstance(2019, 12, 19);
        ps.Name='Testps';
        update ps;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('policyid', pol.Id);
        ApexPages.currentPage().getParameters().put('OriginalId', ps.Id); 
        ApexPages.currentPage().getParameters().put('MTAType', 'Cancellation');
        VG_GentiumStep5_Controller gen5=new VG_GentiumStep5_Controller();
        gen5.updateCancelExtendCalc();
        gen5.pSchedule.VG_MTA_Cancellation_Date__c=date.newInstance(2018,12,01);
        gen5.updateCancelExtendCalc();
        
    }
    public static testmethod void method3(){
        VG_TU.policyCustomSetting();
        Utilities.SkipMethods('Bridge Context');
        Account acc=VG_TU.createAccount('Customer');    
        VG_UMR__c u=VG_TU.createUMR(acc.id,'Gentium');
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.VG_Base_Policy__c=true;
        ps.IPT_Percent__c=null;
        ps.Base_Creation_End_Date__c=Date.newInstance(2018, 12, 19);
        ps.Base_Creation_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_Cancellation_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_Pre_MTA_Expiry_Date__c=Date.newInstance(2018, 12, 19);
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 12, 19);
        ps.VG_MTA_End_Date__c=Date.newInstance(2019, 12, 19);
        ps.Name='Testps';
        update ps;
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        psa.VG_Premium__c=12555;
        update psa;
		
        VG_Policy_Schedule_Endorsement__c pse=new VG_Policy_Schedule_Endorsement__c();
        pse.Name='Test';
        pse.VG_Policy_Schedule__c=ps.id;
        pse.VG_Endorsement_Details__c='Test';
        pse.VG_Premium__c=125695;
        pse.VG_Title__c='Test';
        Insert pse;
		
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        psaList.add(psa);
		
        Map<Id,Policy_Schedule__c> psMap=new Map<Id,Policy_Schedule__c>();
        psMap.put(ps.id,ps);
        List<VG_Policy_Schedule_Endorsement__c> pseList=new List<VG_Policy_Schedule_Endorsement__c>();
        pseList.add(pse);
		
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>();
        rcList.add(rc);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('policyid', pol.Id);
        ApexPages.currentPage().getParameters().put('OriginalId', ps.Id); 
        ApexPages.currentPage().getParameters().put('MTAType', 'Cancellation');
        test.startTest();
        VG_GentiumStep5_Controller gen5=new VG_GentiumStep5_Controller();
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.rcList=rcList;
        gen5.psList=psMap;
        gen5.Previous();
        gen5.Finish();
        gen5.psaList=psaList;
        gen5.pseList=pseList;
        gen5.psList=psMap;
        gen5.rcList=rcList;
        gen5.pSchedule.VG_MTA_Cancellation_Date__c=date.newInstance(2018,12,01); 
        gen5.IsCancellation = True;
        gen5.MTAType='Cancellation';
        gen5.Finish();
        Utilities.clearMethods();
        test.stopTest();
    }
    
   
}