force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Insured)</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/MTA_Cancel_List__c.field-meta.xml
<CustomField>
    <fullName>MTA_Cancel_List__c</fullName>
    <label>MTA_Cancel_List</label>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_MTA_Type__c</field>
        <operation>equals</operation>
        <value>Cancellation</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>NTU/Decline</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
                <isActive>false</isActive>
                <label>Additional Information Required</label>
            </value>
            <value>
                <fullName>Awaiting Submission</fullName>
                <isActive>false</isActive>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Final Terms Quoted After Negotiations</fullName>
                <isActive>false</isActive>
                <label>Final Terms Quoted After Negotiations</label>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
                <isActive>false</isActive>
                <label>NTU - Capacity</label>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
                <isActive>false</isActive>
                <label>NTU - Other</label>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
                <isActive>false</isActive>
                <label>NTU - Price</label>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
                <isActive>false</isActive>
                <label>NTU - Service</label>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
                <isActive>false</isActive>
                <label>NTU - Terms</label>
            </value>
            <value>
                <fullName>Referral Approval</fullName>
                <isActive>false</isActive>
                <label>Referral Approval</label>
            </value>
            <value>
                <fullName>Submission Received</fullName>
                <isActive>false</isActive>
                <label>Submission Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Is_Renewal__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Renewal?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Renewal_Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>VG_Renewal_Policy_Id__c</fullName>
    <label>Renewal Policy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Imara.recordType-meta.xml
<RecordType>
    <fullName>Imara</fullName>
    <active>true</active>
    <label>Imara</label>
</RecordType>

force-app/main/default/classes/VG_Alpha_Policy_ButtonsController.cls
public with sharing class VG_Alpha_Policy_ButtonsController {
    @AuraEnabled
    public static List<Policy__c> getPolicyStatus(Id polId){
        List<Policy__c> polList=new List<Policy__c>();
        Policy__c pol=[select id,Name,Policy_Status__c,VG_Is_Renewal__c,CurrencyIsoCode,VG_Renewal_Policy_Id__c,Insured__c,MTA_Cancel_List__c from Policy__c where id=:polId limit 1];
        polList.add(pol);
        if(pol.VG_Renewal_Policy_Id__c!=null){
            Policy__c renewalPol=[select id,Name,Policy_Status__c,VG_Is_Renewal__c,CurrencyIsoCode,VG_Renewal_Policy_Id__c,Insured__c,MTA_Cancel_List__c from Policy__c where id=:pol.VG_Renewal_Policy_Id__c limit 1];
            polList.add(renewalPol);
        }
        return polList;
    }    
    
    @AuraEnabled
    public static String createRenewalPolicy(Id policyId){
        return  VG_RenewalController.createRenewalPolicy(policyId,'Imara');
    }
    
    @AuraEnabled
    public static Id getBasePolicy(Id polId){
        Policy__c pol = [select id, Name, Policy_Status__c, CurrencyIsoCode, VG_Renewal_Policy_Id__c, Insured__c, VG_Is_Renewal__c, MTA_Cancel_List__c from Policy__c where VG_Renewal_Policy_Id__c=:polId limit 1];
        System.debug('polid:'+pol.id);
        return pol.id;
    }
}