force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Renewal_Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>VG_Renewal_Policy_Id__c</fullName>
    <label>Renewal Policy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/classes/VG_Horizon_Policy_ButtonsController_Test.cls
@IsTest(SeeAllData=False)
public class VG_Horizon_Policy_ButtonsController_Test {
    public Static Testmethod Void method1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Horizon', acc.id);        
        Policy__c pol1=pol.clone(false,true,false,false);
        pol1.VG_Renewal_Policy_Id__c = pol.id;       
        Insert pol1;        
        Test.startTest();          
        VG_Horizon_Policy_ButtonsController.getPolicyStatus(pol1.id);
        VG_Horizon_Policy_ButtonsController.createRenewalPolicy(pol.Id);
        VG_Horizon_Policy_ButtonsController.getBasePolicy(pol.Id); 
        Test.stopTest();
    }
}