force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <summarizedField>Policy_Schedule__c.Levies__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <summarizedField>Policy_Schedule__c.VG_Fee_Income__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Is_MTA__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_MTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/classes/VG_ShowPolicyAssets_Ext_Test.cls
@IsTest(seeAllData =False)
public class VG_ShowPolicyAssets_Ext_Test {
    public static testmethod void method1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c();
        ps.Name='Test';
        ps.Policy__c=pol.id;  
        ps.VG_Is_MTA__c=False;
        ps.VG_Status__c='Booked';
        ps.Levies__c=14;
        ps.VG_Fee_Income__c=2000;
        Insert ps;
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Asset__c psa2=VG_TU.createPolicyScheduleAsset(ps.id);
        apexpages.currentpage().getparameters().put('id',pol.id);
        VG_ShowPolicyAssets_Ext spe=new VG_ShowPolicyAssets_Ext();
    }
}