force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Insured)</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Transaction_GWP__c.field-meta.xml
<CustomField>
    <fullName>Transaction_GWP__c</fullName>
    <label>Transaction Premium</label>
    <summarizedField>Policy_Schedule__c.Transaction_GWP__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Please select the Underwriter is only Partner user</errorMessage>
        <filterItems>
            <field>User.VG_Underwriter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <formula>IF(Gross_Written_Premium__c = 0,0,( VG_Brokerage_Amount__c / Gross_Written_Premium__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Quoted_Time__c.field-meta.xml
<CustomField>
    <fullName>VG_Quoted_Time__c</fullName>
    <label>Quoted Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/ILF_Layer__c.field-meta.xml
<CustomField>
    <fullName>ILF_Layer__c</fullName>
    <label>ILF Layer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit of indemnity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Technical_Layer_Premium__c.field-meta.xml
<CustomField>
    <fullName>Technical_Layer_Premium__c</fullName>
    <label>Technical Layer Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Transaction_GWP__c.field-meta.xml
<CustomField>
    <fullName>Transaction_GWP__c</fullName>
    <label>Transaction Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Translation__mdt/Translation__mdt.object-meta.xml
<CustomObject>
    <label>Translation</label>
    <pluralLabel>Translations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Translation__mdt/fields/From_Language__c.field-meta.xml
<CustomField>
    <fullName>From_Language__c</fullName>
    <label>From Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Translation__mdt/fields/Language1__c.field-meta.xml
<CustomField>
    <fullName>Language1__c</fullName>
    <label>Language1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__mdt/fields/Language2__c.field-meta.xml
<CustomField>
    <fullName>Language2__c</fullName>
    <label>Language2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__mdt/fields/To_Language__c.field-meta.xml
<CustomField>
    <fullName>To_Language__c</fullName>
    <label>To Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Swedish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VG_Bridge_Quotation.cls
public class VG_Bridge_Quotation{
    public String LogoURL{get;set;}
    public String PrintView{get;set;}
    public String psId{get;set;}
    public String Sign_Url{get;set;}
    public String underwriter{get;set;}
    public Date QuoteDate{get;set;}
    public String today{get;set;}
    public Id parentId{get;set;}
    public Decimal total{get;set;}
    public Date date1{get;set;}
    Public Policy_Schedule__c ps{get;set;}
    Public List<Policy_Schedule__c> psList{get;set;}
    Public Map<String,String> transdata{get;set;}
    public VG_Bridge_Quotation(){
        total=0;
        psList=new List<Policy_Schedule__c>();
        psId=apexpages.currentpage().getparameters().get('Id');       
        ps=[Select Id,Name,Policy__c,Policy__r.Insured__r.Name,VG_Brokerage_Percent__c,Commission__c,Policy__r.Underwriter__r.Name,Policy__r.Transaction_GWP__c,Policy__r.VG_Quoted_Time__c from Policy_Schedule__c Where Id=:psId];        
        parentId =ps.Policy__c;
        psList=[Select Id,Name,Policy__c,Policy__r.Insured__r.Name,Product__c,ILF_Layer__c,Technical_Layer_Premium__c,Attachment__c,Limit__c,Gross_Written_Premium__c from Policy_Schedule__c Where Policy__c=:parentId];
        for(Policy_Schedule__c ps:psList){
           If(ps.Gross_Written_Premium__c!=null)
              total += ps.Gross_Written_Premium__c;
        }
         today=System.Today().format();
         date1 = Date.parse(today);
         if(ps.Policy__r.VG_Quoted_Time__c!=null){
          QuoteDate = date.newinstance(ps.Policy__r.VG_Quoted_Time__c.year(),ps.Policy__r.VG_Quoted_Time__c.month(),ps.Policy__r.VG_Quoted_Time__c.day());
         }
         transdata = new Map<String,String>();
         Translation__mdt [] translist=[SELECT From_Language__c,To_Language__c,Language1__c,Language2__c From Translation__mdt];        
         System.debug('11-9 test::'+translist);
         for(Translation__mdt trs : translist){
            System.debug('11-9 test::'+trs.Language1__c+'::'+trs);
            transdata.put(trs.Language1__c,trs.Language2__c);
            System.debug('11-9 Keys::'+trs.Language1__c+'::'+trs.Language2__c);
         }
         string strOrgId = UserInfo.getOrganizationId();
         List< document > documentList = [select Id, name from document where Name='Bridge Loge For English Quote'];
         LogoURL=LogoURL+documentList[0].Id;
         LogoURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Bridge/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId; 
         documentList.clear();
         if(ps.Policy__r.Underwriter__r.Name!=null){
            underwriter=ps.Policy__r.Underwriter__r.Name;
            documentList = [select Id, name from document where Name=:underwriter];    
            if(documentList.size()>0)
                Sign_Url = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Bridge/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;                           
        }
        documentList.clear();
         PrintView='<!--[if gte mso 9]>' +
        '<xml>' +
        '<w:WordDocument>' +
        '<w:View>Print</w:View>' +
        '<w:Zoom>100</w:Zoom>' +
        '<w:DoNotOptimizeForBrowser/>' +
        '</w:WordDocument>' +
        '</xml>' +
        '<![endif]>';  
    }
}