force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_LOB__c/Policy_LOB__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy LOB</label>
</CustomObject>

force-app/main/default/objects/Policy_Record_Type__c/Policy_Record_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy Record Type</label>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Current_Plan_Rate__c.field-meta.xml
<CustomField>
    <fullName>VG_Current_Plan_Rate__c</fullName>
    <label>Current Plan Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VG_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SystemConstants__c/SystemConstants__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SystemConstants</label>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/VG_Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Folder__c.field-meta.xml
<CustomField>
    <fullName>VG_Folder__c</fullName>
    <label>Folder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Policy Documentation</fullName>
                <default>true</default>
                <label>Policy Documentation</label>
            </value>
            <value>
                <fullName>Pricing Spreadsheet</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Reinsurance</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Policy__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/VG_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>ISK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VG_PolicyDocumentController_Test.cls
@IsTest(SeeAllData=false)
public class VG_PolicyDocumentController_Test {
    public Static Testmethod Void method1(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        ps.VG_Current_Plan_Rate__c='USD';
        ps.CurrencyIsoCode='GBP';
        ps.VG_Status__c='Draft';
        Insert ps;
        Attachment att=new Attachment();
        att.Name='Test';
        att.Body=Blob.valueOf('Registration Number,Make,Model,CC,GVW,Seats,Date Added,Date Deleted,Status \nRM 1234,Honda,Accord,200.05,0.5,5,20/11/2017,22/11/2017,Active \n');      
        att.ParentId=pol.id;
        Insert att;
        VG_Attachment__c cusAtt=new VG_Attachment__c();
        cusAtt.Name='Test';
        cusAtt.VG_Folder__c='Underwriting';
        cusAtt.VG_Policy__c=pol.id;
        cusAtt.VG_Attachment__c=att.id;
        Insert cusAtt;
        VG_PolicyDocumentController.getPolicyAttachments('Underwriting',pol.id);
        VG_PolicyDocumentController.getAttachment(att.id);
        VG_PolicyDocumentController.getUserDocRepoList();
    }
    
    public Static Testmethod Void method2(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        ps.VG_Current_Plan_Rate__c='USD';
        ps.CurrencyIsoCode='GBP';
        ps.VG_Status__c='Draft';
        Insert ps;
        Attachment att=new Attachment();
        att.Name='Test';
        att.Body=Blob.valueOf('Registration Number,Make,Model,CC,GVW,Seats,Date Added,Date Deleted,Status \nRM 1234,Honda,Accord,200.05,0.5,5,20/11/2017,22/11/2017,Active \n');      
        att.ParentId=pol.id;
        Insert att;
        VG_Attachment__c cusAtt=new VG_Attachment__c();
        cusAtt.Name='Test';
        cusAtt.VG_Folder__c='Underwriting';
        cusAtt.VG_Policy__c=pol.id;
        cusAtt.VG_Attachment__c=att.id;
        Insert cusAtt;
        VG_PolicyDocumentController.getPolicyAttachments('Policy Documentation',pol.id);
        VG_PolicyDocumentController.getPolicyAttachments('Pricing Spreadsheet',pol.id);
        VG_PolicyDocumentController.getAttachment(att.id);
        VG_PolicyDocumentController.insertAttachment(pol.id, 'Test;', 'Policy Documentation', att.Id);
        
    }
    /*public Static Testmethod Void method3(){
        Account acc1=new Account();
        acc1.Name='Test ACC';
        acc1.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Volante Team').getRecordTypeId();
        acc1.Industry='Energy';
        acc1.ShippingStreet='Test Street';
        acc1.ShippingCity='Test City';
        acc1.ShippingCountry='TC';
        acc1.Phone='9876543210';
        Insert acc1;
        Contact con=VG_TU.createContact(acc1);
        Id p = [select id from profile where name='UMR Partner Community'].id;
        User user = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id,
                timezonesidkey='America/Los_Angeles', username='UMRPartneruser@noemail.com');
       
        insert user;
        
        system.runAs(user) {
        }
            SystemConstants__c cs = new SystemConstants__c();
            cs.Name='Latest Policy Name';
            cs.DocumentId__c = 'Reset';
            Insert cs;
            Policy_Record_Type__c prt = new Policy_Record_Type__c ();
            prt.Name='Edison Motor';
            prt.Code__c = 'EM';
            Insert prt;
            Policy_LOB__c lob = new Policy_LOB__c();
            lob.Name='Motor';
            lob.Code__c = 'MTR';
            Insert lob;
            Account acc=VG_TU.createAccount('Customer');
            Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
            Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
            ps.Policy__c=pol.id;
            ps.VG_Current_Plan_Rate__c='USD';
            ps.CurrencyIsoCode='GBP';
            ps.VG_Status__c='Draft';
            Insert ps;
            Attachment att=new Attachment();
            att.Name='Test';
            att.Body=Blob.valueOf('Registration Number,Make,Model,CC,GVW,Seats,Date Added,Date Deleted,Status \nRM 1234,Honda,Accord,200.05,0.5,5,20/11/2017,22/11/2017,Active \n');      
            att.ParentId=pol.id;
            Insert att;
            VG_Attachment__c cusAtt=new VG_Attachment__c();
            cusAtt.Name='Test';
            cusAtt.VG_Folder__c='Underwriting';
            cusAtt.VG_Policy__c=pol.id;
            cusAtt.VG_Attachment__c=att.id;
            Insert cusAtt;
            VG_PolicyDocumentController.getPolicyAttachments('Policy Documentation',pol.id);
            VG_PolicyDocumentController.getPolicyAttachments('Pricing spreashsheet',pol.id);
            VG_PolicyDocumentController.getPolicyAttachments('Finance',pol.id);
            VG_PolicyDocumentController.getAttachment(att.id);
    }*/
}