force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/MTA_Cancel_List__c.field-meta.xml
<CustomField>
    <fullName>MTA_Cancel_List__c</fullName>
    <label>MTA_Cancel_List</label>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_MTA_Type__c</field>
        <operation>equals</operation>
        <value>Cancellation</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>NTU/Decline</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
                <isActive>false</isActive>
                <label>Additional Information Required</label>
            </value>
            <value>
                <fullName>Awaiting Submission</fullName>
                <isActive>false</isActive>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Final Terms Quoted After Negotiations</fullName>
                <isActive>false</isActive>
                <label>Final Terms Quoted After Negotiations</label>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
                <isActive>false</isActive>
                <label>NTU - Capacity</label>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
                <isActive>false</isActive>
                <label>NTU - Other</label>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
                <isActive>false</isActive>
                <label>NTU - Price</label>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
                <isActive>false</isActive>
                <label>NTU - Service</label>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
                <isActive>false</isActive>
                <label>NTU - Terms</label>
            </value>
            <value>
                <fullName>Referral Approval</fullName>
                <isActive>false</isActive>
                <label>Referral Approval</label>
            </value>
            <value>
                <fullName>Submission Received</fullName>
                <isActive>false</isActive>
                <label>Submission Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NTU_Or_Declined__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Submission Received</fullName>
            </value>
            <value>
                <fullName>Additional Info Required</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Decline - Price</fullName>
            </value>
            <value>
                <fullName>Decline - Risk Profile</fullName>
            </value>
            <value>
                <fullName>Decline - Quality of Risk</fullName>
            </value>
            <value>
                <fullName>Decline - Location</fullName>
            </value>
            <value>
                <fullName>Decline - Attachment</fullName>
            </value>
            <value>
                <fullName>Decline - Terms / Wording</fullName>
            </value>
            <value>
                <fullName>Decline - Licensing Restrictions</fullName>
            </value>
            <value>
                <fullName>Decline - Territorial Scope</fullName>
            </value>
            <value>
                <fullName>Decline - Line of Business</fullName>
            </value>
            <value>
                <fullName>Decline - Type of Business e.g Direct vs QS</fullName>
            </value>
            <value>
                <fullName>Decline - Binding Authority Restrictions</fullName>
            </value>
            <value>
                <fullName>Decline - Referall Declined</fullName>
            </value>
            <value>
                <fullName>Decline - Conflict with Volante Capacity Provider</fullName>
            </value>
            <value>
                <fullName>Decline - Aggregation with carrier</fullName>
            </value>
            <value>
                <fullName>Decline - Assured Financials</fullName>
            </value>
            <value>
                <fullName>Decline - Other</fullName>
            </value>
            <value>
                <fullName>Decline - Duplicate</fullName>
            </value>
            <value>
                <fullName>NTU - Renewed with Existing Panel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Is_MTA__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_MTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Type__c</fullName>
    <label>MTA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Revision of Cover</fullName>
            </value>
            <value>
                <fullName>Declaration</fullName>
            </value>
            <value>
                <fullName>Reduction</fullName>
            </value>
            <value>
                <fullName>Run-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/VG_Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Folder__c.field-meta.xml
<CustomField>
    <fullName>VG_Folder__c</fullName>
    <label>Folder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Underwriting</fullName>
            </value>
            <value>
                <fullName>Policy Documentation</fullName>
                <default>true</default>
                <label>Policy Documentation</label>
            </value>
            <value>
                <fullName>Pricing Spreadsheet</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Reinsurance</fullName>
            </value>
            <value>
                <fullName>Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VG_PolicySheduleButton_Controller.cls
//All Document saved to Policy Documentation folder.this is changed by siddik on 27.2.2018
public with Sharing class VG_PolicySheduleButton_Controller {
    @AuraEnabled
    public static Policy_Schedule__c getPolicySchedule(Id psId){
        System.debug('Stat::'+psId);
        Policy_Schedule__c ps=[select id,Name,Policy__c,Policy__r.MTA_Cancel_List__c,Policy__r.Policy_Status__c,Policy__r.VG_Sub_Status__c,VG_Status__c,VG_MTA_Type__c,VG_Is_MTA__c from Policy_Schedule__c where id=:psId limit 1];
        System.debug('Stat::'+ps);
        return ps;
    }
    @AuraEnabled
    public static String getCurrentUser(){
        String user=UserInfo.getName();
        return user;
    }
    @AuraEnabled
    public static String deletePolicySchedule(Id psId){
        Policy_Schedule__c ps=[select id,Policy__c from Policy_Schedule__c where id=:psId limit 1];
        String policyId=ps.Policy__c;   
        delete ps;
        return policyId;
    }
    
    @AuraEnabled
    public static void bookPolicySchedule(Id psId){
        Policy_Schedule__c ps=new Policy_Schedule__c();
        ps.id=psId;
        ps.VG_Status__c='Booked';
        update ps;
    }
    @AuraEnabled
    Public Static Void createActiveNoteAttachment(Id psId){
            Policy_Schedule__c ps=[select id,Name,VG_Status__c from Policy_Schedule__c where id=:psId limit 1];
            System.debug('Stat2::'+ps);    
            VG_Attachment__c customAttachment;
            Attachment attachment= new Attachment();
            PageReference policyPDF;
            policyPDF = Page.VG_Active_Note;
            policyPDF.getParameters().put('Id',psId);
            policyPDF.setRedirect(true);
            if(policyPDF != null){
                Blob body;
                if(!test.isRunningTest()){
                    body = policyPDF.getContent();//policyPDF.getContentAsPDF();
                }else{
                    body = blob.valueof('TEST');
                }
                //body = policyPDF.getContentAsPDF();
                System.debug('Body is:'+body);
                attachment.body = body;
                attachment.name ='Advice Note '+System.today().format()+'.doc';
                attachment.parentId = psId;
                Insert attachment;
                System.debug('attachment::'+attachment);
                customAttachment = new VG_Attachment__c();
                customAttachment.VG_Attachment__c = attachment.Id;
                customAttachment.VG_Folder__c='Policy Documentation';
                customAttachment.VG_Policy_Schedule__c=attachment.parentId;
                customAttachment.Name = attachment.Name;
                Insert customAttachment;
                System.debug('customAttachment::'+customAttachment);
            }
        }
    @AuraEnabled
    Public Static Void createEdisonQuotationAttachment(Id psId){
            Policy_Schedule__c ps=[select id,Name,VG_Status__c from Policy_Schedule__c where id=:psId limit 1];
            System.debug('Stat2::'+ps);    
            VG_Attachment__c customAttachment;
            Attachment attachment= new Attachment();
            PageReference policyPDF;
            policyPDF = Page.VG_Edison_Quotation_PS;
            policyPDF.getParameters().put('Id',psId);
            policyPDF.setRedirect(true);
            if(policyPDF != null){
                Blob body;
                if(!test.isRunningTest()){
                    body = policyPDF.getContent();//policyPDF.getContentAsPDF();
                }else{
                    body = blob.valueof('TEST');
                }
                //body = policyPDF.getContentAsPDF();
                System.debug('Body is:'+body);
                attachment.body = body;
                attachment.name ='Edison Quote '+System.today().format()+'.doc';
                attachment.parentId = psId;
                Insert attachment;
                System.debug('attachment::'+attachment);
                customAttachment = new VG_Attachment__c();
                customAttachment.VG_Attachment__c = attachment.Id;
                customAttachment.VG_Folder__c='Policy Documentation';
                customAttachment.VG_Policy_Schedule__c=attachment.parentId;
                customAttachment.Name = attachment.Name;
                Insert customAttachment;
                System.debug('customAttachment::'+customAttachment);
            }
        }
    
    @AuraEnabled
    Public Static Void createEdisonScheduleAttachment(Id psId){
            Policy_Schedule__c ps=[select id,Name,VG_Status__c,Policy__c from Policy_Schedule__c where id=:psId limit 1];
            System.debug('Stat2::'+ps);    
            VG_Attachment__c customAttachment;
            Attachment attachment= new Attachment();
            PageReference policyPDF;
            policyPDF = Page.VG_Edison_Schedule;
            policyPDF.getParameters().put('Id',psId);
            policyPDF.setRedirect(true);
            if(policyPDF != null){
                Blob body;
                if(!test.isRunningTest()){
                    body = policyPDF.getContent();//policyPDF.getContentAsPDF();
                }else{
                    body = blob.valueof('TEST');
                }
                //body = policyPDF.getContentAsPDF();
                System.debug('Body is:'+body);
                attachment.body = body;
                attachment.name ='Edison Schedule '+System.today().format()+'.doc';
                attachment.parentId = psId;
                Insert attachment;
                System.debug('attachment::'+attachment);
                customAttachment = new VG_Attachment__c();
                customAttachment.VG_Attachment__c = attachment.Id;
                customAttachment.VG_Folder__c='Policy Documentation';
                customAttachment.VG_Policy_Schedule__c=attachment.parentId;
                customAttachment.Name = attachment.Name;
                Insert customAttachment;
                System.debug('customAttachment::'+customAttachment);
            }
        }
        
        
    @AuraEnabled
    Public Static Void createMotorCertificateAttachment(Id psId){
            Policy_Schedule__c ps=[select id,Name,VG_Status__c from Policy_Schedule__c where id=:psId limit 1];
            System.debug('Stat2::'+ps);    
            VG_Attachment__c customAttachment;
            Attachment attachment= new Attachment();
            PageReference policyPDF;
            policyPDF = Page.VG_Motor_Insurance;
            policyPDF.getParameters().put('Id',psId);
            policyPDF.setRedirect(true);
            if(policyPDF != null){
                Blob body;
                if(!test.isRunningTest()){
                    body = policyPDF.getContent();//policyPDF.getContentAsPDF();
                }else{
                    body = blob.valueof('TEST');
                }
                //body = policyPDF.getContentAsPDF();
                System.debug('Body is:'+body);
                attachment.body = body;
                attachment.name ='Motor Certificate '+System.today().format()+'.doc';
                attachment.parentId = psId;
                Insert attachment;
                System.debug('attachment::'+attachment);
                customAttachment = new VG_Attachment__c();
                customAttachment.VG_Attachment__c = attachment.Id;
                customAttachment.VG_Folder__c='Policy Documentation';
                customAttachment.VG_Policy_Schedule__c=attachment.parentId;
                customAttachment.Name = attachment.Name;
                Insert customAttachment;
                System.debug('customAttachment::'+customAttachment);
            }
        }
}