force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Renewal_Policy_Id__c.field-meta.xml
<CustomField>
    <fullName>VG_Renewal_Policy_Id__c</fullName>
    <label>Renewal Policy Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/classes/VG_Aesir_Policy_ButtonsController_Test.cls
@IsTest(SeeAllData=False)
public class VG_Aesir_Policy_ButtonsController_Test {
    Public Static TestMethod Void testMethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Aesir', acc.id);        
        Policy__c pol1=pol.clone(false,true,false,false);
        pol1.VG_Renewal_Policy_Id__c = pol.id;       
        Insert pol1;        
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Test.startTest();       
        VG_Aesir_Policy_ButtonsController.createRenewalPolicy(pol.id);
        VG_Aesir_Policy_ButtonsController.getPolicyStatus(pol1.id);
        VG_Aesir_Policy_ButtonsController.getBasePolicy(pol.id);
        Test.stopTest();
        
    }
}