force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_LOB__c/Policy_LOB__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy LOB</label>
</CustomObject>

force-app/main/default/objects/Policy_Record_Type__c/Policy_Record_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Policy Record Type</label>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Claims__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Claims__c</fullName>
    <label>Drivers Claims</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Conviction_Points__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Conviction_Points__c</fullName>
    <label>Drivers Conviction Points</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Convictions__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Convictions__c</fullName>
    <label>Drivers Convictions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC10</fullName>
            </value>
            <value>
                <fullName>AC20</fullName>
            </value>
            <value>
                <fullName>AC30</fullName>
            </value>
            <value>
                <fullName>BA10</fullName>
            </value>
            <value>
                <fullName>BA30</fullName>
            </value>
            <value>
                <fullName>BA40</fullName>
            </value>
            <value>
                <fullName>BA60</fullName>
            </value>
            <value>
                <fullName>CD10</fullName>
            </value>
            <value>
                <fullName>CD20</fullName>
            </value>
            <value>
                <fullName>CD30</fullName>
            </value>
            <value>
                <fullName>CD40</fullName>
            </value>
            <value>
                <fullName>CD50</fullName>
            </value>
            <value>
                <fullName>CD60</fullName>
            </value>
            <value>
                <fullName>CD70</fullName>
            </value>
            <value>
                <fullName>CD80</fullName>
            </value>
            <value>
                <fullName>CD90</fullName>
            </value>
            <value>
                <fullName>CU10</fullName>
            </value>
            <value>
                <fullName>CU20</fullName>
            </value>
            <value>
                <fullName>CU30</fullName>
            </value>
            <value>
                <fullName>CU40</fullName>
            </value>
            <value>
                <fullName>CU50</fullName>
            </value>
            <value>
                <fullName>CU80</fullName>
            </value>
            <value>
                <fullName>DD10</fullName>
            </value>
            <value>
                <fullName>DD40</fullName>
            </value>
            <value>
                <fullName>DD60</fullName>
            </value>
            <value>
                <fullName>DD80</fullName>
            </value>
            <value>
                <fullName>DD90</fullName>
            </value>
            <value>
                <fullName>DR10</fullName>
            </value>
            <value>
                <fullName>DR20</fullName>
            </value>
            <value>
                <fullName>DR30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_DOB__c.field-meta.xml
<CustomField>
    <fullName>Drivers_DOB__c</fullName>
    <label>Drivers DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_License_Ban_Details__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License_Ban_Details__c</fullName>
    <label>Drivers License Ban Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Medical_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Medical_Conditions__c</fullName>
    <label>Drivers Medical Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Name__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Name__c</fullName>
    <label>Drivers Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SystemConstants__c/SystemConstants__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SystemConstants</label>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VG_EdisonPS_Ins2_Controller_Test.cls
@isTest(SeeAllData = False)
public class VG_EdisonPS_Ins2_Controller_Test {
    public static testmethod void TesMethod1(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Cancellation');
        VG_EdisonPS_Ins2_Controller eps2=new VG_EdisonPS_Ins2_Controller();
        
    }
    public static testmethod void TesMethod2(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Declaration');
        VG_EdisonPS_Ins2_Controller eps2=new VG_EdisonPS_Ins2_Controller();
        eps2.previous();
        
    }
    public static testmethod void TesMethod3(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Revision of Cover');
        VG_EdisonPS_Ins2_Controller eps2=new VG_EdisonPS_Ins2_Controller();
        
    }
    public static testmethod void TesMethod4(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Extension');
        VG_EdisonPS_Ins2_Controller eps2=new VG_EdisonPS_Ins2_Controller();
        
        eps2.rc=rc;
        eps2.AddRisk();
        eps2.Index='0';
        eps2.RemoveRisk();
        eps2.rc=rc;
        eps2.EditRisk();
        //eps2.previous();
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Endorsement__c pse=VG_TU.createPolicyScheduleEndorsement(ps.id);
        eps2.Cancel();
    }
    public static testmethod void TesMethod5(){
        SystemConstants__c cs = new SystemConstants__c();
        cs.Name='Latest Policy Name';
        cs.DocumentId__c = 'Reset';
        Insert cs;
        Policy_Record_Type__c prt = new Policy_Record_Type__c ();
        prt.Name='Edison Motor';
        prt.Code__c = 'EM';
        Insert prt;
        Policy_LOB__c lob = new Policy_LOB__c();
        lob.Name='Motor';
        lob.Code__c = 'MTR';
        Insert lob;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        VG_EdisonPS_Ins2_Controller eps2=new VG_EdisonPS_Ins2_Controller();
        eps2.previous();
        eps2.rc=rc;
        eps2.AddRisk();
        eps2.Index='0';
        eps2.RemoveRisk();
        eps2.rc=rc;
        eps2.EditRisk();
        eps2.Next();
        eps2.MTAType='Extension';
        eps2.wrcList.clear();
        Risk_Capture__c rc1=new Risk_Capture__c();
        rc1.Name='Test';
        rc1.Drivers_DOB__c=Date.newInstance(1956, 02, 16);
        rc1.Drivers_Claims__c='nil';
        rc1.Drivers_License_Ban_Details__c='Never';
        rc1.Drivers_Name__c='Test Driver';
        rc1.Drivers_Conviction_Points__c='25256';
        rc1.Drivers_Medical_Conditions__c='fit';
        rc1.Drivers_Convictions__c='AC10';
        VG_EdisonPS_Ins2_Controller.WrapperRisk ew=new VG_EdisonPS_Ins2_Controller.WrapperRisk();
        ew.rc=rc1;
        eps2.wrcList.add(ew);
        eps2.Next();
        
        //Cover MTA Type not equal null code on controller
        ApexPages.currentPage().getParameters().put('MTAType', 'Extension');
        ApexPages.currentPage().getParameters().put('OriginalId', ps.id);
        VG_EdisonPS_Ins2_Controller eps3=new VG_EdisonPS_Ins2_Controller();
    }
}