force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <label>Tax 1 - Amount of Taxable Premium</label>
    <summarizedField>Policy_Schedule__c.IPT__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <summarizedField>Policy_Schedule__c.Levies__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <summarizedField>Policy_Schedule__c.VG_Brokerage_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <label>Signed Share (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Capacity)</relationshipLabel>
    <relationshipName>UMR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Capacity_Manager__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Capacity_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_Currency__c.field-meta.xml
<CustomField>
    <fullName>VG_Currency__c</fullName>
    <label>Original Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VG_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_MGA_Commission__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission__c</fullName>
    <label>Commission (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Binder_Broker__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Binder_Broker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Binder Broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (RI Binder Broker)</relationshipLabel>
    <relationshipName>UMR1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Binder_Commission__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Binder_Commission__c</fullName>
    <label>Binder Broker Commission (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Coverage__c</fullName>
    <label>RI Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>7T</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>D2</fullName>
            </value>
            <value>
                <fullName>D3</fullName>
            </value>
            <value>
                <fullName>D4</fullName>
            </value>
            <value>
                <fullName>D5</fullName>
            </value>
            <value>
                <fullName>D6</fullName>
            </value>
            <value>
                <fullName>D7</fullName>
            </value>
            <value>
                <fullName>TR, X3, XC, XR</fullName>
            </value>
            <value>
                <fullName>B4, B5, P3, P5, P7, 6T, 7T, LE</fullName>
            </value>
            <value>
                <fullName>CB, CC</fullName>
            </value>
            <value>
                <fullName>XM, XN</fullName>
            </value>
            <value>
                <fullName>MF</fullName>
            </value>
            <value>
                <fullName>KX, XG, XH</fullName>
            </value>
            <value>
                <fullName>BB, D3, D5, D7, D9, E3, E5, E7, E9, F3, F5, NA, W4, FG, GM</fullName>
            </value>
            <value>
                <fullName>GX, TX, VX, X2, XE, XT</fullName>
            </value>
            <value>
                <fullName>B, CT, GS, JB, G, GC, O, T, TS, V</fullName>
            </value>
            <value>
                <fullName>NX</fullName>
            </value>
            <value>
                <fullName>CY, CZ, KS, KT, N, NB</fullName>
            </value>
            <value>
                <fullName>XY, X1</fullName>
            </value>
            <value>
                <fullName>VL, EG, EH, EZ, EA, EB, EF, H2, H3, L2, L3, AO, AP</fullName>
            </value>
            <value>
                <fullName>SC, SO, SL, V &amp; AP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Inception_Date__c</fullName>
    <label>Inception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Product__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Product__c</fullName>
    <label>RI Product</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Casualty</fullName>
            </value>
            <value>
                <fullName>Cyber</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Financial Lines</fullName>
            </value>
            <value>
                <fullName>Leisure and Sport</fullName>
            </value>
            <value>
                <fullName>Financial Institutions</fullName>
            </value>
            <value>
                <fullName>Professions</fullName>
            </value>
            <value>
                <fullName>Facultative and Treaty Property and Casualty Reinsurance</fullName>
            </value>
            <value>
                <fullName>Space</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Referral_Limit_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Referral_Limit_Premium__c</fullName>
    <label>Referral Premium Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Referral_Limit_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Referral_Limit_Sum_Insured__c</fullName>
    <label>Referral Sum Insured Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Share__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Share__c</fullName>
    <label>Cession Share (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Share_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Share_Type__c</fullName>
    <label>Cession Share Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proportional</fullName>
            </value>
            <value>
                <fullName>Non-proportional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Sum_Insured_Limit__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Sum_Insured_Limit__c</fullName>
    <label>Sum Insured Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Type__c</fullName>
    <label>Cession Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gross</fullName>
            </value>
            <value>
                <fullName>Net</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/globalValueSets/VG_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>DKK</fullName>
    </customValue>
    <customValue>
        <fullName>ISK</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>HKD</fullName>
    </customValue>
    <customValue>
        <fullName>NZD</fullName>
    </customValue>
    <customValue>
        <fullName>NOK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>ZAR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>SEK</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PolicyScheduleTriggerFunctionTest.cls
/*

*Created By : Siddik

*Created On : 24-11-2017

*JIRA.No    : VG-11

*/

@IsTest(SeeAllData=False)
Public Class PolicyScheduleTriggerFunctionTest{    
    Public Static TestMethod Void testMethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Vendor');
        
        List<VG_UMR__c> uList=new List<VG_UMR__c>();
        VG_UMR__c u=new VG_UMR__c();
        u.VG_Account__c=acc.id;
        u.Name='Test';
        u.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Edison Motor').getRecordTypeId();
        u.VG_RI_Product__c='Cyber';
        u.VG_RI_Coverage__c='M6 - Third Party Only';
        u.VG_RI_Type__c='Net';
        u.VG_RI_Share_Type__c='Proportional';
        u.VG_RI_Inception_Date__c=Date.newInstance(2017, 11, 18);
        u.VG_RI_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        u.VG_RI_Binder_Broker__c=acc.Id;
        u.VG_Currency__c='CAD';
        u.VG_RI_Share__c=52;
        u.VG_MGA_Commission__c=45;
        u.VG_RI_Binder_Commission__c=28;
        u.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u.VG_RI_Referral_Limit_Premium__c=1528;
        u.VG_RI_Sum_Insured_Limit__c=1258888;
        u.VG_Capacity_Manager__c=UserInfo.getUserId();
        uList.add(u);
        VG_UMR__c u2=new VG_UMR__c();
        u2.VG_Account__c=acc.id;
        u2.Name='Test';
        u2.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Edison Motor').getRecordTypeId();
        u2.VG_RI_Product__c='Cyber';
        u2.VG_RI_Coverage__c='M6 - Third Party Only';
        u2.VG_RI_Type__c='Net';
        u2.VG_RI_Share_Type__c='Proportional';
        u2.VG_RI_Inception_Date__c=Date.newInstance(2017, 11, 18);
        u2.VG_RI_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        u2.VG_RI_Binder_Broker__c=acc.Id;
        u2.VG_Currency__c='CAD';
        u2.VG_RI_Share__c=52;
        u2.VG_MGA_Commission__c=45;
        u2.VG_RI_Binder_Commission__c=28;
        u2.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u2.VG_RI_Referral_Limit_Premium__c=1528;
        u2.VG_RI_Sum_Insured_Limit__c=1258888;
        u2.VG_Capacity_Manager__c=UserInfo.getUserId();
        uList.add(u2);
        Insert uList;
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        PolicyScheduleTriggerFunction.allowInsertRI=True;
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        ps.VG_Status__c='Booked';
        ps.Gross_Written_Premium__c=50000;
        ps.IPT__c=50000;
        ps.Levies__c=5000;
        ps.VG_Brokerage_Amount__c=50000;
        
        update ps;
    }
    Public Static TestMethod Void testMethod2(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Vendor');
        
        List<VG_UMR__c> uList=new List<VG_UMR__c>();
        VG_UMR__c u=new VG_UMR__c();
        u.VG_Account__c=acc.id;
        u.Name='Test';
        u.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Horizon').getRecordTypeId();
        u.VG_RI_Product__c='Cyber';
        u.VG_RI_Coverage__c='M6 - Third Party Only';
        u.VG_RI_Type__c='Net';
        u.VG_RI_Share_Type__c='Proportional';
        u.VG_RI_Inception_Date__c=Date.newInstance(2017, 11, 18);
        u.VG_RI_Expiry_Date__c=Date.newInstance(2018, 12, 18);
        u.VG_RI_Binder_Broker__c=acc.Id;
        u.VG_Currency__c='CAD';
        u.VG_RI_Share__c=52;
        u.VG_MGA_Commission__c=45;
        u.VG_RI_Binder_Commission__c=28;
        u.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u.VG_RI_Referral_Limit_Premium__c=1528;
        u.VG_RI_Sum_Insured_Limit__c=1258888;
        u.VG_Capacity_Manager__c=UserInfo.getUserId();
        u.VG_Capacity_Paper__c='Fidelis';
        uList.add(u);
        VG_UMR__c u2=new VG_UMR__c();
        u2.VG_Account__c=acc.id;
        u2.Name='Test';
        u2.RecordTypeId=Schema.SObjectType.VG_UMR__c.getRecordTypeInfosByName().get('Horizon').getRecordTypeId();
        u2.VG_RI_Product__c='Cyber';
        u2.VG_RI_Coverage__c='M6 - Third Party Only';
        u2.VG_RI_Type__c='Net';
        u2.VG_RI_Share_Type__c='Proportional';
        u2.VG_RI_Inception_Date__c=Date.newInstance(2015, 11, 18);
        u2.VG_RI_Expiry_Date__c=Date.newInstance(2020, 12, 18);
        u2.VG_RI_Binder_Broker__c=acc.Id;
        u2.VG_Currency__c='CAD';
        u2.VG_Capacity_Paper__c='Greenlight Re';
        u2.VG_RI_Share__c=52;
        u2.VG_MGA_Commission__c=45;
        u2.VG_RI_Binder_Commission__c=28;
        u2.VG_RI_Referral_Limit_Sum_Insured__c=125685;
        u2.VG_RI_Referral_Limit_Premium__c=1528;
        u2.VG_RI_Sum_Insured_Limit__c=1258888;
        u2.VG_Capacity_Manager__c=UserInfo.getUserId();
        uList.add(u2);
        Insert uList;
        Policy__c pol=VG_TU.createPolicy('Horizon', acc.id);
        PolicyScheduleTriggerFunction.allowInsertRI=True;
        Policy_Schedule__c ps=new Policy_Schedule__c();
        ps.RecordTypeId=Schema.SObjectType.Policy_Schedule__c.getRecordTypeInfosByName().get('Horizon').getRecordTypeId();
        ps.Name='Test';
        ps.Policy__c=pol.id;  
        ps.Gross_Written_Premium__c=500;
        ps.VG_Capacity_Paper__c='Greenlight Re';
        ps.Transaction_GWP__c=0;
        ps.Share__c=20;
        Insert ps;
        VG_Payment_Frequency__c pf=VG_TU.createPaymentFrequency(ps.id);
        ps.VG_Status__c='Booked';
        ps.Gross_Written_Premium__c=50000;
        ps.IPT__c=50000;
        ps.Levies__c=5000;
        ps.VG_Brokerage_Amount__c=50000; 
        ps.VG_Capacity_Paper__c='Fidelis';        
        ps.Bordereaux_Override__c = 'No';
        update ps;
    }
}