force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Governance_Compliance__c.field-meta.xml
<CustomField>
    <fullName>VG_Governance_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Governance &amp; Compliance</label>
    <referenceTo>VG_Governance_Compliance__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/VG_Governance_Compliance__c.object-meta.xml
<CustomObject>
    <label>Governance &amp; Compliance</label>
    <nameField>
        <label>Governance &amp; Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance &amp; Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Contract_Certainty__c.field-meta.xml
<CustomField>
    <fullName>VG_Contract_Certainty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Certainty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Peer_Review_1_Complete__c.field-meta.xml
<CustomField>
    <fullName>VG_Peer_Review_1_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Peer Review 1 Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Peer_Review_2_Complete__c.field-meta.xml
<CustomField>
    <fullName>VG_Peer_Review_2_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Peer Review 2 Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VG_EditGovernanceComplianceController_T.cls
@IsTest(SeeAllData=False)
public class VG_EditGovernanceComplianceController_T {
    public static testmethod void testmethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        VG_Edit_Governance_Compliance_Controller egcc=new VG_Edit_Governance_Compliance_Controller();
        egcc.cancel();
        egcc.gc.VG_Peer_Review_1_Complete__c=true;
        egcc.gc.VG_Peer_Review_2_Complete__c=true;
        egcc.gc.VG_Contract_Certainty__c=true;
        egcc.createGC();
        VG_Governance_Compliance__c gcc=new VG_Governance_Compliance__c();
        gcc.Name='Test';
        Insert gcc;
        Policy__c pol1=pol.Clone(false,true,false,false);
        pol1.VG_Governance_Compliance__c=gcc.id;
        Insert pol1;
        ApexPages.currentPage().getParameters().put('Id', pol1.id);
        VG_Edit_Governance_Compliance_Controller egcc1=new VG_Edit_Governance_Compliance_Controller();
        egcc1.createGC();
        //Below lines cover VG_Governance_Compliance_Controller class
        ApexPages.StandardController stdController = new ApexPages.StandardController(pol1);
        VG_Governance_Compliance_Controller gandcc=new VG_Governance_Compliance_Controller(stdController);
    }
}