force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Actual_GWP__c.field-meta.xml
<CustomField>
    <fullName>Actual_GWP__c</fullName>
    <formula>Gross_Written_Premium__c - VG_Brokerage_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3 AND 4) OR 5</booleanFilter>
        <errorMessage>Please select an approved broker or sub-broker</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sub-Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.VG_TOBA_Uploaded__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Regulatory_Check__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy_Status__c</field>
            <operation>equals</operation>
            <value>NTU/Decline</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Broker)</relationshipLabel>
    <relationshipName>Policies_Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Insured__c.field-meta.xml
<CustomField>
    <fullName>Insured__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Insured)</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <label>Tax 1 - Amount of Taxable Premium</label>
    <summarizedField>Policy_Schedule__c.IPT__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Transaction_GWP__c.field-meta.xml
<CustomField>
    <fullName>Transaction_GWP__c</fullName>
    <label>Transaction Premium</label>
    <summarizedField>Policy_Schedule__c.Transaction_GWP__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Underwriter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <errorMessage>Please select the Underwriter is only Partner user</errorMessage>
        <filterItems>
            <field>User.VG_Underwriter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <formula>IF(Gross_Written_Premium__c = 0,0,( VG_Brokerage_Amount__c / Gross_Written_Premium__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Current_Insurer__c.field-meta.xml
<CustomField>
    <fullName>VG_Current_Insurer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Insurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Current Insurer)</relationshipLabel>
    <relationshipName>PoliciesCurrentInsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Inception_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Inception_Date__c</fullName>
    <label>Risk Inception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission_Amount__c</fullName>
    <label>MGA Commission (Amount)</label>
    <summarizedField>Policy_Schedule__c.VG_MGA_Commission_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Sub_Broker__c.field-meta.xml
<CustomField>
    <fullName>VG_Sub_Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Broker</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sub-Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Sub-Broker)</relationshipLabel>
    <relationshipName>Policies_Sub_Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Actual_GWP__c.field-meta.xml
<CustomField>
    <fullName>Actual_GWP__c</fullName>
    <label>Actual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Base_Creation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Base_Creation_Start_Date__c</fullName>
    <label>Base Creation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT_Percent__c.field-meta.xml
<CustomField>
    <fullName>IPT_Percent__c</fullName>
    <label>IPT (%)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Transaction_GWP__c.field-meta.xml
<CustomField>
    <fullName>Transaction_GWP__c</fullName>
    <label>Transaction Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Percent__c</fullName>
    <label>Brokerage (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Is_MTA__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_MTA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission_Amount__c</fullName>
    <label>MGA Commission (Amount)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Sub_broker__c.field-meta.xml
<CustomField>
    <fullName>VG_Sub_broker__c</fullName>
    <label>Sub broker</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/classes/VG_Edison_Quotation_PS_Extension.cls
public class VG_Edison_Quotation_PS_Extension {
    Public String MF {get; set;}
    Public String ImageURL {get; set;}
    public String LogoURL{get;set;}
    public String PP1{get;set;}
    public String FooterURL{get;set;}
    Public Policy_Schedule__c ps{get;set;}
    public String PrintView{get;set;}
    public String PSId{get;set;}
    public Boolean comp{get;set;}
    public Decimal NoV{get;set;}
    public Boolean tpft{get;set;}
    public Boolean tpo{get;set;}
    public Boolean fto{get;set;}
    public Boolean mixed{get;set;}
    public String today{get;set;}
    Public List<VG_Policy_Schedule_Endorsement__c> pseList{get;set;}
    Public List<VG_Policy_Schedule_Asset__c> psaList{get;set;}
    public Date IncepDate{get;set;}
    public String IncepDateFormat{get;set;}
    public Date MTAStartDate{get;set;}
    public String MTAStartDateFormat{get;set;}
    public String underwriter{get;set;} 
    public String Sign_Url{get;set;}
    Public List<VG_Policy_Schedule_Endorsement__c> pseList1{get;set;}
    Public List<VG_Policy_Schedule_Endorsement__c> pseList2{get;set;}
    Public List<VG_Policy_Schedule_Endorsement__c> pseList3{get;set;}
    
    public VG_Edison_Quotation_PS_Extension() {
        PSId=apexpages.currentpage().getparameters().get('Id');
        ps=[Select Id,Name,Product__c,VG_Brokerage_Percent__c,Policy__r.Gross_Written_Premium__c,Gross_Written_Premium__c,Policy__r.Underwriter__r.Name,Policy__r.Insured__r.ShippingPostalCode,Policy__r.VG_Brokerage_Percent__c,Policy__r.Broker_Name__r.Name,Policy__r.VG_Sub_Broker__r.Name,Policy__r.Broker_Name__r.VG_Intermediary_Number__c,Policy__r.Actual_GWP__c,Base_Creation_Start_Date__c,Policy__r.Insured__r.Name,Policy__r.VG_Current_Insurer__r.Name,Policy__r.Name,VG_Is_MTA__c,Actual_GWP__c,IPT_Percent__c,IPT__c,VG_MGA_Commission_Amount__c, Transaction_GWP__c, Policy__r.Insured__r.AccountNumber,Policy__r.Insured__r.Bank_Sort_Code__c,VG_MTA_Start_Date__c,Policy__r.VG_Inception_Date__c,Levies__c,VG_Fee_Income__c,Policy__r.Insured__r.BillingPostalCode,Policy__r.Deductible_or_Excess_Amount__c,Policy__r.VG_Brokerage_Amount__c from Policy_Schedule__c Where Id=:PSId];
        today=System.Today().format();
        IncepDate = ps.Policy__r.VG_Inception_Date__c;   
        if(IncepDate != null)
            IncepDateFormat = IncepDate.format();
        MTAStartDate=ps.VG_MTA_Start_Date__c;
        if(MTAStartDate != null)
            MTAStartDateFormat=MTAStartDate.format();
        string strOrgId = UserInfo.getOrganizationId();
        //ImageURL = '/servlet/servlet.FileDownload?file=';
        List< document > documentList = [select Id, name from document where Name='Volante_Global_logo'];
        List< document > MFList = [select Id, name from document where Name='Motor Felt'];
        ImageURL = ImageURL + documentList[0].Id;
        ImageURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Edison/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;              
        //ImageURL = 'https://volante--dev--c.cs85.content.force.com/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;                      
        documentList.clear();
        documentList = [select Id, name from document where Name='VG_Edison_Quote'];               
        LogoURL=LogoURL+documentList[0].Id;
        LogoURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Edison/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;                   
        documentList.clear();
        documentList = [select Id, name from document where Name='VG_Edison_Quote2'];               
        FooterURL=FooterURL+documentList[0].Id;
        FooterURL = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Edison/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;                   
        documentList.clear();
        if(ps.Policy__r.Underwriter__r.Name!=null){
            underwriter=ps.Policy__r.Underwriter__r.Name;
            documentList = [select Id, name from document where Name=:underwriter];    
            Sign_Url = 'https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Edison/servlet/servlet.ImageServer?id='+documentList[0].Id+'&oid=' + strOrgId;                           
        }
        
        documentList.clear();
        MF='https://'+ApexPages.currentPage().getHeaders().get('Host')+ '/Edison/servlet/servlet.ImageServer?id='+MFList[0].Id+'&oid=' + strOrgId;        
        System.debug('currentPage::'+ApexPages.currentPage()+'::'+ApexPages.currentPage().getHeaders()+'::'+ApexPages.currentPage().getHeaders().get('Host'));  //Output of this debug :: ::volante--dev--c.cs85.visual.force.com       
        PrintView='<!--[if gte mso 9]>' +
        '<xml>' +
        '<w:WordDocument>' +
        '<w:View>Print</w:View>' +
        '<w:Zoom>100</w:Zoom>' +
        '<w:DoNotOptimizeForBrowser/>' +
        '</w:WordDocument>' +
        '</xml>' +
        '<![endif]>';  
        System.debug('PP1::'+PP1);   
        pseList=new List<VG_Policy_Schedule_Endorsement__c>([select id,Name,VG_Endorsement_Number__c,VG_Title__c from VG_Policy_Schedule_Endorsement__c where VG_Policy_Schedule__c =:PSID ORDER BY VG_Endorsement_Number__c ASC]);
        System.debug('pseList::'+pseList); 
        pseList1 =new List<VG_Policy_Schedule_Endorsement__c>();
        pseList2 =new List<VG_Policy_Schedule_Endorsement__c>();
        pseList3 =new List<VG_Policy_Schedule_Endorsement__c>();
        integer i=0;
        integer j;      
            if(pseList.size()>0 ){
                while(i<8 && i<pseList.size()){               
                    pseList1.add(pseList[i++]);
                    System.debug('pseList1::'+pseList1);               
                }
                j=8;
                while(j<48 && j<pseList.size()){               
                    pseList2.add(pseList[j++]);
                    System.debug('pseList2::'+pseList2);               
                }
                for(j=48;j<pseList.size();j++){
                    pseList3.add(pseList[j]);
                    System.debug('pseList3::'+pseList3);
                }
            }
        
        psaList=new List<VG_Policy_Schedule_Asset__c>([select id,Name,VG_Coverage__c,VG_Number_of_Vehicles__c from VG_Policy_Schedule_Asset__c where VG_Policy_Schedule__c =:PSID]);
        System.debug('psaList::'+psaList);
        List<String> cov=new List<String>();
        NoV=0;
        for(VG_Policy_Schedule_Asset__c psa:psaList){
            if(psa.VG_Coverage__c !=null){
                String[] c=psa.VG_Coverage__c.split(';');
                for(String s: c){
                    cov.add(s);
                }
            }
            if(psa.VG_Number_of_Vehicles__c !=null){
                NoV=NoV+psa.VG_Number_of_Vehicles__c;
            }
                
        }    
        if(!cov.IsEmpty()){
            Set<String> coverage=new Set<String>();
            for(String s:cov){
                if(!coverage.contains(s))
                    coverage.add(s);
            }
            System.debug('coverage::'+coverage);
            if(coverage.contains('M3 - Fully Comprehensive') && !coverage.contains('M6 - Third Party Fire & Theft') && !coverage.contains('M6 - Third Party Only') && !coverage.contains('M6 - Fire & Theft Only')){
               comp=True; 
               fto=false;
               tpo=false;
               tpft=false;
               mixed=false;
            }else if(!coverage.contains('M3 - Fully Comprehensive') && coverage.contains('M6 - Third Party Fire & Theft') && !coverage.contains('M6 - Third Party Only') && !coverage.contains('M6 - Fire & Theft Only')){
               tpft=True; 
               comp=false; 
               fto=false;
               tpo=false;
               mixed=false;
            }else if(!coverage.contains('M3 - Fully Comprehensive') && !coverage.contains('M6 - Third Party Fire & Theft') && coverage.contains('M6 - Third Party Only') && !coverage.contains('M6 - Fire & Theft Only')){
               tpo=True; 
               comp=false; 
               fto=false;
               tpft=false;
               mixed=false;
            }else if(!coverage.contains('M3 - Fully Comprehensive') && !coverage.contains('M6 - Third Party Fire & Theft') && !coverage.contains('M6 - Third Party Only') && coverage.contains('M6 - Fire & Theft Only')){
               fto=True; 
               comp=false; 
               tpo=false;
               tpft=false;
               mixed=false;
            }else{
               mixed=true;
               comp=false; 
               fto=false;
               tpo=false;
               tpft=false;
            }
            System.debug('Status::'+mixed+comp+fto+tpo+tpft);
        }else{
            mixed=false;
            comp=false; 
            fto=false;
            tpo=false;
            tpft=false;
        }
    }
}