force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>NTU/Decline</fullName>
            </value>
            <value>
                <fullName>Bound</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Additional Information Required</fullName>
                <isActive>false</isActive>
                <label>Additional Information Required</label>
            </value>
            <value>
                <fullName>Awaiting Submission</fullName>
                <isActive>false</isActive>
                <label>Awaiting Submission</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Final Terms Quoted After Negotiations</fullName>
                <isActive>false</isActive>
                <label>Final Terms Quoted After Negotiations</label>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
                <isActive>false</isActive>
                <label>NTU - Capacity</label>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
                <isActive>false</isActive>
                <label>NTU - Other</label>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
                <isActive>false</isActive>
                <label>NTU - Price</label>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
                <isActive>false</isActive>
                <label>NTU - Service</label>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
                <isActive>false</isActive>
                <label>NTU - Terms</label>
            </value>
            <value>
                <fullName>Referral Approval</fullName>
                <isActive>false</isActive>
                <label>Referral Approval</label>
            </value>
            <value>
                <fullName>Submission Received</fullName>
                <isActive>false</isActive>
                <label>Submission Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>NTU_Or_Declined__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Submission Received</fullName>
            </value>
            <value>
                <fullName>Additional Info Required</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>NTU - Price</fullName>
            </value>
            <value>
                <fullName>NTU - Terms</fullName>
            </value>
            <value>
                <fullName>NTU - Capacity</fullName>
            </value>
            <value>
                <fullName>NTU - Service</fullName>
            </value>
            <value>
                <fullName>NTU - Other</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Approval Rejected</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Decline - Price</fullName>
            </value>
            <value>
                <fullName>Decline - Risk Profile</fullName>
            </value>
            <value>
                <fullName>Decline - Quality of Risk</fullName>
            </value>
            <value>
                <fullName>Decline - Location</fullName>
            </value>
            <value>
                <fullName>Decline - Attachment</fullName>
            </value>
            <value>
                <fullName>Decline - Terms / Wording</fullName>
            </value>
            <value>
                <fullName>Decline - Licensing Restrictions</fullName>
            </value>
            <value>
                <fullName>Decline - Territorial Scope</fullName>
            </value>
            <value>
                <fullName>Decline - Line of Business</fullName>
            </value>
            <value>
                <fullName>Decline - Type of Business e.g Direct vs QS</fullName>
            </value>
            <value>
                <fullName>Decline - Binding Authority Restrictions</fullName>
            </value>
            <value>
                <fullName>Decline - Referall Declined</fullName>
            </value>
            <value>
                <fullName>Decline - Conflict with Volante Capacity Provider</fullName>
            </value>
            <value>
                <fullName>Decline - Aggregation with carrier</fullName>
            </value>
            <value>
                <fullName>Decline - Assured Financials</fullName>
            </value>
            <value>
                <fullName>Decline - Other</fullName>
            </value>
            <value>
                <fullName>Decline - Duplicate</fullName>
            </value>
            <value>
                <fullName>NTU - Renewed with Existing Panel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/classes/VG_LS_PS_Button_Controller_Test.cls
@IsTest(seeAllData =False)
public class VG_LS_PS_Button_Controller_Test {
     public static testMethod void TestMethod1() {
         VG_TU.policyCustomSetting();
         Account acc=VG_TU.createAccount('Customer');     
         Policy__c pol=VG_TU.createPolicy('Affinity', acc.id);
         pol.Policy_Status__c='NTU/Decline';
         pol.VG_Sub_Status__c='Approved';
         update pol;
         System.debug('Policy Name::'+pol.Name);
         Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
         ps.Policy__c=pol.id;
         Insert ps; 
         VG_LS_PS_Button_Controller.getPolicySchedule(ps.Id);
         VG_LS_PS_Button_Controller.createELCertificate(ps.Id);
         VG_LS_PS_Button_Controller.createGPAQuoteAttachment(ps.Id);
         VG_LS_PS_Button_Controller.createLSStatementAttachment(ps.Id);
         VG_LS_PS_Button_Controller.createPSGPAAttachment(ps.Id);
     }
}