force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Broker_Contact__c.field-meta.xml
<CustomField>
    <fullName>Broker_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Search Field that Searches the contacts for the given broker.</description>
    <label>Broker Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Broker_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3 AND 4) OR 5</booleanFilter>
        <errorMessage>Please select an approved broker or sub-broker</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sub-Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.VG_TOBA_Uploaded__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Regulatory_Check__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy_Status__c</field>
            <operation>equals</operation>
            <value>NTU/Decline</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Broker)</relationshipLabel>
    <relationshipName>Policies_Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Affinity.recordType-meta.xml
<RecordType>
    <fullName>Affinity</fullName>
    <active>true</active>
    <label>Affinity</label>
</RecordType>

force-app/main/default/classes/ChangeBrokerController_Test.cls
@IsTest(SeeAllData=False)
public class ChangeBrokerController_Test {
	public Static Testmethod Void method1(){
        VG_TU.policyCustomSetting();
        Account acc2=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Affinity',acc2.id);
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        ChangeBrokerController cbc = new ChangeBrokerController();
        cbc.save();
		cbc.cancel();        
    }
    public Static Testmethod Void method2(){
        VG_TU.policyCustomSetting();
        Account acc2=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Affinity',acc2.id);
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        Account ba=VG_TU.createChangeBrokerAccount('Broker');  
        Contact c = VG_TU.createContact(ba);
        System.debug('ba::'+ba);
        pol.Broker_Name__c = ba.id;
        pol.Broker_Contact__c= c.Id;
        update pol;
        ChangeBrokerController cbc = new ChangeBrokerController();
        cbc.policy=pol;
        cbc.PolicyId = pol.Id;
        cbc.save();
    	
    } 
}