force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <label>Tax 1 - Amount of Taxable Premium</label>
    <summarizedField>Policy_Schedule__c.IPT__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <summarizedField>Policy_Schedule__c.VG_Brokerage_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT__c.field-meta.xml
<CustomField>
    <fullName>IPT__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_Payment_Frequency__c/VG_Payment_Frequency__c.object-meta.xml
<CustomObject>
    <label>Payment Frequency</label>
    <nameField>
        <label>Payment Frequency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Frequencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Payment_Frequency__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Payment Frequencies</relationshipLabel>
    <relationshipName>Payment_Frequencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/VG_Taxes__c.object-meta.xml
<CustomObject>
    <label>Taxes</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Administered_By__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Administered_By__c</fullName>
    <label>Tax Administered By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Insurer</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Percent__c</fullName>
    <label>Tax (%)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Taxable_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Taxable_Amount__c</fullName>
    <label>Taxable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VG_BridegeInvoiceController_Test.cls
@IsTest(seeAllData =False)
public class VG_BridegeInvoiceController_Test {
    public static testMethod void TestMethod1() { 
        VG_TU.policyCustomSetting();       
        Document d1=new Document();
        d1.Name='Bridge Logo';
        d1.Body=blob.valueOf('Hai');
        d1.FolderId='0050O0000078Mug';
        insert d1;
        Document d2=new Document();
        d2.Name='Motor Felt';
        d2.Body=blob.valueOf('Hai');
        d2.FolderId='0050O0000078Mug';
        insert d2;
        Document d3=new Document();
        d3.Name='Volante_Global_logo';
        d3.Body=blob.valueOf('Hai');
        d3.FolderId='0050O0000078Mug';
        insert d3;
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Bridge', acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Product__c='Property';
        ps.Policy__c=pol.id;
        ps.Gross_Written_Premium__c=50000;
        ps.VG_Brokerage_Amount__c=4500;
        ps.IPT__c=4500;
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 11, 12);
        Insert ps;
        VG_Payment_Frequency__c pf= VG_TU.createPaymentFrequency(ps.Id);
        VG_Taxes__c tx=new VG_Taxes__c();
        tx.Name='test';
        tx.VG_Policy_Schedule__c=ps.id;
        tx.VG_Taxable_Amount__c=4500;
        tx.VG_Tax_Administered_By__c='Insurer';
        tx.VG_Tax_Percent__c=45;
        Insert tx;
        VG_Taxes__c tx1=new VG_Taxes__c();
        tx1.Name='test';
        tx1.VG_Policy_Schedule__c=ps.id;
        tx1.VG_Taxable_Amount__c=4500;
        tx1.VG_Tax_Amount__c=4800;
        tx1.VG_Tax_Administered_By__c='Broker';
        tx1.VG_Tax_Percent__c=45;
        Insert tx1;
        ApexPages.currentPage().getParameters().put('Id', ps.id);
        ApexPages.currentPage().getParameters().put('PFId', pf.id);
        VG_BridegeInvoiceController BD=new VG_BridegeInvoiceController();
    }   
}