force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Governance_Compliance__c.field-meta.xml
<CustomField>
    <fullName>VG_Governance_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Governance &amp; Compliance</label>
    <referenceTo>VG_Governance_Compliance__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/VG_Governance_Compliance__c.object-meta.xml
<CustomObject>
    <label>Governance &amp; Compliance</label>
    <nameField>
        <label>Governance &amp; Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance &amp; Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/Referred_to__c.field-meta.xml
<CustomField>
    <fullName>Referred_to__c</fullName>
    <label>Referred to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Contact_Certainty_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_Contact_Certainty_Date__c</fullName>
    <label>Contact Certainty Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Contract_Certainty__c.field-meta.xml
<CustomField>
    <fullName>VG_Contract_Certainty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contract Certainty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_10__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_10__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are currencies clearly identified?</description>
    <inlineHelpText>Are currencies clearly identified?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_11__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_11__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Full Terms and Conditions?</description>
    <inlineHelpText>Full Terms and Conditions?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_1__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_1__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are parties clearly identified?</description>
    <inlineHelpText>Are parties clearly identified?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_2__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is wording attached or clearly referenced?</description>
    <inlineHelpText>Is wording attached or clearly referenced?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_3__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are all conditions clearly expressed?</description>
    <inlineHelpText>Are all conditions clearly expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_4__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_4__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Regulatory requirements addressed?</description>
    <inlineHelpText>Regulatory requirements addressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_5__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_5__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the period of cover clearly expressed?</description>
    <inlineHelpText>Is the period of cover clearly expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_6__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_6__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are the limits clearly expressed?</description>
    <inlineHelpText>Are the limits clearly expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_7__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_7__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the premium or rate clearly expressed?</description>
    <inlineHelpText>Is the premium or rate clearly expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_8__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_8__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are any applicable taxes expressed?</description>
    <inlineHelpText>Are any applicable taxes expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Governance_Compliance__c/fields/VG_Question_9__c.field-meta.xml
<CustomField>
    <fullName>VG_Question_9__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are any payment terms clearly expressed?</description>
    <inlineHelpText>Are any payment terms clearly expressed?</inlineHelpText>
    <label>Contract Certainty Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VG_Governance_Compliance_Controller.cls
Public Class VG_Governance_Compliance_Controller{
    
    public Id policyId {get; set;}
    
    public VG_Governance_Compliance__c gc{get;set;}    
    public Policy__c policy{get;set;}
    public VG_Governance_Compliance_Controller(ApexPages.StandardController stdController){
        policy= (Policy__c )stdController.getRecord();
        gc=[select id,Name,VG_Question_1__c,VG_Question_6__c,VG_Question_2__c,VG_Question_11__c,Referred_to__c,VG_Question_7__c,VG_Question_3__c,VG_Question_8__c,VG_Question_4__c,VG_Question_9__c,VG_Question_5__c,VG_Question_10__c,VG_Contact_Certainty_Date__c,VG_Contract_Certainty__c from VG_Governance_Compliance__c where id=:policy.VG_Governance_Compliance__c ];
    }
}