force-app/main/default/objects/Endorsement_Library__c/Endorsement_Library__c.object-meta.xml
<CustomObject>
    <label>Endorsement Library</label>
    <nameField>
        <label>Endorsement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endorsement Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endorsement_Library__c/fields/Endorsement_Title__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Title__c</fullName>
    <label>Endorsement Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endorsement_Library__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Endorsement_Library__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Endorsement_Details__c.field-meta.xml
<CustomField>
    <fullName>VG_Endorsement_Details__c</fullName>
    <label>Endorsement Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Endorsement_Library_Id__c.field-meta.xml
<CustomField>
    <fullName>VG_Endorsement_Library_Id__c</fullName>
    <label>Endorsement Library Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Schedule_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Title__c.field-meta.xml
<CustomField>
    <fullName>VG_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VG_GentiumStep4_Controller_Test.cls
@isTest(SeeAllData = False)
public class VG_GentiumStep4_Controller_Test {
	public static testmethod void TesMethod1(){ 
        VG_TU.policyCustomSetting();        
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Endorsement_Library__c EL=new Endorsement_Library__c();
        EL.Name='Test EL';
        EL.Text__c='Text';
        EL.Endorsement_Title__c='Title';
        Insert EL;
        VG_Policy_Schedule_Endorsement__c PSE=new VG_Policy_Schedule_Endorsement__c();
        PSE.VG_Endorsement_Details__c=EL.Text__c;
        PSE.VG_Endorsement_Library_Id__c=EL.Id;
        PSE.VG_Policy_Schedule__c=ps.Id;
        PSE.VG_Title__c=EL.Endorsement_Title__c;
        PSE.VG_Premium__c=0;
        Insert PSE;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Cancellation');
        VG_GentiumStep4_Controller gen=new VG_GentiumStep4_Controller();
        gen.Nexta();
        gen.Previousa();
        VG_Policy_Schedule_Endorsement__c PSE1=new VG_Policy_Schedule_Endorsement__c();
        PSE1.VG_Endorsement_Details__c=EL.Text__c;
        PSE1.VG_Endorsement_Library_Id__c=EL.Id;
        PSE1.VG_Policy_Schedule__c=ps.Id;
        PSE1.VG_Title__c=EL.Endorsement_Title__c;
        PSE1.VG_Premium__c=0;
        Insert PSE1;
        gen.existingEndorsements.add(PSE1);
        gen.MTAType=null;
        gen.Previousa();        
    }
    public static testmethod void TesMethod2(){
        VG_TU.policyCustomSetting();        
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Endorsement_Library__c EL=new Endorsement_Library__c();
        EL.Name='Test EL';
        EL.Text__c='Text';
        EL.Endorsement_Title__c='Title';
        Insert EL;
        VG_Policy_Schedule_Endorsement__c PSE=new VG_Policy_Schedule_Endorsement__c();
        PSE.VG_Endorsement_Details__c=EL.Text__c;
        PSE.VG_Endorsement_Library_Id__c=EL.Id;
        PSE.VG_Policy_Schedule__c=ps.Id;
        PSE.VG_Title__c=EL.Endorsement_Title__c;
        PSE.VG_Premium__c=0;
        Insert PSE;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Extension');
        VG_GentiumStep4_Controller gen=new VG_GentiumStep4_Controller();
        gen.Nexta();        
    }
    public static testmethod void TesMethod3(){ 
        VG_TU.policyCustomSetting();        
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Endorsement_Library__c EL=new Endorsement_Library__c();
        EL.Name='Test EL';
        El.RecordTypeId=Schema.SObjectType.Endorsement_Library__c.getRecordTypeInfosByName().get('Gentium').getRecordTypeId();        
        EL.Text__c='Text';
        EL.Endorsement_Title__c='Title';
        Insert EL;
        VG_Policy_Schedule_Endorsement__c PSE=new VG_Policy_Schedule_Endorsement__c();
        PSE.VG_Endorsement_Details__c=EL.Text__c;
        PSE.VG_Endorsement_Library_Id__c=EL.Id;
        PSE.VG_Policy_Schedule__c=ps.Id;
        PSE.VG_Title__c=EL.Endorsement_Title__c;
        PSE.VG_Premium__c=0;
        Insert PSE;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Revision of Cover');
        VG_GentiumStep4_Controller gen=new VG_GentiumStep4_Controller();
        gen.Nexta();
        gen.Previousa();
        VG_Policy_Schedule_Endorsement__c PSE1=new VG_Policy_Schedule_Endorsement__c();
        PSE1.VG_Endorsement_Details__c=EL.Text__c;
        PSE1.VG_Endorsement_Library_Id__c=EL.Id;
        PSE1.VG_Policy_Schedule__c=ps.Id;
        PSE1.VG_Title__c=EL.Endorsement_Title__c;
        PSE1.VG_Premium__c=0;
        Insert PSE1;
        gen.existingEndorsements.add(PSE1);
        gen.MTAType=null;
        gen.Previousa(); 
        gen.Cancel();
    }
    public static testmethod void TesMethod4(){
        VG_TU.policyCustomSetting();        
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Endorsement_Library__c EL=new Endorsement_Library__c();
        EL.Name='Test EL';
        El.RecordTypeId=Schema.SObjectType.Endorsement_Library__c.getRecordTypeInfosByName().get('Gentium').getRecordTypeId();                
        EL.Text__c='Text';
        EL.Endorsement_Title__c='Title';
        Insert EL;
        VG_Policy_Schedule_Endorsement__c PSE=new VG_Policy_Schedule_Endorsement__c();
        PSE.VG_Endorsement_Details__c=EL.Text__c;
        PSE.VG_Endorsement_Library_Id__c=EL.Id;
        PSE.VG_Policy_Schedule__c=ps.Id;
        PSE.VG_Title__c=EL.Endorsement_Title__c;
        PSE.VG_Premium__c=0;
        Insert PSE;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Declaration');
        VG_GentiumStep4_Controller gen=new VG_GentiumStep4_Controller();
        gen.Nexta();   
        gen.LibraryWrapperList[0].IsSelected=True;
        
    }
    public static testmethod void TesMethod5(){
        VG_TU.policyCustomSetting();        
        Account acc=VG_TU.createAccount('Customer');        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Endorsement_Library__c EL=new Endorsement_Library__c();
        EL.Name='Test EL';
        EL.Text__c='Text';
        EL.Endorsement_Title__c='Title';
        Insert EL;
        VG_Policy_Schedule_Endorsement__c PSE=new VG_Policy_Schedule_Endorsement__c();
        PSE.VG_Endorsement_Details__c=EL.Text__c;
        PSE.VG_Endorsement_Library_Id__c=EL.Id;
        PSE.VG_Policy_Schedule__c=ps.Id;
        PSE.VG_Title__c=EL.Endorsement_Title__c;
        PSE.VG_Premium__c=0;
        Insert PSE;
        ApexPages.currentPage().getParameters().put('id', ps.Id);
        ApexPages.currentPage().getParameters().put('MTAType', null);
        VG_GentiumStep4_Controller gen=new VG_GentiumStep4_Controller();
        gen.Nexta();        
    }
}