force-app/main/default/objects/Endorsement_Library__c/Endorsement_Library__c.object-meta.xml
<CustomObject>
    <label>Endorsement Library</label>
    <nameField>
        <label>Endorsement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endorsement Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endorsement_Library__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <summarizedField>Policy_Schedule__c.VG_Brokerage_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Premium_Adjustment_2__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment_2__c</fullName>
    <label>Commercial Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Rate_On_Line__c.field-meta.xml
<CustomField>
    <fullName>Rate_On_Line__c</fullName>
    <label>Rate On Line (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Risk_Premium_Pro__c.field-meta.xml
<CustomField>
    <fullName>Risk_Premium_Pro__c</fullName>
    <label>Risk Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <label>Signed Share (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Overider_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Overider_Percent__c</fullName>
    <label>Overider(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Risk_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Risk_Premium__c</fullName>
    <label>Risk Premium (Annual)</label>
    <summarizedField>VG_Policy_Schedule_Asset__c.VG_Premium__c</summarizedField>
    <summaryForeignKey>VG_Policy_Schedule_Asset__c.VG_Policy_Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Layer__c.field-meta.xml
<CustomField>
    <fullName>VG_Layer__c</fullName>
    <label>Layer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st Layer</fullName>
            </value>
            <value>
                <fullName>2nd Layer</fullName>
            </value>
            <value>
                <fullName>3rd Layer</fullName>
            </value>
            <value>
                <fullName>4th Layer</fullName>
            </value>
            <value>
                <fullName>5th Layer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_No_of_Reinstatements__c.field-meta.xml
<CustomField>
    <fullName>VG_No_of_Reinstatements__c</fullName>
    <label>No of Reinstatements</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Plan_Loss_Ratio__c.field-meta.xml
<CustomField>
    <fullName>VG_Plan_Loss_Ratio__c</fullName>
    <label>Plan Loss Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Rate_Type__c</fullName>
    <label>Rate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat Premium</fullName>
            </value>
            <value>
                <fullName>Rate on Income</fullName>
            </value>
            <value>
                <fullName>Swing rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Territorial_Scope__c.field-meta.xml
<CustomField>
    <fullName>VG_Territorial_Scope__c</fullName>
    <label>Territorial Scope</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Worldwide</fullName>
            </value>
            <value>
                <fullName>Worldwide Ex North America</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Estonia</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Latvia</fullName>
            </value>
            <value>
                <fullName>Lithuania</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malta</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Romania</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Slovenia</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Deposit_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Deposit_Premium__c</fullName>
    <label>Deposit Premium(%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_GNPI__c.field-meta.xml
<CustomField>
    <fullName>VG_GNPI__c</fullName>
    <label>GNPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Limit_Precent__c.field-meta.xml
<CustomField>
    <fullName>VG_Limit_Precent__c</fullName>
    <label>Limit(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Minimum_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Minimum_Premium__c</fullName>
    <label>Minimum Premium(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Risk_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Risk_Premium__c</fullName>
    <label>Risk Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Horizon.recordType-meta.xml
<RecordType>
    <fullName>Horizon</fullName>
    <active>true</active>
    <label>Horizon</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VG_Revise_HorizonStepsController_Test.cls
@IsTest(SeeAllData=False)
public class VG_Revise_HorizonStepsController_Test {
    public static testMethod void TestMethod1() {
        //Cover Constructor 
        Test.StartTest();
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Horizon',acc.id);
        Endorsement_Library__c EL1=VG_TU.createEndorsementLibraryCustom('Horizon','Sub-limits');
        Endorsement_Library__c EL2=VG_TU.createEndorsementLibraryCustom('Horizon','Endorsements');
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        ps.Premium_Adjustment_2__c=2000;
        ps.Rate_On_Line__c=20.3;
        ps.Gross_Written_Premium__c=145200;
        ps.Risk_Premium_Pro__c=5000;
        ps.Share__c=25;
        ps.VG_Overider_Percent__c=15;
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 12, 15);
        ps.VG_Brokerage_Amount__c = 4000;
        update ps;
        Risk_Capture__c rc=vg_tu.createRiskCapture(ps.id);
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        psa.VG_Minimum_Premium__c=5008;
        psa.VG_Deposit_Premium__c=4560;
        psa.VG_Risk_Premium__c=5000;
        update psa;
        VG_Policy_Schedule_Endorsement__c pse=VG_TU.createPolicyScheduleEndorsement(ps.id);
        VG_Policy_Schedule_Endorsement__c pse1=VG_TU.createPolicyScheduleEndorsement(ps.id);
        ApexPages.currentPage().getParameters().put('Id', ps.id);
        ApexPages.currentPage().getParameters().put('MTAType', 'Revision of Cover');
        ApexPages.currentPage().getParameters().put('MTAStartDate', String.ValueOf(Date.newInstance(2017, 12, 18)));
        Test.stopTest();
        VG_Revise_HorizonStepsController hsc=new VG_Revise_HorizonStepsController();
        hsc.WrittenShare=11.5;
        hsc.SignedShare=10.5;
        hsc.GrossWrittenPremium=200000;
        hsc.TechnicalPremium=20000;
        hsc.Brokerage=15.0;
        hsc.Overider=12.3;
        hsc.FeeIncome=50000;
        hsc.PremiumAdjustment=5000;
        hsc.PSRiskPremium=5000;
        hsc.EndorsementPremium=5000;
        hsc.RateOnLine=12.3;
        hsc.Product='Property Per Event';
        hsc.Levies=2000;
        //cover cancel method
        hsc.Cancel();
        //cover step1
        hsc.gotostep1();
        hsc.Product='Property Per Event';
        //cover step2
        hsc.gotostep2();
        hsc.rc.VG_No_of_Reinstatements__c=String.valueOf(2);
        hsc.rc.VG_Plan_Loss_Ratio__c=12.3;
        hsc.rc.VG_Layer__c='1st Layer';
        hsc.rc.VG_Territorial_Scope__c='Asia';
        hsc.rc.VG_Rate_Type__c='Flat Premium';
        hsc.generateReinstatement();
        //cover step3
        hsc.gotostep3();
        hsc.Product='AGG Stop Loss';
        hsc.gotostep3();
        hsc.Product='Property Per Event';
        hsc.gotostep3();
        //cover Step 4a and 4b code 
        Endorsement_Library__c EL3=VG_TU.createEndorsementLibraryCustom('Horizon','Sub-limits');
        hsc.existingEndorsements.add(pse);
        hsc.gotostep4a();
        hsc.gotostep4b();
        hsc.LibraryWrapperList[0].IsSelected=True;
        hsc.gotostep4b();
        hsc.existingEndorsements.add(pse);
        hsc.gotostep4b();
        hsc.AddCustom();
        //cover Step 6a and 6b code
        hsc.existingEndorsements1.add(pse);
        hsc.gotostep6a();
        hsc.gotostep6b();
        hsc.LibraryWrapperList1[0].IsSelected=True;
        hsc.gotostep6b();
        hsc.existingEndorsements1.add(pse);
        hsc.gotostep6b();
        //cover step5
        hsc.gotostep5();
        //cover finish
        hsc.existingEndorsements1.clear();
        hsc.existingEndorsements.clear();
        hsc.existingEndorsements1.add(pse.clone(false,true,false,false));
        hsc.existingEndorsements.add(pse.clone(false,true,false,false));
        hsc.Finish();
        //cover generateReinstatement
        hsc.generateReinstatement();
        //cover cals
        hsc.Calc();
        //cover updatePremiums
        hsc.updatePremiums();
        //cover RiskRatingCalc
        hsc.RiskRatingCalc();
    }
    public static testMethod void TestMethod2() {
        Test.startTest();
        //Cover Constructor 
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Horizon',acc.id);
        Endorsement_Library__c EL1=VG_TU.createEndorsementLibraryCustom('Horizon','Sub-limits');
        Endorsement_Library__c EL2=VG_TU.createEndorsementLibraryCustom('Horizon','Endorsements');
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        ps.Premium_Adjustment_2__c=2000;
        ps.Rate_On_Line__c=20.3;
        ps.Gross_Written_Premium__c=145200;
        ps.Share__c=25;
        ps.VG_Overider_Percent__c=15;
        update ps;
        Risk_Capture__c rc=vg_tu.createRiskCapture(ps.id);
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        psa.VG_Limit_Precent__c=50;
        psa.VG_GNPI__c=5400;
        psa.VG_Risk_Premium__c=4000;
        update psa;
        Test.stopTest();
        VG_Policy_Schedule_Endorsement__c pse=VG_TU.createPolicyScheduleEndorsement(ps.id);
        VG_Policy_Schedule_Endorsement__c pse1=VG_TU.createPolicyScheduleEndorsement(ps.id);
        ApexPages.currentPage().getParameters().put('Id', ps.id);
        ApexPages.currentPage().getParameters().put('MTAType', '');
        ApexPages.currentPage().getParameters().put('MTAStartDate', String.ValueOf(Date.newInstance(2017, 12, 18)));
        VG_Revise_HorizonStepsController hsc=new VG_Revise_HorizonStepsController();
        hsc.WrittenShare=11.5;
        hsc.SignedShare=10.5;
        hsc.GrossWrittenPremium=200000;
        hsc.TechnicalPremium=20000;
        hsc.Brokerage=15.0;
        hsc.Overider=12.3;
        hsc.FeeIncome=50000;
        hsc.PremiumAdjustment=5000;
        hsc.PSRiskPremium=5000;
        hsc.EndorsementPremium=5000;
        hsc.TotalLayerPremium=15000;
        hsc.RateOnLine=12.3;
        hsc.Product='AGG Stop Loss';
        hsc.Levies=2000;
        //cover cancel method
        hsc.Cancel();
        //cover step1
        hsc.gotostep1();
        hsc.Product='AGG Stop Loss';
        //cover step2
        hsc.gotostep2();
        hsc.rc.VG_No_of_Reinstatements__c=String.valueOf(2);
        hsc.rc.VG_Plan_Loss_Ratio__c=12.3;
        hsc.rc.VG_Layer__c='1st Layer';
        hsc.rc.VG_Territorial_Scope__c='Asia';
        hsc.rc.VG_Rate_Type__c='Flat Premium';
        //cover step3
        hsc.gotostep3();
        hsc.Product='AGG Stop Loss';
        hsc.gotostep3();
        hsc.Product='Property Per Event';
        hsc.gotostep3();
        //cover Step 4a and 4b code 
        Endorsement_Library__c EL3=VG_TU.createEndorsementLibraryCustom('Horizon','Sub-limits');
        hsc.existingEndorsements.add(pse);
        hsc.gotostep4a();
        hsc.gotostep4b();
        hsc.LibraryWrapperList[0].IsSelected=True;
        hsc.gotostep4b();
        hsc.existingEndorsements.add(pse);
        hsc.gotostep4b();
        hsc.AddCustom();
        //cover Step 6a and 6b code
        hsc.existingEndorsements1.add(pse);
        hsc.gotostep6a();
        hsc.gotostep6b();
        hsc.LibraryWrapperList1[0].IsSelected=True;
        hsc.gotostep6b();
        hsc.existingEndorsements1.add(pse);
        hsc.gotostep6b();
        //cover step5
        hsc.gotostep5();
        hsc.RemoveCustom();
        //cover finish
        hsc.existingEndorsements1.clear();
        hsc.existingEndorsements.clear();
        hsc.existingEndorsements1.add(pse.clone(false,true,false,false));
        hsc.existingEndorsements.add(pse.clone(false,true,false,false));
        hsc.Finish();
        //cover generateReinstatement
        hsc.generateReinstatement();
        //cover cals
        hsc.Calc();
        //cover updatePremiums
        hsc.updatePremiums();
        //cover RiskRatingCalc
        hsc.RiskRatingCalc();
    }
}