force-app/main/default/objects/Endorsement_Library__c/Endorsement_Library__c.object-meta.xml
<CustomObject>
    <label>Endorsement Library</label>
    <nameField>
        <label>Endorsement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endorsement Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endorsement_Library__c/fields/Endorsement_Title__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Title__c</fullName>
    <label>Endorsement Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endorsement_Library__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Endorsement_Library__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Conviction_Points__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Conviction_Points__c</fullName>
    <label>Drivers Conviction Points</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Convictions__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Convictions__c</fullName>
    <label>Drivers Convictions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC10</fullName>
            </value>
            <value>
                <fullName>AC20</fullName>
            </value>
            <value>
                <fullName>AC30</fullName>
            </value>
            <value>
                <fullName>BA10</fullName>
            </value>
            <value>
                <fullName>BA30</fullName>
            </value>
            <value>
                <fullName>BA40</fullName>
            </value>
            <value>
                <fullName>BA60</fullName>
            </value>
            <value>
                <fullName>CD10</fullName>
            </value>
            <value>
                <fullName>CD20</fullName>
            </value>
            <value>
                <fullName>CD30</fullName>
            </value>
            <value>
                <fullName>CD40</fullName>
            </value>
            <value>
                <fullName>CD50</fullName>
            </value>
            <value>
                <fullName>CD60</fullName>
            </value>
            <value>
                <fullName>CD70</fullName>
            </value>
            <value>
                <fullName>CD80</fullName>
            </value>
            <value>
                <fullName>CD90</fullName>
            </value>
            <value>
                <fullName>CU10</fullName>
            </value>
            <value>
                <fullName>CU20</fullName>
            </value>
            <value>
                <fullName>CU30</fullName>
            </value>
            <value>
                <fullName>CU40</fullName>
            </value>
            <value>
                <fullName>CU50</fullName>
            </value>
            <value>
                <fullName>CU80</fullName>
            </value>
            <value>
                <fullName>DD10</fullName>
            </value>
            <value>
                <fullName>DD40</fullName>
            </value>
            <value>
                <fullName>DD60</fullName>
            </value>
            <value>
                <fullName>DD80</fullName>
            </value>
            <value>
                <fullName>DD90</fullName>
            </value>
            <value>
                <fullName>DR10</fullName>
            </value>
            <value>
                <fullName>DR20</fullName>
            </value>
            <value>
                <fullName>DR30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_DOB__c.field-meta.xml
<CustomField>
    <fullName>Drivers_DOB__c</fullName>
    <label>Drivers DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Name__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Name__c</fullName>
    <label>Drivers Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Rate_Per_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>VG_Rate_Per_Vehicle__c</fullName>
    <label>Annual Rate Per Vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>Cars – High Value</fullName>
            </value>
            <value>
                <fullName>Buses – 17+ seats</fullName>
            </value>
            <value>
                <fullName>Coaches – 17 + seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 7 seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 16 seats</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 3.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 7.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 12t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 18t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 24t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 30t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 44t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles over 44t</fullName>
            </value>
            <value>
                <fullName>Trade Plate</fullName>
            </value>
            <value>
                <fullName>Ghost Vehicle</fullName>
            </value>
            <value>
                <fullName>Motor Cycle</fullName>
            </value>
            <value>
                <fullName>Special Types</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Cars – Bluelight</fullName>
            </value>
            <value>
                <fullName>Vans – Bluelight</fullName>
            </value>
            <value>
                <fullName>Fire Engine</fullName>
            </value>
            <value>
                <fullName>Ambulance</fullName>
            </value>
            <value>
                <fullName>Motorcycle – Bluelight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Endorsement_Details__c.field-meta.xml
<CustomField>
    <fullName>VG_Endorsement_Details__c</fullName>
    <label>Endorsement Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Endorsement_Library_Id__c.field-meta.xml
<CustomField>
    <fullName>VG_Endorsement_Library_Id__c</fullName>
    <label>Endorsement Library Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Schedule_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Title__c.field-meta.xml
<CustomField>
    <fullName>VG_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VG_GentiumStep4b_Controller.cls
Public class VG_GentiumStep4b_Controller {
    public List<Endorsement_Library__c> ElList {get; set;}
    public List<LibraryWrapper> LibraryWrapperList {get; set;}
    public Id PSId {get; set;}
    public String PSName {get; set;}
    public Id policyid {get; set;}
    public List<VG_Policy_Schedule_Endorsement__c> existingEndorsements {get; set;}
    public Boolean hasEndorsements {get; set;}
    public Id OriginalId {get; set;}
    public String MTAType {get; set;}
    public Boolean IsCancellation {get; set;}
    public Boolean IsExtension {get; set;}
    public Boolean IsRevision {get; set;}
    public Boolean IsDeclaration {get; set;}
    public Integer counterEnd {get; set;}
//below one line added by siddik on 12.4.18
    public Policy_Schedule__c ps {get; set;}    
    Public VG_GentiumStep4b_Controller(){
        LibraryWrapperList = new List<LibraryWrapper>();
        LibraryWrapper LW;
        Set<Id> existingEndSet = new Set<Id>();
        PSId = apexpages.currentpage().getparameters().get('id');
        policyid=apexpages.currentpage().getparameters().get('policyid');
        OriginalId = apexpages.currentpage().getparameters().get('OriginalId');
        MTAType = apexpages.currentpage().getparameters().get('MTAType');
        if(MTAType == 'Extension'){
            IsExtension = True;
            IsCancellation = IsRevision = IsDeclaration = False;
        }else if(MTAType == 'Cancellation'){
            IsCancellation = True;
            IsExtension = IsRevision = IsDeclaration = False;
        }else if(MTAType == 'Revision of Cover'){
            IsRevision = True;
            IsCancellation = IsExtension = IsDeclaration = False;
        }else if(MTAType == 'Declaration'){
            IsDeclaration = True;
            IsCancellation = IsRevision = IsExtension = False;
        }
    //below one line added by siddik on 12.4.18        
        ps = [Select Id, Name,CurrencyIsoCode from Policy_Schedule__c where Id =: PSId limit 1];
        PSName = [Select Id, Name from Policy_Schedule__c where Id =: PSId].Name;
        Id GentiumId =  Schema.SObjectType.Endorsement_Library__c.getRecordTypeInfosByName().get('Gentium').getRecordTypeId();
        existingEndorsements = [Select Id, VG_Endorsement_Details__c, VG_Policy_Schedule__c, VG_Premium__c, VG_Title__c, VG_Endorsement_Library_Id__c from VG_Policy_Schedule_Endorsement__c where VG_Policy_Schedule__c =: PSId ORDER BY CreatedDate Desc];
        if(existingEndorsements.IsEmpty()){
            hasEndorsements = False;
            counterEnd = 0;
        }else{
            hasEndorsements = True;
            counterEnd = existingEndorsements.size();
        }
        for(VG_Policy_Schedule_Endorsement__c Endsmt: existingEndorsements){
            existingEndSet.add(Endsmt.VG_Endorsement_Library_Id__c);            
        }
        ElList = [Select Id,Text__c, Name, Endorsement_Title__c from Endorsement_Library__c where RecordTypeId =: GentiumId ORDER By Name ASC];
        for(Endorsement_Library__c EL : ElList){
            LW = new LibraryWrapper();
            LW.EL = EL;
            if(existingEndSet.contains(EL.Id)){
                LW.isSelected = True;
            }else{
                LW.isSelected = False;
            }
            LW.premium = 0;
            LibraryWrapperList.add(LW);
        }
    }
    
    public PageReference Cancel(){
        List<Policy_Schedule__c> ps =[select id,Name from Policy_Schedule__c where id=:PSId];
        List<VG_Policy_Schedule_Asset__c> psaList=[select id,Name,VG_Number_of_Vehicles__c,VG_Vehicle_Type__c,VG_Coverage__c,VG_Rate_Per_Vehicle__c,VG_Premium__c from VG_Policy_Schedule_Asset__c where VG_Policy_Schedule__c=:PSId];
        List<VG_Policy_Schedule_Endorsement__c> pseList=new List<VG_Policy_Schedule_Endorsement__c>([select id,Name,VG_Title__c,VG_Premium__c,VG_Endorsement_Details__c from VG_Policy_Schedule_Endorsement__c where VG_Policy_Schedule__c=:PSId]);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>([select Id,Name,Drivers_Name__c,Drivers_DOB__c,Drivers_Convictions__c,Drivers_Conviction_Points__c,Drivers_License_Ban_Details__c,Drivers_Claims__c,Drivers_Medical_Conditions__c from Risk_Capture__c where Policy_Schedule__c=:PSId]);
        if(!psaList.IsEmpty()){
            Delete psaList;
        }
        if(!pseList.IsEmpty()){
            Delete pseList;
        }
        if(!rcList.IsEmpty()){
            Delete rcList;
        }
        if(ps!=null){
            Delete ps;
        }
        return new PageReference('/'+policyid);
    }
    
    
    public PageReference Nexta(){
        List<VG_Policy_Schedule_Endorsement__c> endorsementsToBeInserted = new List<VG_Policy_Schedule_Endorsement__c>();
        VG_Policy_Schedule_Endorsement__c tempEndsmt;
        if(!existingEndorsements.IsEmpty()){
            Delete existingEndorsements;
        }
        counterEnd = 1;
        for(LibraryWrapper LW : LibraryWrapperList){
            if(LW.isSelected){
                tempEndsmt = new VG_Policy_Schedule_Endorsement__c();
                tempEndsmt.VG_Endorsement_Details__c = LW.EL.Text__c;
                tempEndsmt.VG_Endorsement_Library_Id__c = LW.EL.Id;
                tempEndsmt.VG_Policy_Schedule__c = PSId;
                tempEndsmt.VG_Title__c = LW.EL.Endorsement_Title__c;
                tempEndsmt.VG_Premium__c = 0;
                tempEndsmt.Name = PSName + '/PE/' + counterEnd;
                counterEnd++;
                endorsementsToBeInserted.add(tempEndsmt);
            }
        }
        if(!endorsementsToBeInserted.IsEmpty()){
            Insert endorsementsToBeInserted;
            System.debug(endorsementsToBeInserted.size() + 'Endorsements Inserted');
        }
        PageReference reference=new PageReference('/apex/VG_Gentium_Step4b');
        reference.getParameters().put('Id',PSId);
        reference.getParameters().put('policyid',policyid);
        if(MTAType !=null){
            reference.getParameters().put('MTAType',MTAType);
            reference.getParameters().put('OriginalId',OriginalId);
        }
        reference.setRedirect(true);
        return reference;
    }
    
     
    public PageReference AddCustom(){
        hasEndorsements = True;    
        VG_Policy_Schedule_Endorsement__c tempEndsmt = new VG_Policy_Schedule_Endorsement__c();
     //below one line added by siddik on 12.4.18
        tempEndsmt.CurrencyIsoCode=ps.CurrencyIsoCode;
        tempEndsmt.VG_Policy_Schedule__c = PSId;
        tempEndsmt.VG_Premium__c = 0;
        counterEnd++;
        tempEndsmt.Name = PSName + '/PE/'+counterEnd;
        Insert tempEndsmt;
        Update existingEndorsements;
        PageReference reference=new PageReference('/apex/VG_Gentium_Step4b');
        reference.getParameters().put('Id',PSId);
        reference.getParameters().put('policyid',policyid);
        if(MTAType !=null){
            reference.getParameters().put('MTAType',MTAType);
            reference.getParameters().put('OriginalId',OriginalId);
        }
        reference.setRedirect(true);
        return reference;
    }
     
    public PageReference Nextb(){
        if(!existingEndorsements.IsEmpty()){
            Upsert existingEndorsements;
        }
        PageReference reference=new PageReference('/apex/VG_Gentium_Step5');
        reference.getParameters().put('Id',PSId);
        reference.getParameters().put('policyid',policyid);
        if(MTAType !=null){
            reference.getParameters().put('MTAType',MTAType);
            reference.getParameters().put('OriginalId',OriginalId);
        }
        reference.setRedirect(true);
        return reference;
    }   
    
    public PageReference Previousb(){
        PageReference reference=new PageReference('/apex/VG_Gentium_Step4');
        reference.getParameters().put('Id',PSId);
        reference.getParameters().put('policyid',policyid);
        if(MTAType !=null){
            reference.getParameters().put('MTAType',MTAType);
            reference.getParameters().put('OriginalId',OriginalId);
        }
        if(MTAType !=null && (MTAType == 'Revision of Cover' || MTAType == 'Declaration')){
            List<VG_Policy_Schedule_Endorsement__c> pselist=new List<VG_Policy_Schedule_Endorsement__c>([select id from VG_Policy_Schedule_Endorsement__c where VG_Policy_Schedule__c =:PSId]);
            if(!pselist.IsEmpty()){
                Delete pselist;
            }
        }
        reference.setRedirect(true);
        return reference;
    }
    
    Public Class LibraryWrapper{
        Public Endorsement_Library__c EL {get; set;}
        Public Boolean isSelected {get; set;} 
        Public Decimal premium {get; set;}
        
        Public LibraryWrapper(){
            EL = new Endorsement_Library__c();
            isSelected = False;
            premium = 0;
        }
    }
    
}