force-app/main/default/objects/Endorsement_Library__c/Endorsement_Library__c.object-meta.xml
<CustomObject>
    <label>Endorsement Library</label>
    <nameField>
        <label>Endorsement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endorsement Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Endorsement_Library__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sub-limits</fullName>
            </value>
            <value>
                <fullName>Endorsements</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Endorsement_Library__c/fields/VG_Product__c.field-meta.xml
<CustomField>
    <fullName>VG_Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Burglary</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Machinery Breakdown</fullName>
            </value>
            <value>
                <fullName>CAR/EAR</fullName>
            </value>
            <value>
                <fullName>Escaping Liquid</fullName>
            </value>
            <value>
                <fullName>Cistern</fullName>
            </value>
            <value>
                <fullName>Freeze &amp; Refrigerator</fullName>
            </value>
            <value>
                <fullName>Robbery</fullName>
            </value>
            <value>
                <fullName>Special Objects</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Machinery BI</fullName>
            </value>
            <value>
                <fullName>Extra Costs</fullName>
            </value>
            <value>
                <fullName>Loss of Rent</fullName>
            </value>
            <value>
                <fullName>Epidemic Disease</fullName>
                <label>Epidemic Disease(BI)</label>
            </value>
            <value>
                <fullName>Liability GL/PL</fullName>
            </value>
            <value>
                <fullName>Legal Aid</fullName>
            </value>
            <value>
                <fullName>Crisis</fullName>
            </value>
            <value>
                <fullName>Personal Accident(visitor)</fullName>
            </value>
            <value>
                <fullName>Assault</fullName>
            </value>
            <value>
                <fullName>Tools</fullName>
            </value>
            <value>
                <fullName>Lift</fullName>
            </value>
            <value>
                <fullName>Forklift</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Rate_Per_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>VG_Rate_Per_Vehicle__c</fullName>
    <label>Annual Rate Per Vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Technical_UW_Rate_Annual__c.field-meta.xml
<CustomField>
    <fullName>VG_Technical_UW_Rate_Annual__c</fullName>
    <label>Technical UW Rate (Annual)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>Cars – High Value</fullName>
            </value>
            <value>
                <fullName>Buses – 17+ seats</fullName>
            </value>
            <value>
                <fullName>Coaches – 17 + seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 7 seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 16 seats</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 3.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 7.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 12t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 18t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 24t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 30t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 44t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles over 44t</fullName>
            </value>
            <value>
                <fullName>Trade Plate</fullName>
            </value>
            <value>
                <fullName>Ghost Vehicle</fullName>
            </value>
            <value>
                <fullName>Motor Cycle</fullName>
            </value>
            <value>
                <fullName>Special Types</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Cars – Bluelight</fullName>
            </value>
            <value>
                <fullName>Vans – Bluelight</fullName>
            </value>
            <value>
                <fullName>Fire Engine</fullName>
            </value>
            <value>
                <fullName>Ambulance</fullName>
            </value>
            <value>
                <fullName>Motorcycle – Bluelight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Policy Endorsements</relationshipLabel>
    <relationshipName>Policy_Schedule_Endorsements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VG_NordicsProductSteps_Test.cls
@IsTest(SeeAllData=False)
public class VG_NordicsProductSteps_Test {

    public static testmethod void testmethod1(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        List<Policy_Schedule__c> psList=new List<Policy_Schedule__c>();
        psList.add(ps);
        Insert psList; 
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        VG_Policy_Schedule_Asset__c psa=new VG_Policy_Schedule_Asset__c();
        psa.name='Test';
        psa.VG_Policy_Schedule__c=ps.id;
        psa.VG_Rate_Per_Vehicle__c=20;
        psa.VG_Number_of_Vehicles__c=10;
        psa.VG_Coverage__c='M3 - Fully Comprehensive';
        psa.VG_Vehicle_Type__c='Plant';
        psaList.add(psa);
        VG_Policy_Schedule_Asset__c psa1=new VG_Policy_Schedule_Asset__c();
        psa1.name='Test';
        psa1.VG_Policy_Schedule__c=ps.id;
        psa1.VG_Rate_Per_Vehicle__c=20;
        psa1.VG_Number_of_Vehicles__c=10;
        psa1.VG_Coverage__c='M3 - Fully Comprehensive';
        psa1.VG_Vehicle_Type__c='Cars';        
        psa1.VG_Technical_UW_Rate_Annual__c=5000;       
        Insert psa1;
        System.debug('psaList::'+psaList);
        
        PageReference pageRef = Page.VG_Nordics_Step1;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', pol.id);
        VG_NordicsProductSteps cntr = new VG_NordicsProductSteps();
        cntr.assetList=new List<VG_NordicsProductSteps.AssetWrapper>();        
        VG_NordicsProductSteps.AssetWrapper ass=new VG_NordicsProductSteps.AssetWrapper();                
        ass.asset=psaList[0];
        ass.AdjustedBIPremium=100;
        ass.counter='0';
        cntr.assetList.add(ass);
        System.debug('assetList1::'+cntr.assetList);
        VG_NordicsProductSteps.PricingWrapper pw=new VG_NordicsProductSteps.PricingWrapper();
        pw.price='0';
        cntr.otherFactors.add(pw);
        cntr.gotostep4();
        cntr.addRR();        
        cntr.RemoveRR();
        cntr.AddAsset();              
        cntr.CancelAsset();
        cntr.EditAsset();             
    }
    
    public static testmethod void testmethod2(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        List<Policy_Schedule__c> psList=new List<Policy_Schedule__c>();
        psList.add(ps);
        Insert psList; 
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        VG_Policy_Schedule_Asset__c psa=new VG_Policy_Schedule_Asset__c();
        psa.name='Test';
        psa.VG_Policy_Schedule__c=ps.id;
        psa.VG_Rate_Per_Vehicle__c=20;
        psa.VG_Number_of_Vehicles__c=10;
        psa.VG_Coverage__c='M3 - Fully Comprehensive';
        psa.VG_Vehicle_Type__c='Plant';
        psaList.add(psa);
        VG_Policy_Schedule_Asset__c psa1=new VG_Policy_Schedule_Asset__c();
        psa1.name='Test';
        psa1.VG_Policy_Schedule__c=ps.id;
        psa1.VG_Rate_Per_Vehicle__c=20;
        psa1.VG_Number_of_Vehicles__c=10;
        psa1.VG_Coverage__c='M3 - Fully Comprehensive';
        psa1.VG_Vehicle_Type__c='Cars';        
        psa1.VG_Technical_UW_Rate_Annual__c=5000;
        psaList.add(psa1);
        Insert psaList;        
        PageReference pageRef = Page.VG_Nordics_Step1;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', pol.id);
        VG_NordicsProductSteps cntr = new VG_NordicsProductSteps();  
        VG_NordicsProductSteps.RRWrapper rr=new VG_NordicsProductSteps.RRWrapper();
        rr.psa=psaList[0];
        rr.share=10;
        System.debug('share::'+rr.share);
        rr.Counter='0';
        rr.techPremium=1000;
        cntr.riskRatingList.add(rr);
        VG_NordicsProductSteps.RRWrapper rr1=new VG_NordicsProductSteps.RRWrapper();
        rr1.psa=psaList[1];
        rr1.share=100;
        rr1.Counter='1';
        rr1.techPremium=1100;
        cntr.riskRatingList.add(rr1);
        cntr.price.VG_Product__c='Property';
        List<VG_Pricing__c> priceList=new List<VG_Pricing__c>();
        VG_Pricing__c pr=new VG_Pricing__c();
        pr.Name='prTest1';
        pr.VG_Product__c='Property';
        pr.VG_Level__c = 'Risk Detail';
        pr.VG_Rate__c=1000;
        pr.VG_Rating_Factor__c='Agentur';
        pr.VG_Category__c = 'BI Base Rate';
        pr.VG_Order__c=1;
        priceList.add(pr);
        VG_Pricing__c pr1=new VG_Pricing__c();
        pr1.Name='prTest2';
        pr1.VG_Product__c='Property';
        pr1.VG_Level__c = 'Risk Detail';
        pr1.VG_Rate__c=1000;
        pr1.VG_Rating_Factor__c='Agentur';
        pr1.VG_Category__c = 'PD Base Rate';
        pr1.VG_Order__c=1;
        priceList.add(pr1);
        VG_Pricing__c pr2=new VG_Pricing__c();
        pr2.Name='prTest2';
        pr2.VG_Product__c='Property';
        pr2.VG_Level__c = 'Risk Detail';
        pr2.VG_Rate__c=1000;
        pr2.VG_Rating_Factor__c='Agentur';
        pr2.VG_Category__c = 'Pressure over 200 bar and/or temperature over 500 ºC';
        pr2.VG_Order__c=1;
        priceList.add(pr2);
        VG_Pricing__c pr4=pr1.clone(false,true,false,false);
        priceList.add(pr4);
        Insert priceList;
        System.debug('price::'+priceList);                
        cntr.AddCustom();
        cntr.gotostep1A();
        cntr.gotostep2();
        cntr.gotostep3();
        cntr.gotostep4();
        cntr.gotostep4b();
        cntr.gotostep5();
        cntr.cancel();
    }
    
    public static testmethod void testmethod3(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>();
        VG_Policy_Schedule_Asset__c psa=new VG_Policy_Schedule_Asset__c();
        psa.name='Test1';
        psa.VG_Policy_Schedule__c=ps.id;
        psa.VG_Rate_Per_Vehicle__c=20;
        psa.VG_Number_of_Vehicles__c=10;
        psa.VG_Coverage__c='M3 - Fully Comprehensive';
        psa.VG_Vehicle_Type__c='Plant';
        psaList.add(psa);
        VG_Policy_Schedule_Asset__c psa1=new VG_Policy_Schedule_Asset__c();
        psa1.name='Test2';
        psa1.VG_Policy_Schedule__c=ps.id;
        psa1.VG_Rate_Per_Vehicle__c=20;
        psa1.VG_Number_of_Vehicles__c=10;
        psa1.VG_Coverage__c='M3 - Fully Comprehensive';
        psa1.VG_Vehicle_Type__c='Cars';        
        psa1.VG_Technical_UW_Rate_Annual__c=5000;
        psaList.add(psa1);
        Insert psaList;        
        PageReference pageRef = Page.VG_Nordics_Step1;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', pol.id);
        VG_NordicsProductSteps cntr = new VG_NordicsProductSteps();
        cntr.price.VG_Product__c='GLPL';
        List<VG_Pricing__c> priceList=new List<VG_Pricing__c>();
        VG_Pricing__c pr=new VG_Pricing__c();
        pr.Name='prTest1';
        pr.VG_Product__c='GLPL';
        pr.VG_Level__c = 'Risk Detail';
        pr.VG_Rate__c=1000;
        pr.VG_Rating_Factor__c='Agentur';
        pr.VG_Category__c = 'Type of operation';
        pr.VG_Order__c=1;
        priceList.add(pr);
        VG_Pricing__c pr3=pr.clone(false,true,false,false);
        priceList.add(pr3);
        VG_Pricing__c pr1=new VG_Pricing__c();
        pr1.Name='prTest2';
        pr1.VG_Product__c='GLPL';
        pr1.VG_Level__c = 'Risk Detail';
        pr1.VG_Rate__c=1000;
        pr1.VG_Rating_Factor__c='Agentur';
        pr1.VG_Category__c = 'Deductible Adjustment';
        pr1.VG_Order__c=1;
        priceList.add(pr1);
        VG_Pricing__c pr2=new VG_Pricing__c();
        pr2.Name='prTest3';
        pr2.VG_Product__c='Property';
        pr2.VG_Level__c = 'Risk Detail';
        pr2.VG_Rate__c=1000;
        pr2.VG_Rating_Factor__c='Agentur';
        pr2.VG_Category__c = 'Deductible Adjustment';
        pr2.VG_Order__c=1;
        priceList.add(pr2);
        Insert priceList;
        cntr.gotostep2();
        cntr.updateExposure();
        //below code cover sub classes 
        VG_NordicsProductSteps.LibraryWrapper lw=new VG_NordicsProductSteps.LibraryWrapper();
        VG_NordicsProductSteps.AssetWrapper aw=new VG_NordicsProductSteps.AssetWrapper();
        VG_NordicsProductSteps.RRWrapper rrw=new VG_NordicsProductSteps.RRWrapper();
        VG_NordicsProductSteps.OtherFactors ofa=new VG_NordicsProductSteps.OtherFactors();
        VG_NordicsProductSteps.PricingWrapper pw=new VG_NordicsProductSteps.PricingWrapper();
        // above code cover sub classes 
    }
    
    public static testmethod void testmethod4(){
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        pol.CurrencyIsoCode='SEK';
        Update pol;
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        List<VG_Pricing__c> priceList=new List<VG_Pricing__c>();
        VG_Pricing__c pr=new VG_Pricing__c();
        pr.Name='prTest1';
        pr.VG_Product__c='GLPL';
        pr.VG_Level__c = 'Risk Detail';
        pr.VG_Rate__c=1000;
        pr.VG_Rating_Factor__c='Agentur';
        pr.VG_Category__c = 'Type of operation';
        pr.VG_Order__c=1;
        priceList.add(pr);
        VG_Pricing__c pr3=pr.clone(false,true,false,false);
        priceList.add(pr3);
        VG_Pricing__c pr1=new VG_Pricing__c();
        pr1.Name='prTest2';
        pr1.VG_Product__c='GLPL';
        pr1.VG_Level__c = 'Risk Detail';
        pr1.VG_Rate__c=1000;
        pr1.VG_Rating_Factor__c='Agentur';
        pr1.VG_Category__c = 'Deductible Adjustment';
        pr1.VG_Order__c=1;
        priceList.add(pr1);
        VG_Pricing__c pr2=new VG_Pricing__c();
        pr2.Name='prTest3';
        pr2.VG_Product__c='Property';
        pr2.VG_Level__c = 'Risk Detail';
        pr2.VG_Rate__c=1000;
        pr2.VG_Rating_Factor__c='Agentur';
        pr2.VG_Category__c = 'Deductible Adjustment';
        pr2.VG_Order__c=1;
        priceList.add(pr2);
        Insert priceList;
        Endorsement_Library__c el=VG_TU.createEndorsementLibrary();
        el.RecordTypeId=Schema.SObjectType.Endorsement_Library__c.getRecordTypeInfosByName().get('Bridge').getRecordTypeId();
        el.Type__c='Endorsements';
        el.VG_Product__c='Commercial';
        Update el;
        Endorsement_Library__c el1=el.clone(false,true,false,false);
        el1.Type__c='Sub-limits'; 
        Insert el1;
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        ApexPages.currentPage().getParameters().put('Currency', pol.CurrencyIsoCode);
        VG_NordicsProductSteps cntr = new VG_NordicsProductSteps();
        VG_NordicsProductSteps.RRWrapper rrw=new VG_NordicsProductSteps.RRWrapper();
        VG_NordicsProductSteps.LibraryWrapper lw=new VG_NordicsProductSteps.LibraryWrapper();
        RRW.psa = psa;
        RRW.counter = '0';
        RRW.share=0;
        cntr.cancel();//completed
        //cntr.updateDeductibleRate();//completed
        cntr.gotostep1A();//completed
        cntr.gotostep2();
        cntr.price=pr2;
        cntr.gotostep2();
        cntr.gotostep3();//completed 
        el.VG_Product__c=cntr.price.VG_Product__c;
        update el;
        el1.VG_Product__c=cntr.price.VG_Product__c;
        update el1;
        cntr.gotostep4();
        cntr.gotostep6();
        System.debug('19.3.2019::'+cntr.LibraryWrapperList1);
        cntr.LibraryWrapperList[0].IsSelected=false;
        cntr.LibraryWrapperList1[0].IsSelected=false;
        cntr.gotostep4b();
        cntr.gotostep6b();
        cntr.AddCustom();
        VG_Policy_Schedule_Endorsement__c tempEndsmt = new VG_Policy_Schedule_Endorsement__c();
        tempEndsmt.CurrencyISOCode = 'USD';
        tempEndsmt.VG_Endorsement_Library_Id__c=el.id;
        //tempEndsmt.VG_Policy_Schedule__c = PSId;
        tempEndsmt.VG_Premium__c = 1000;
        tempEndsmt.VG_Sub_limit__c=1000;
        //counterEnd++;
        //tempEndsmt.Name = PSName + '/PE/'+counterEnd;
        cntr.existingEndorsements1.add(tempEndsmt);
        cntr.existingEndorsements[0].VG_Premium__c =1000;
        cntr.existingEndorsements[0].VG_Sub_limit__c =1000;
        cntr.LibraryWrapperList[0].IsSelected=True;
        cntr.LibraryWrapperList1[0].IsSelected=True;
        cntr.gotostep4b();
        cntr.gotostep6b();
        cntr.gotostep5();//completed
        cntr.addRR();//completed
        cntr.AddCustom();//completed
        cntr.Index='0';
        cntr.counter=0;
        cntr.RemoveRR();//completed
        cntr.RemoveRR();//completed
        cntr.AddAsset();//completed
        cntr.SaveAsset();//completed
        cntr.AddAsset();//completed
        cntr.SaveAsset();//completed
        cntr.AddAsset();//completed
        cntr.SaveAsset();//completed
        cntr.RemoveAsset();//completed
        cntr.CancelAsset();//completed
        cntr.EditAsset();//completed
        cntr.setLPList();
        cntr.price.VG_Product__c='Commercial';
        cntr.setLPList();
        cntr.gotostep4();
        cntr.gotostep6();
        cntr.riskRatingList.add(RRW);
        cntr.IsProperty=false;
        cntr.gotostep4();
        cntr.gotostep6();
        cntr.price.VG_Product__c='GLPL';
        cntr.setLPList();
        cntr.price.VG_Product__c='Life Sciences';
        cntr.setLPList();
        cntr.price.VG_Product__c='D&O';
        cntr.setLPList();
        cntr.price.VG_Product__c='Clinical Trials';
        cntr.setLPList();
        cntr.price.VG_Product__c='Crime';
        cntr.setLPList();
        cntr.price.VG_Product__c='FIPI';
        cntr.setLPList();
        cntr.price.VG_Product__c='PI';
        cntr.setLPList();//completed
        cntr.getFLRates(50000000, 'IPO');
        cntr.getFLRates(100000000, 'IPO');
        cntr.getFLRates(250000000, 'IPO');
        cntr.getFLRates(500000000, 'IPO');
        cntr.getFLRates(750000000, 'IPO');
        cntr.getFLRates(1000000000, 'IPO');
        cntr.getFLRates(1500000000, 'IPO');
        cntr.getFLRates(2500000000L, 'IPO');
        cntr.getFLRates(5000000000L, 'IPO');
        cntr.getFLRates(10000000000L, 'IPO');
        cntr.getFLRates(25000000000L, 'IPO');
        cntr.getFLRates(50000000000L, 'IPO');
        cntr.getFLRates(100000000000L, 'IPO');
        cntr.getFLRates(500000000000L, 'IPO');
        cntr.getFLRates(50000000, 'Crime');
        cntr.getFLRates(100000000, 'Crime');
        cntr.getFLRates(250000000, 'Crime');
        cntr.getFLRates(500000000, 'Crime');
        cntr.getFLRates(750000000, 'Crime');
        cntr.getFLRates(1000000000, 'Crime');
        cntr.getFLRates(1500000000, 'Crime');
        cntr.getFLRates(2500000000L, 'Crime');
        cntr.getFLRates(5000000000L, 'Crime');
        cntr.getFLRates(10000000000L, 'Crime');
        cntr.getFLRates(25000000000L, 'Crime');
        cntr.getFLRates(50000000000L, 'Crime');
        cntr.getFLRates(100000000000L, 'Crime');
        cntr.getFLRates(500000000000L, 'Crime');
        cntr.getFLRates(50000000, 'D&O');
        cntr.getFLRates(100000000, 'D&O');
        cntr.getFLRates(250000000, 'D&O');
        cntr.getFLRates(500000000, 'D&O');
        cntr.getFLRates(750000000, 'D&O');
        cntr.getFLRates(1000000000, 'D&O');
        cntr.getFLRates(1500000000, 'D&O');
        cntr.getFLRates(2500000000L, 'D&O');
        cntr.getFLRates(5000000000L, 'D&O');
        cntr.getFLRates(10000000000L, 'D&O');
        cntr.getFLRates(25000000000L, 'D&O');
        cntr.getFLRates(50000000000L, 'D&O');
        cntr.getFLRates(100000000000L, 'D&O');
        cntr.getFLRates(500000000000L, 'D&O');
        cntr.getFLRates(500000000000L, 'GLPL');//Completed
        //cntr.finish();
    }
}