force-app/main/default/objects/Endorsement_Library__c/Endorsement_Library__c.object-meta.xml
<CustomObject>
    <label>Endorsement Library</label>
    <nameField>
        <label>Endorsement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endorsement Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Broker Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 3 AND 4) OR 5</booleanFilter>
        <errorMessage>Please select an approved broker or sub-broker</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sub-Broker</value>
        </filterItems>
        <filterItems>
            <field>Account.VG_TOBA_Uploaded__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Regulatory_Check__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Policy_Status__c</field>
            <operation>equals</operation>
            <value>NTU/Decline</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies (Broker)</relationshipLabel>
    <relationshipName>Policies_Broker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Volante_Entities__c.field-meta.xml
<CustomField>
    <fullName>VG_Volante_Entities__c</fullName>
    <label>Volante Entities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HEAG</fullName>
            </value>
            <value>
                <fullName>VCL</fullName>
            </value>
            <value>
                <fullName>VEML</fullName>
            </value>
            <value>
                <fullName>VIL</fullName>
                <default>true</default>
                <label>VIL</label>
            </value>
            <value>
                <fullName>VSR LLC</fullName>
            </value>
            <value>
                <fullName>VTSL</fullName>
            </value>
            <value>
                <fullName>BUAB</fullName>
            </value>
            <value>
                <fullName>VG UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Volante_Entities__c.field-meta.xml
<CustomField>
    <fullName>VG_Volante_Entities__c</fullName>
    <label>Volante Entities</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HEAG</fullName>
            </value>
            <value>
                <fullName>VCL</fullName>
            </value>
            <value>
                <fullName>VEML</fullName>
            </value>
            <value>
                <fullName>VIL</fullName>
            </value>
            <value>
                <fullName>VSR LLC</fullName>
            </value>
            <value>
                <fullName>VTSL</fullName>
            </value>
            <value>
                <fullName>BUAB</fullName>
            </value>
            <value>
                <fullName>VG UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Edison.recordType-meta.xml
<RecordType>
    <fullName>Edison</fullName>
    <active>true</active>
    <label>Edison</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Endorsement__c/VG_Policy_Schedule_Endorsement__c.object-meta.xml
<CustomObject>
    <label>Policy Endorsements</label>
    <nameField>
        <label>Policy Schedule Endorsement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Endorsements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VG_Edison_PolicyRenewalController_Test.cls
@IsTest(SeeAllData=false)
public class VG_Edison_PolicyRenewalController_Test {
    public static testMethod void TestMethod1() {
        VG_TU.policyCustomSetting();
        Test.startTest();
        Utilities.SkipMethods('Bridge Context');
        Account acc=VG_TU.createAccount('Customer');
        Account ba=VG_TU.createAccount('Broker');
        ba.VG_Volante_Entities__c = 'VIL';
        update ba;
        Policy__c pol=VG_TU.createPolicy('Edison Motor',acc.id);
        pol.VG_Volante_Entities__c = 'VIL';
        pol.Broker_Name__c = ba.id;
        update pol;
        Policy_Schedule__c ps=VG_TU.createPolicySchedule(pol.id);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>();
        Risk_Capture__c rc=VG_TU.createRiskCapture(ps.id);
        Risk_Capture__c rc1=VG_TU.createRiskCapture(ps.id);       
        Endorsement_Library__c el1=VG_TU.createEndorsementLibrary();
        VG_Policy_Schedule_Asset__c psa=VG_TU.createPolicyScheduleAsset(ps.id);
        VG_Policy_Schedule_Asset__c psa1=VG_TU.createPolicyScheduleAsset(ps.id);
        Endorsement_Library__c EL3=VG_TU.createEndorsementLibraryCustom('Edison Motor','Sub-limits');
        VG_Policy_Schedule_Endorsement__c pse=VG_TU.createPolicyScheduleEndorsement(ps.id);
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        VG_Edison_PolicyRenewalController pr=new VG_Edison_PolicyRenewalController();
        pr.gotostep1();
        pr.gotostep2();
        pr.rrWrapList[0].isSelected=true;
        pr.gotostep3();
        pr.pseWrapList[0].IsSelected=True;
        pr.Next();
        pr.Cancel();
        Utilities.clearMethods();
        Test.stopTest();
    }
}