force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Occurred__c.field-meta.xml
<CustomField>
    <fullName>Error_Occurred__c</fullName>
    <label>Error Occurred</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/VG_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>VG_Record_ID__c</fullName>
    <label>Record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorTrace.cls
Public Class ErrorTrace{
    
    public static string insertLog(Exception e,String RecordID){
        Error_Log__c error = new Error_Log__c();
        error.Name = e.getTypeName();
        error.Error__c = e.getMessage();
        error.Error_Occurred__c = System.Now();
        error.Stack_Trace__c = e.getStackTraceString();
        error.User__c = UserInfo.getUserId();
        error.VG_Record_ID__c = RecordID;
        Insert error;
        return error.id;
        
    }
}