force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_ReInsurance__c/VG_ReInsurance__c.object-meta.xml
<CustomObject>
    <label>Capacity Bordereaux</label>
    <nameField>
        <label>ReInsurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Bordereaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_UMR__c.field-meta.xml
<CustomField>
    <fullName>VG_UMR__c</fullName>
    <label>Unique Market Reference</label>
    <referenceTo>VG_UMR__c</referenceTo>
    <relationshipLabel>Capacity Bordereaux</relationshipLabel>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BDXFixBatch.cls
global class BDXFixBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {

        String query = Label.BDX_Fix_Batch;
        return Database.getQueryLocator(query);

    }

   // Execute method
    global void execute(Database.BatchableContext BC, List<Policy_Schedule__c> scope) {
         Set<Id> setIds = new Set<Id>();
         for(Policy_Schedule__c ps : scope){
             setIds.add(ps.Id);
         }
         List<VG_ReInsurance__c> RIList = [Select Id, VG_UMR__c, VG_Policy_Schedule__c from VG_ReInsurance__c where VG_Policy_Schedule__c IN: setIds];

         Delete RIList;
         PolicyScheduleTriggerFunction.allowInsertRI = True;
         PolicyScheduleTriggerFunction.createRIRecords(scope);
    }   
    // Finish Method

    global void finish(Database.BatchableContext BC) {

    }
}