force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission_Amount__c</fullName>
    <label>MGA Commission (Amount)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UMR_Exchange_Rates__c/UMR_Exchange_Rates__c.object-meta.xml
<CustomObject>
    <label>UMR Exchange Rates</label>
    <nameField>
        <label>UMR Exchange Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UMR Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UMR_Exchange_Rates__c/fields/VG_Capacity_Details__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capacity Details</label>
    <referenceTo>VG_UMR__c</referenceTo>
    <relationshipLabel>UMR Exchange Rates</relationshipLabel>
    <relationshipName>UMR_Exchange_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UMR_Exchange_Rates__c/fields/VG_Exchange_Rate_to_USD__c.field-meta.xml
<CustomField>
    <fullName>VG_Exchange_Rate_to_USD__c</fullName>
    <label>Exchange Rate (to USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/VG_ReInsurance__c.object-meta.xml
<CustomObject>
    <label>Capacity Bordereaux</label>
    <nameField>
        <label>ReInsurance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Bordereaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_ReInsurance__c/fields/UMR_Specific_Exchange_Rates_USD__c.field-meta.xml
<CustomField>
    <fullName>UMR_Specific_Exchange_Rates_USD__c</fullName>
    <label>UMR Specific Exchange Rates (USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_IS_Standard_Currency_Used__c.field-meta.xml
<CustomField>
    <fullName>VG_IS_Standard_Currency_Used__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default Exchange Rate Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission_Amount__c</fullName>
    <formula>IF(
AND(
     NOT(ISBLANK(VG_UMR__r.RI_Share_Cap__c)),
     IF(VG_Policy_Schedule__r.Gross_Written_Premium__c = 0, 0 , round((IF(ISBLANK(VG_MGA_Commission_Override__c),  VG_UMR__r.VG_MGA_Commission__c, (VALUE(VG_MGA_Commission_Override__c) )/100)* VG_RI_Premium__c) + IF(ISPICKVAL( VG_UMR__r.Net_MGA_Commission_Option__c ,&quot;Yes&quot;), Brokerage_Amount__c, 0),2)/VG_Policy_Schedule__r.Gross_Written_Premium__c) &gt;  VG_UMR__r.RI_Share_Cap__c) ,
 VG_UMR__r.RI_Share_Cap__c * VG_Policy_Schedule__r.Gross_Written_Premium__c, 
round((IF(ISBLANK(VG_MGA_Commission_Override__c),  VG_UMR__r.VG_MGA_Commission__c, (VALUE(VG_MGA_Commission_Override__c) )/100)* VG_RI_Premium__c) + IF(ISPICKVAL( VG_UMR__r.Net_MGA_Commission_Option__c ,&quot;Yes&quot;), Brokerage_Amount__c, 0),2))</formula>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_RI_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Premium__c</fullName>
    <formula>IF(ISPICKVAL( VG_UMR__r.VG_RI_Type__c , &apos;Gross&apos;) , VG_Policy_Schedule__r.Gross_Written_Premium__c * Participation_Ceded__c, IF(ISPICKVAL( VG_UMR__r.VG_RI_Type__c , &apos;Net&apos;), ( VG_Policy_Schedule__r.Gross_Written_Premium__c - VG_Policy_Schedule__r.VG_Brokerage_Amount__c )*Participation_Ceded__c, 0) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ceded Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_Status__c.field-meta.xml
<CustomField>
    <fullName>VG_Status__c</fullName>
    <formula>IF( VG_Policy_Schedule__r.VG_Is_MTA__c ,  TEXT(VG_Policy_Schedule__r.VG_Status__c) ,IF( VG_Policy_Schedule__r.VG_Base_Policy__c,  TEXT(VG_Policy_Schedule__r.Policy__r.Policy_Status__c),&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_ReInsurance__c/fields/VG_UMR__c.field-meta.xml
<CustomField>
    <fullName>VG_UMR__c</fullName>
    <label>Unique Market Reference</label>
    <referenceTo>VG_UMR__c</referenceTo>
    <relationshipLabel>Capacity Bordereaux</relationshipLabel>
    <relationshipName>ReInsurances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/fields/VG_MGA_Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_MGA_Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_UMR__c/fields/VG_RI_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_RI_Premium__c</fullName>
    <label>Total Bound Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReInsuranceTriggerFunction.cls
/*

 *Created By : Venkat
 
 *Created On : 19-12-2017
 
 *JIRA.No    : 
 
 *Test Class : 
*/
Public Class ReInsuranceTriggerFunction{
    Public Static Void Handler(List<VG_ReInsurance__c> TriggerNew,List<VG_ReInsurance__c> TriggerOld,Map<Id,VG_ReInsurance__c> TriggerNewMap,Map<Id,VG_ReInsurance__c> TriggerOldMap,Boolean IsBefore,Boolean IsAfter,Boolean IsInsert,Boolean IsUpdate,Boolean IsDelete,Boolean IsUnDelete){
        if(IsBefore && (IsInsert || IsUpdate)){
            UMRCurrencycheck(TriggerNew, TriggerOldMap, IsInsert, IsUpdate);    
        }
        if(IsBefore && IsUpdate){          
              
        }
        
        if(IsAfter && (IsInsert||IsUpdate)){
            if(!Utilities.avoidRecursionCheck('RollupFields'))
                RollupFields(TriggerNew);
        }
        if(IsBefore && IsDelete){
            
        }
    }
    
    public static void UMRCurrencycheck(List<VG_ReInsurance__c> TriggerNew, Map<Id,VG_ReInsurance__c> TriggerOldMap, Boolean IsInsert, Boolean IsUpdate){        
        Set<Id> UMRIds  =  new Set<Id>();
        List<CurrencyType> exchangeRates  = new List<CurrencyType>([Select Id,  ConversionRate,  IsoCode from CurrencyType]);
        Map<Id,VG_UMR__c> umrMap = new Map<Id,VG_UMR__c>([select id, Name from VG_UMR__c]);               
        List<UMR_Exchange_Rates__c> umrExchangeRateList = new List<UMR_Exchange_Rates__c>([Select Id,Name,CurrencyIsoCode,VG_Exchange_Rate_to_USD__c,VG_Capacity_Details__c from UMR_Exchange_Rates__c where VG_Capacity_Details__c IN: umrMap.keySet()]);
        Map<String,UMR_Exchange_Rates__c> EXMap = new Map<String,UMR_Exchange_Rates__c>();
        for(UMR_Exchange_Rates__c EX : umrExchangeRateList){
            String key = EX.VG_Capacity_Details__c + ':' + EX.Name;
            EXMap.put(key,EX);
        }
        Map<String,Decimal> conversionRate = new Map<String,Decimal>();
        for(CurrencyType rt : exchangeRates){
            conversionRate.put(rt.IsoCode,rt.ConversionRate);
        }
        for(VG_ReInsurance__c RI : TriggerNew){
            String key = RI.VG_UMR__c  + ':' + RI.CurrencyIsoCode;
            if(IsInsert || (IsUpdate && RI.CurrencyISOCode != TriggerOldMap.get(RI.Id).CurrencyISOCode)){
                If(EXMap.containsKey(key)){
                    RI.UMR_Specific_Exchange_Rates_USD__c = EXMap.get(key).VG_Exchange_Rate_to_USD__c;
                    RI.VG_IS_Standard_Currency_Used__c = false; 
                }else{
                    RI.UMR_Specific_Exchange_Rates_USD__c = conversionRate.get(RI.CurrencyIsoCode);
                    RI.VG_IS_Standard_Currency_Used__c = true; 
                }   
            }         
        }
    }
    
    public Static Void RollupFields(List<VG_ReInsurance__c> TriggerNew){
        Set<Id> UMRIds = new Set<Id>();
        Set<Id> PSIds = new Set<Id>();
        Set<Id> TriggerNewIds = new Set<Id>();
        for(VG_ReInsurance__c RI: TriggerNew){
            UMRIds.add(RI.VG_UMR__c);
            PSIds.add(RI.VG_Policy_Schedule__c);
            TriggerNewIds.add(RI.VG_Policy_Schedule__c);
        }
        System.debug(PSIds);
        List<CurrencyType> exchangeRates = [Select Id, ConversionRate, IsoCode from CurrencyType ];
        Map<String,CurrencyType> currencyRateMap=new Map<String,CurrencyType>();
        for(CurrencyType cr: exchangeRates){
            currencyRateMap.put(cr.IsoCode,cr);
        }
        Map<Id,Policy_Schedule__c> psMap=new Map<Id,Policy_Schedule__c>([Select Id, Name,VG_MGA_Commission_Amount__c  from Policy_Schedule__c where Id IN: PSIds AND VG_Status__c='Booked']);
        List<VG_ReInsurance__c> existingRIs = [Select Id,CurrencyIsoCode,VG_MGA_Commission_Amount__c, VG_RI_Premium__c, VG_UMR__c, VG_Policy_Schedule__c from VG_ReInsurance__c where (VG_UMR__c IN: UMRIds OR VG_Policy_Schedule__c IN: psMap.keyset()) AND (VG_Status__c = 'Bound' OR VG_Status__c = 'Booked')];
        System.Debug('existingRIs::'+existingRIs);
        Map<Id, Decimal> UMRMGAComm = new Map<Id, Decimal>();
        Map<Id, Decimal> UMRRIPremium = new Map<Id, Decimal>();
        Map<Id, Decimal> PSMGAComm = new Map<Id, Decimal>();
        List<VG_UMR__c> UMRToBeUpdated = new List<VG_UMR__c>();
        List<Policy_Schedule__c> PSToBeUpdated = new List<Policy_Schedule__c>();
        VG_UMR__c UMR;
        Policy_Schedule__c PS;
        PSIds.clear();
        for(VG_ReInsurance__c RI : existingRIs){
            PSIds.add(RI.VG_Policy_Schedule__c);
            if(UMRMGAComm.get(RI.VG_UMR__c) == null){
                UMRMGAComm.put(RI.VG_UMR__c, ((RI.VG_MGA_Commission_Amount__c!=null?RI.VG_MGA_Commission_Amount__c:0)/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate));        
            }else{
                Decimal tempMGA = UMRMGAComm.get(RI.VG_UMR__c);
                tempMGA = tempMGA + ((RI.VG_MGA_Commission_Amount__c!=null?RI.VG_MGA_Commission_Amount__c:0)/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate);
                UMRMGAComm.put(RI.VG_UMR__c, tempMGA);   
            }
            if(UMRRIPremium.get(RI.VG_UMR__c) == null){
                UMRRIPremium.put(RI.VG_UMR__c, (RI.VG_RI_Premium__c/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate) );        
            }else{
                Decimal tempPre = UMRRIPremium.get(RI.VG_UMR__c);
                tempPre = tempPre+ (RI.VG_RI_Premium__c/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate) ;
                UMRRIPremium.put(RI.VG_UMR__c, tempPre);   
            }
            if(PSMGAComm.get(RI.VG_Policy_Schedule__c) == null){
                PSMGAComm.put(RI.VG_Policy_Schedule__c, ((RI.VG_MGA_Commission_Amount__c!=null?RI.VG_MGA_Commission_Amount__c:0)/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate));        
            }else{
                Decimal tempMGA = PSMGAComm.get(RI.VG_Policy_Schedule__c);
                tempMGA = tempMGA + ((RI.VG_MGA_Commission_Amount__c!=null?RI.VG_MGA_Commission_Amount__c:0)/currencyRateMap.get(RI.CurrencyIsoCode).ConversionRate);
                tempMGA =tempMGA.setScale(2);
                PSMGAComm.put(RI.VG_Policy_Schedule__c, tempMGA);   
            }
        }
        for(Id UMRId : UMRRIPremium.keySet()){
            UMR = new VG_UMR__c();
            UMR.Id = UMRId;
            UMR.VG_MGA_Commission_Amount__c = UMRMGAComm.get(UMRId);
            UMR.VG_RI_Premium__c = UMRRIPremium.get(UMRId);
            UMRToBeUpdated.add(UMR);
        }
        System.debug(PSIds);
        Map<Id,Policy_Schedule__c> psMap1=new Map<Id,Policy_Schedule__c>([Select Id, Name,VG_MGA_Commission_Amount__c,VG_Status__c  from Policy_Schedule__c where Id IN: PSIds]);
        for(Id PSId : PSMGAComm.keySet()){
            System.debug('9.12(1)::'+PSId+'::'+psMap1.containsKey(PSId)+'::'+psMap1.get(PSId).VG_MGA_Commission_Amount__c+'::'+PSMGAComm.get(PSId));
            if(TriggerNewIds.contains(PSId) && psMap1.containsKey(PSId) && psMap1.get(PSId).VG_Status__c=='Booked' && psMap1.get(PSId).VG_MGA_Commission_Amount__c != PSMGAComm.get(PSId).setScale(2)){
                System.debug('9.12::'+PSId+'::'+psMap1.containsKey(PSId)+'::'+psMap1.get(PSId).VG_MGA_Commission_Amount__c+'::'+PSMGAComm.get(PSId)+'::'+PSMGAComm.get(PSId).setScale(2));
                PS = new Policy_Schedule__c();
                PS.Id = PSId;
                PS.VG_MGA_Commission_Amount__c = PSMGAComm.get(PSId);
                PSToBeUpdated.add(PS);
            }
        }
        if(!UMRToBeUpdated.IsEmpty()){
            Update UMRToBeUpdated;
        }
        if(!PSToBeUpdated.IsEmpty()){
            Update PSToBeUpdated;
        }
    }
}