force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Tax_Amount_GWP_100__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Amount_GWP_100__c</fullName>
    <label>Tax Amount GWP 100%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/VFP.recordType-meta.xml
<RecordType>
    <fullName>VFP</fullName>
    <active>true</active>
    <label>VFP</label>
</RecordType>

force-app/main/default/objects/VG_Taxes__c/VG_Taxes__c.object-meta.xml
<CustomObject>
    <label>Taxes</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Comment__c.field-meta.xml
<CustomField>
    <fullName>VG_Comment__c</fullName>
    <label>Comment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Is_Temp_Delete__c.field-meta.xml
<CustomField>
    <fullName>VG_Is_Temp_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Temp Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Override__c.field-meta.xml
<CustomField>
    <fullName>VG_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Administered_By__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Administered_By__c</fullName>
    <label>Tax Administered By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Insurer</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Amount__c</fullName>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Amount_GWP_100__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Amount_GWP_100__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tax Amount GWP 100%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Jurisdiction__c</fullName>
    <label>Tax Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia - Northern Territory (NT)</fullName>
            </value>
            <value>
                <fullName>Australia - Western Territory (WA)</fullName>
            </value>
            <value>
                <fullName>Australia - New South Wales (NSW)</fullName>
            </value>
            <value>
                <fullName>Australia - South Australia (SA)</fullName>
            </value>
            <value>
                <fullName>Australia - Queensland (QLD)</fullName>
            </value>
            <value>
                <fullName>Australia - Victoria (VIC)</fullName>
            </value>
            <value>
                <fullName>Australia - Tasmania (TAS)</fullName>
            </value>
            <value>
                <fullName>Australia - Australian Capital Territory (ACT)</fullName>
            </value>
            <value>
                <fullName>Australia - Jervis Bay Territory (JBT)</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada - Alberta (AB)</fullName>
            </value>
            <value>
                <fullName>Canada - British Columbia (BC)</fullName>
            </value>
            <value>
                <fullName>Canada - NewFoundland and Labrador (NL)</fullName>
            </value>
            <value>
                <fullName>Canada - Northwest Territories (NT)</fullName>
            </value>
            <value>
                <fullName>Canada - Nunavut (NU)</fullName>
            </value>
            <value>
                <fullName>Canada - Manitoba (MB)</fullName>
            </value>
            <value>
                <fullName>Canada - New Brunswick (NB)</fullName>
            </value>
            <value>
                <fullName>Canada - Nova Scotia (NS)</fullName>
            </value>
            <value>
                <fullName>Canada - Ontario (ON)</fullName>
            </value>
            <value>
                <fullName>Canada - Prince Edward Island (PE)</fullName>
            </value>
            <value>
                <fullName>Canada - Quebec (QC)</fullName>
            </value>
            <value>
                <fullName>Canada - Saskatchewan (SK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Paid_By__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Paid_By__c</fullName>
    <label>Tax Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Insured</fullName>
            </value>
            <value>
                <fullName>Insurer</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Capacity</fullName>
                <isActive>false</isActive>
                <label>Capacity</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Tax_Percent__c.field-meta.xml
<CustomField>
    <fullName>VG_Tax_Percent__c</fullName>
    <label>Tax (%)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/VG_Taxes__c/fields/VG_Taxable_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Taxable_Amount__c</fullName>
    <label>Taxable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DownloadAllTaxesController.cls
Public Class DownloadAllTaxesController{

    public ID psId{get;set;}
    
    public String psName{get;set;}
    public String header{get;set;}
    
    public boolean isVFP{get;set;}
    
    public List<VG_Taxes__c> taxList{get;set;}
    
    public DownloadAllTaxesController(){
        
        psId = apexpages.currentpage().getparameters().get('Id');
        isVFP = false;
        taxList = new List<VG_Taxes__c >([select id, Name, VG_Override__c,VG_Tax_Amount_GWP_100__c,VG_Policy_Schedule__r.RecordType.Name, CurrencyIsoCode, VG_Is_Temp_Delete__c, VG_Taxable_Amount__c, VG_Tax_Amount__c, VG_Tax_Paid_By__c, VG_Comment__c, VG_Tax_Percent__c, VG_Tax_Administered_By__c, VG_Policy_Schedule__c, VG_Policy_Schedule__r.Name, VG_Tax_Jurisdiction__c from VG_Taxes__c where VG_Policy_Schedule__c =: psid ]); 
        psName = taxList[0].VG_Policy_Schedule__r.Name;
        if(taxList[0].VG_Policy_Schedule__r.RecordType.Name == 'VFP'){
            header = 'Tax Type,Tax (%),Taxable Amount,Tax Amount,Tax Amount GWP 100%,Tax Jurisdcition,Tax Administered By,Tax Paid By,Comment,Override';
            isVFP = true;
        }else{
            header = 'Tax Type,Tax (%),Taxable Amount,Tax Amount,Tax Jurisdcition,Tax Administered By,Tax Paid By,Comment,Override';
        }
        
    }

}