force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Coverages__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverages__c</fullName>
    <label>Coverages</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBA</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>All Perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and Allied Perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of Profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Number_Of_vehicle__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_Of_vehicle__c</fullName>
    <label>Number Of vehicle</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>All perils</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Fire and allied perils</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>EAR</fullName>
            </value>
            <value>
                <fullName>Motor Hull</fullName>
            </value>
            <value>
                <fullName>Loss of profit</fullName>
            </value>
            <value>
                <fullName>CatNat</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Launch Vehicle Flight</fullName>
            </value>
            <value>
                <fullName>Combined Flight-Post Separation</fullName>
            </value>
            <value>
                <fullName>Comined Flight-In-Orbit</fullName>
            </value>
            <value>
                <fullName>In-Orbit</fullName>
            </value>
            <value>
                <fullName>Launch Vehicle Flight Only</fullName>
            </value>
            <value>
                <fullName>Assembly,Intetgratio and Testing</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>Engine Testing</fullName>
            </value>
            <value>
                <fullName>Launch Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>In-Orbit Third Party Liabilities</fullName>
            </value>
            <value>
                <fullName>MF-Overseas PD PL ex USA</fullName>
                <label>MF-Overseas PD TPL ex USA</label>
            </value>
            <value>
                <fullName>MP-EU PD TPL ex UK</fullName>
            </value>
            <value>
                <fullName>Named Perils</fullName>
            </value>
            <value>
                <fullName>All Risk</fullName>
            </value>
            <value>
                <fullName>Business Interruption</fullName>
            </value>
            <value>
                <fullName>Office Comprehensive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyScheduleAssetTriggerFunction.cls
/*

 *Created By : Siddik
 
 *Created On : 10-09-2018
 
 *JIRA.No    : -
 
 *Test Class : PolicyScheduleAssetTriggeFunctionTest
 
*/

Public Class PolicyScheduleAssetTriggerFunction{

    Public Static Void Handler(List<VG_Policy_Schedule_Asset__c> TriggerNew,List<VG_Policy_Schedule_Asset__c> TriggerOld,Map<Id,VG_Policy_Schedule_Asset__c> TriggerNewMap,Map<Id,VG_Policy_Schedule_Asset__c> TriggerOldMap,Boolean IsBefore,Boolean IsAfter,Boolean IsInsert,Boolean IsUpdate,Boolean IsDelete){
        if(IsAfter && (IsInsert||IsUpdate)){
            updatePolicyScheduleRollups(TriggerNew,TriggerNewMap);
        }
        if(IsBefore && IsUpdate){          
        }
        if((IsAfter && IsInsert)){
        }
        if(IsAfter && IsUpdate){
        }
        if(IsBefore && IsDelete){
            
        }
    }
    Public Static Void updatePolicyScheduleRollups(List<VG_Policy_Schedule_Asset__c> TriggerNew,Map<Id,VG_Policy_Schedule_Asset__c> TriggerNewMap){
        Set<ID> psIds=new Set<ID>();
        for(VG_Policy_Schedule_Asset__c psa: TriggerNew){
            psIds.add(psa.VG_Policy_Schedule__c);
        }
        List<VG_Policy_Schedule_Asset__c> psaList=new List<VG_Policy_Schedule_Asset__c>([select id,VG_Policy_Schedule__c, VG_Coverage__c,VG_Number_of_Vehicles__c from VG_Policy_Schedule_Asset__c where VG_Policy_Schedule__c IN: psIds]);
        Map<id,List<VG_Policy_Schedule_Asset__c>> psMap=new Map<id,List<VG_Policy_Schedule_Asset__c>>();
        List<Policy_Schedule__c> psList=new List<Policy_Schedule__c>();
        for(VG_Policy_Schedule_Asset__c psa: psaList){
            if(psMap.containsKey(psa.VG_Policy_Schedule__c)) {
                List<VG_Policy_Schedule_Asset__c> psaList1 = psMap.get(psa.VG_Policy_Schedule__c);
                psaList1.add(psa);
                psMap.put(psa.VG_Policy_Schedule__c, psaList1);
            } else {
                psMap.put(psa.VG_Policy_Schedule__c, new List<VG_Policy_Schedule_Asset__c> { psa });
            }
        }
        for(Id ps: psMap.KeySet()){
            Decimal NOV=0;
            String COV='';
            for(VG_Policy_Schedule_Asset__c psa : psMap.get(ps)){
                if(psa.VG_Number_of_Vehicles__c != null)
                NOV = NOV + psa.VG_Number_of_Vehicles__c;
                if(COV == ''){
                    COV=psa.VG_Coverage__c;
                }else if(psa.VG_Coverage__c != null && psa.VG_Coverage__c != COV ){
                    COV='Mixed';
                }
            }
            System.debug('10-09 Test::'+COV+'::'+NOV);
            Policy_Schedule__c temPs=new Policy_Schedule__c();
            temPs.id=ps;
            temPs.VG_Coverages__c=COV;
            temPs.VG_Number_Of_vehicle__c=NOV;
            psList.add(temPs);
        }
        if(!psList.IsEmpty()){
            update psList;
        }
    }
}