force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>GLPL</fullName>
            </value>
            <value>
                <fullName>Life Sciences</fullName>
            </value>
            <value>
                <fullName>Clinical Trials</fullName>
            </value>
            <value>
                <fullName>D&amp;O</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>FIPI</fullName>
            </value>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Property Per Event</fullName>
            </value>
            <value>
                <fullName>Property Per Risk</fullName>
            </value>
            <value>
                <fullName>AGG XL</fullName>
            </value>
            <value>
                <fullName>AGG Stop Loss</fullName>
            </value>
            <value>
                <fullName>Fleet</fullName>
            </value>
            <value>
                <fullName>Schemes</fullName>
            </value>
            <value>
                <fullName>Commercial Combined</fullName>
            </value>
            <value>
                <fullName>Public Sector – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Commercial – Non Conventional</fullName>
            </value>
            <value>
                <fullName>Motor</fullName>
            </value>
            <value>
                <fullName>FI - PI</fullName>
            </value>
            <value>
                <fullName>FI - Cyber</fullName>
            </value>
            <value>
                <fullName>FI - D&amp;O</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>FI - Crime</fullName>
            </value>
            <value>
                <fullName>FI - Blend</fullName>
            </value>
            <value>
                <fullName>Commercial Crime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Claims__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Claims__c</fullName>
    <label>Drivers Claims</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Conviction_Points__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Conviction_Points__c</fullName>
    <label>Drivers Conviction Points</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Convictions__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Convictions__c</fullName>
    <label>Drivers Convictions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC10</fullName>
            </value>
            <value>
                <fullName>AC20</fullName>
            </value>
            <value>
                <fullName>AC30</fullName>
            </value>
            <value>
                <fullName>BA10</fullName>
            </value>
            <value>
                <fullName>BA30</fullName>
            </value>
            <value>
                <fullName>BA40</fullName>
            </value>
            <value>
                <fullName>BA60</fullName>
            </value>
            <value>
                <fullName>CD10</fullName>
            </value>
            <value>
                <fullName>CD20</fullName>
            </value>
            <value>
                <fullName>CD30</fullName>
            </value>
            <value>
                <fullName>CD40</fullName>
            </value>
            <value>
                <fullName>CD50</fullName>
            </value>
            <value>
                <fullName>CD60</fullName>
            </value>
            <value>
                <fullName>CD70</fullName>
            </value>
            <value>
                <fullName>CD80</fullName>
            </value>
            <value>
                <fullName>CD90</fullName>
            </value>
            <value>
                <fullName>CU10</fullName>
            </value>
            <value>
                <fullName>CU20</fullName>
            </value>
            <value>
                <fullName>CU30</fullName>
            </value>
            <value>
                <fullName>CU40</fullName>
            </value>
            <value>
                <fullName>CU50</fullName>
            </value>
            <value>
                <fullName>CU80</fullName>
            </value>
            <value>
                <fullName>DD10</fullName>
            </value>
            <value>
                <fullName>DD40</fullName>
            </value>
            <value>
                <fullName>DD60</fullName>
            </value>
            <value>
                <fullName>DD80</fullName>
            </value>
            <value>
                <fullName>DD90</fullName>
            </value>
            <value>
                <fullName>DR10</fullName>
            </value>
            <value>
                <fullName>DR20</fullName>
            </value>
            <value>
                <fullName>DR30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_DOB__c.field-meta.xml
<CustomField>
    <fullName>Drivers_DOB__c</fullName>
    <label>Drivers DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_License_Ban_Details__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License_Ban_Details__c</fullName>
    <label>Drivers License Ban Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Medical_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Medical_Conditions__c</fullName>
    <label>Drivers Medical Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Drivers_Name__c.field-meta.xml
<CustomField>
    <fullName>Drivers_Name__c</fullName>
    <label>Drivers Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_IsTemp__c.field-meta.xml
<CustomField>
    <fullName>VG_IsTemp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Number_of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>VG_Number_of_Vehicles__c</fullName>
    <label>Number of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cars</fullName>
            </value>
            <value>
                <fullName>Cars – High Value</fullName>
            </value>
            <value>
                <fullName>Buses – 17+ seats</fullName>
            </value>
            <value>
                <fullName>Coaches – 17 + seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 7 seats</fullName>
            </value>
            <value>
                <fullName>Minibuses – upto 16 seats</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 3.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 7.5t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 12t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 18t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 24t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 30t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles upto 44t</fullName>
            </value>
            <value>
                <fullName>Commercial Vehicles over 44t</fullName>
            </value>
            <value>
                <fullName>Trade Plate</fullName>
            </value>
            <value>
                <fullName>Ghost Vehicle</fullName>
            </value>
            <value>
                <fullName>Motor Cycle</fullName>
            </value>
            <value>
                <fullName>Special Types</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Cars – Bluelight</fullName>
            </value>
            <value>
                <fullName>Vans – Bluelight</fullName>
            </value>
            <value>
                <fullName>Fire Engine</fullName>
            </value>
            <value>
                <fullName>Ambulance</fullName>
            </value>
            <value>
                <fullName>Motorcycle – Bluelight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VG_EdisonPS_Ins2_Controller.cls
Public Class VG_EdisonPS_Ins2_Controller{
    Public List<Risk_Capture__c> rcList{get;set;}
    public String Index{get;set;}
    Public Policy_Schedule__c ps{get;set;}
    Public List<WrapperRisk> wrcList{get;set;}
    Public Risk_Capture__c rc{get;set;}
    Public String policyid{get;set;}
    public Integer counter{get;set;}
    Public String psid{get;set;}
    public Id OriginalId {get; set;}
    public String MTAType {get; set;}
    public Boolean IsCancellation {get; set;}
    public Boolean IsExtension {get; set;}
    public Boolean IsRevision {get; set;}
    public Boolean IsDeclaration {get; set;}
    //public String Product_seleced{get;set;}
    
    Public VG_EdisonPS_Ins2_Controller(){
        counter=0;
        policyid=apexpages.currentpage().getparameters().get('policyid');
        psid=apexpages.currentpage().getparameters().get('id');
        OriginalId = apexpages.currentpage().getparameters().get('OriginalId');
        MTAType = apexpages.currentpage().getparameters().get('MTAType');
        if(MTAType == 'Extension'){
            IsExtension = True;
            IsCancellation = IsRevision = IsDeclaration = False;
        }else if(MTAType == 'Cancellation'){
            IsCancellation = True;
            IsExtension = IsRevision = IsDeclaration = False;
        }else if(MTAType == 'Revision of Cover'){
            IsRevision = True;
            IsCancellation = IsExtension = IsDeclaration = False;
        }else if(MTAType == 'Declaration'){
            IsDeclaration = True;
            IsCancellation = IsRevision = IsExtension = False;
        }else{
            IsDeclaration=IsCancellation = IsRevision = IsExtension = False;
        }
        ps=[select id,Name,CurrencyIsoCode,Product__c from Policy_Schedule__c where id=:psid];
        //Product_seleced=ps.Product__c;             
        rcList=new List<Risk_Capture__c>();
        wrcList=new List<WrapperRisk>();
        rc=new Risk_Capture__c();
        if(MTAType == null){
            rcList=new List<Risk_Capture__c>([select id,Name,VG_IsTemp__c, VG_IsTempDelete__c,Drivers_Claims__c,Drivers_Conviction_Points__c,Drivers_Convictions__c,Drivers_DOB__c,Drivers_License_Ban_Details__c,Drivers_Medical_Conditions__c,Drivers_Name__c,Policy_Schedule__c from Risk_Capture__c where Policy_Schedule__c=:psid AND VG_IsTempDelete__c=false]);
        }else{
            System.debug('TestrcList::'+rcList.size()+'::psid::'+psid+'::'+rcList);
            rcList=new List<Risk_Capture__c>([select id,Name,VG_IsTemp__c, VG_IsTempDelete__c,Drivers_Claims__c,Drivers_Conviction_Points__c,Drivers_Convictions__c,Drivers_DOB__c,Drivers_License_Ban_Details__c,Drivers_Medical_Conditions__c,Drivers_Name__c,Policy_Schedule__c from Risk_Capture__c where Policy_Schedule__c=:OriginalId]);        
        }              
        if(!rcList.IsEmpty()){ 
            System.debug('rcList::'+rcList.size()+'::psid::'+psid+'::'+rcList);                       
            for(Risk_Capture__c rc:rcList){
                rc.Policy_Schedule__c=psid;  //this line Added by Anu 3.2.2018
                WrapperRisk wrc=new WrapperRisk(); 
                if(MTAType == null){
                    wrc.rc=rc;               
                }else{
                    wrc.rc=rc.clone(false, true, false, false);
                }
                System.debug('wrc::'+wrc.rc.Policy_Schedule__c);
                wrc.Counter=String.valueOf(counter);
                wrcList.add(wrc);
                System.debug('Cntrcounter::'+counter);
                counter++;
                System.debug('Cntrcounter::'+counter);
                System.debug('wrcList::'+wrcList);
            }
        }
    }
    
    
    public class WrapperRisk{
        public Risk_Capture__c rc{get;set;}
        public String Counter{get;set;}
    }
    
    
    public void AddRisk(){        
        WrapperRisk wrc=new WrapperRisk();
        rc.VG_IsTemp__c = True;
        wrc.rc=rc;
        wrc.Counter=String.valueOf(counter);
        wrcList.add(wrc);
        counter++;
        rc=new Risk_Capture__c();
    }
    
    
    public void RemoveRisk(){
        //wrcList.remove(integer.valueOf(Index));
        counter=0;
        System.debug('wrcList::'+wrcList);
        for(WrapperRisk wrc: wrcList){
            wrc.Counter=String.valueOf(counter);
            System.debug('wrc.Counter::'+wrc.Counter);
            if(counter == integer.valueOf(Index)){
                wrc.rc.VG_IsTempDelete__c = True;
                System.debug('delete:::'+wrc.rc.VG_IsTempDelete__c+counter +integer.valueOf(Index));
            }
            counter++;
        }
        System.debug('wrcList::'+wrcList);
    }    
    
    public void EditRisk(){
        rc=wrcList[integer.valueOf(Index)].rc;
        System.debug('rc::'+rc.Policy_Schedule__c);        
        wrcList.remove(integer.valueOf(Index));
        //counter--;
        counter=0;
        for(WrapperRisk wrc:wrcList){
            wrc.Counter=String.valueOf(counter);
            counter++;
        }
    }
    
    
    public PageReference Cancel(){
        Policy_Schedule__c ps =[select id,Name,Product__c from Policy_Schedule__c where id=:psid];
        List<VG_Policy_Schedule_Asset__c> psaList=[select id,Name,VG_Number_of_Vehicles__c,VG_Vehicle_Type__c,VG_Coverage__c,VG_Rate_Per_Vehicle__c,VG_Premium__c from VG_Policy_Schedule_Asset__c where VG_Policy_Schedule__c=:psid];
        List<VG_Policy_Schedule_Endorsement__c> pseList=new List<VG_Policy_Schedule_Endorsement__c>([select id,Name,VG_Title__c,VG_Premium__c,VG_Endorsement_Details__c from VG_Policy_Schedule_Endorsement__c where VG_Policy_Schedule__c=:psid]);
        List<Risk_Capture__c> rcList=new List<Risk_Capture__c>([select Id,Name,Drivers_Name__c,Drivers_DOB__c,Drivers_Convictions__c,Drivers_Conviction_Points__c,Drivers_License_Ban_Details__c,Drivers_Claims__c,Drivers_Medical_Conditions__c from Risk_Capture__c where Policy_Schedule__c=:psid]);
        if(!psaList.IsEmpty()){
            Delete psaList;
        }
        if(!pseList.IsEmpty()){
            Delete pseList;
        }
        if(!rcList.IsEmpty()){
            Delete rcList;
        }
        if(ps!=null){
            Delete ps;
        }
        if(IsDeclaration ||  IsRevision )
            return new PageReference('/'+OriginalId);
        else
            return new PageReference('/'+policyid);
    }
    
    
    public PageReference Next(){
        List<Risk_Capture__c> rcInsList=new List<Risk_Capture__c>();
        List<Risk_Capture__c> RCtoBeDeleted = new List<Risk_Capture__c>();
        
        /*If(ps.Product__c=='Unisured Loss Recovery'){
            rc.Policy_Schedule__c=ps.id;
            rc.Name=ps.Name+'/RD/1';
            System.debug('rc::'+rc);
            Insert rc;
        }*/
        
        for(WrapperRisk wrc:wrcList){
            wrc.rc.CurrencyIsoCode=ps.CurrencyIsoCode;
            if(!wrc.rc.VG_IsTempDelete__c){
                 rcInsList.add(wrc.rc);
            }
            if(wrc.rc.VG_IsTempDelete__c && wrc.rc.id!=null){
                 RCtoBeDeleted.add(wrc.rc);
            }         
        }
        System.debug('rcInsList::'+rcInsList+'::'+RCtoBeDeleted);
        If(!RCtoBeDeleted.IsEmpty()){
            Delete RCtoBeDeleted;
        }
        if(!rcInsList.IsEmpty()){
            Integer count = 0;
            for(Risk_Capture__c rc:rcInsList){
                rc.Policy_schedule__c=ps.id;
                rc.Name=ps.Name+'/RD/'+count;                            
                count++;
            }
            If(ps.Product__c!='Unisured Loss Recovery'){
                Upsert rcInsList;
            }               
        }
        if(MTAType == null){
            return new PageReference('/apex/VG_EdisonPS_Ins3?policyid='+policyid+'&id='+psid);
        }else{
            return new PageReference('/apex/VG_EdisonPS_Ins3?MTAType='+MTAType+'&OriginalId='+OriginalId+'&id='+ps.id+'&policyid='+policyid);
        }        
    }
    
    
    public PageReference previous(){
        if(MTAType == null){
            return new PageReference('/apex/VG_EdisonPS_Ins1?id='+policyid+'&psid='+psid);         
        }else{
            //return new PageReference('/apex/VG_EdisonPS_Ins1?MTAType='+MTAType+'&OriginalId='+OriginalId+'&psid='+ps.id);
            // code added by siddik on 19.2.2018
            Policy_Schedule__c ps=[select id,name,Product__c from Policy_Schedule__c where id=:psid];
            delete ps;
            return new PageReference('/apex/VG_EdisonPS_Ins1?MTAType='+MTAType+'&OriginalId='+OriginalId);
            //end added ...19.2.2018
        }  
          
    }
}