force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claims_Schedule__c/Claims_Schedule__c.object-meta.xml
<CustomObject>
    <label>Claims Schedule</label>
    <nameField>
        <label>Claims Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claims_Schedule__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims Schedules</relationshipLabel>
    <relationshipName>Claims_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/VG_Ignore_Validation__c.field-meta.xml
<CustomField>
    <fullName>VG_Ignore_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Gentium.recordType-meta.xml
<RecordType>
    <fullName>Gentium</fullName>
    <active>true</active>
    <label>Gentium</label>
</RecordType>

force-app/main/default/classes/ClaimScheduleTriggerFunction_Test.cls
@IsTest(SeeAllData=False)
public class ClaimScheduleTriggerFunction_Test {
    Public Static TestMethod Void testMethod1(){
        Account acc=VG_TU.createAccount('Customer');
        VG_TU.policyCustomSetting();        
        Policy__c pol=VG_TU.createPolicy('Gentium', acc.id);
        system.debug(pol.VG_Ignore_Validation__c);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        Insert ps;        
        Test.startTest();
        Utilities.SkipMethods('Trigger Context2');
        claim__c cl=VG_TU.createClaim(acc.id,pol.id);
        Claims_Schedule__c cs1=VG_TU.createClaimSchedule(acc.id,ps.id,cl.id);
        Claims_Schedule__c cs2=VG_TU.createClaimSchedule(acc.id,ps.id,cl.id);
        Claims_Schedule__c cs3=VG_TU.createClaimSchedule(acc.id,ps.id,cl.id);
        Utilities.clearMethods();
        Test.stopTest();
        
        
    }
}