force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Number</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claims_Progression__c/Claims_Progression__c.object-meta.xml
<CustomObject>
    <label>Claims Progression</label>
    <nameField>
        <label>Claims Progression Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims Progressions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claims_Progression__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <formula>VG_Claims_Schedule__r.Claim__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Claim</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claims_Progression__c/fields/VG_Claims_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Claims_Schedule__c</fullName>
    <label>Claims Schedule</label>
    <referenceTo>Claims_Schedule__c</referenceTo>
    <relationshipLabel>Claims Progressions</relationshipLabel>
    <relationshipName>Claims_Progressions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claims_Schedule__c/Claims_Schedule__c.object-meta.xml
<CustomObject>
    <label>Claims Schedule</label>
    <nameField>
        <label>Claims Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claims_Schedule__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claims Schedules</relationshipLabel>
    <relationshipName>Claims_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Capacity_Paper__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Paper__c</fullName>
    <label>Section No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PI Liberty 100%</fullName>
            </value>
            <value>
                <fullName>PI Liberty Co</fullName>
            </value>
            <value>
                <fullName>PI Liberty Lloyds</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual VFP</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - D&amp;O/Crime</fullName>
            </value>
            <value>
                <fullName>Hazardous</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Haulage</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Non Conventional</fullName>
            </value>
            <value>
                <fullName>Bridge Default</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI Open Market (2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI CE (2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI CE (2019)</fullName>
            </value>
            <value>
                <fullName>Written in 2020</fullName>
            </value>
            <value>
                <fullName>PT into 2020</fullName>
            </value>
            <value>
                <fullName>2018 Liberty Company Stamp - 2018 year</fullName>
            </value>
            <value>
                <fullName>2019 - 2019 YOA - 10 MUSD - 60% Liberty, 10% Swiss, 30% Everest</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - 10 MUSD - 60% Liberty, 10% Swiss, 30% Everest</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - after Partner PT</fullName>
            </value>
            <value>
                <fullName>2020 - 4 MUSD (Liberty 3 + Swiss 1)</fullName>
            </value>
            <value>
                <fullName>2020 - 5.5 MUSD (Liberty 3+Swiss 1, Fidelis 0+Partner 1.5)</fullName>
            </value>
            <value>
                <fullName>Special - Inmarsat PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Measat PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Ovzon PT Stamp</fullName>
            </value>
            <value>
                <fullName>Special - Resurs PT Stamp</fullName>
            </value>
            <value>
                <fullName>2019 - 2020 YOA - 10 MUSD - 90% Liberty, 10% Swiss</fullName>
            </value>
            <value>
                <fullName>2020 - 13.5 MUSD (3+1, 1.5, 2.5+2.5+0.5+2.5)</fullName>
            </value>
            <value>
                <fullName>2020 - Liberty and Lineslip (Argentina)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_UMR__c/VG_UMR__c.object-meta.xml
<CustomObject>
    <label>Capacity Details</label>
    <nameField>
        <label>Unique Market Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capacity Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_UMR__c/fields/VG_Capacity_Paper__c.field-meta.xml
<CustomField>
    <fullName>VG_Capacity_Paper__c</fullName>
    <label>Section No</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PI Liberty 100%</fullName>
            </value>
            <value>
                <fullName>PI Liberty Co</fullName>
            </value>
            <value>
                <fullName>PI Liberty Lloyds</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual VFP</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - D&amp;O/Crime</fullName>
            </value>
            <value>
                <fullName>Warranty &amp; Indemnity</fullName>
            </value>
            <value>
                <fullName>CE - VSR</fullName>
            </value>
            <value>
                <fullName>CE - VSR Amwin</fullName>
            </value>
            <value>
                <fullName>Greenlight Re</fullName>
            </value>
            <value>
                <fullName>Fidelis</fullName>
            </value>
            <value>
                <fullName>AGCS</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (FY 2019)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (FY 2020)</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (Section A - 2020)</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Amwin</fullName>
            </value>
            <value>
                <fullName>Liberty Mutual - FI (Section A - 2019)</fullName>
            </value>
            <value>
                <fullName>Hazardous</fullName>
            </value>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Haulage</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Non Conventional</fullName>
            </value>
            <value>
                <fullName>Liberty &amp; Everest</fullName>
            </value>
            <value>
                <fullName>Liberty Only</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Allianz</fullName>
            </value>
            <value>
                <fullName>VSR - FI - Aspen</fullName>
            </value>
            <value>
                <fullName>VSR - FI - RSUI</fullName>
            </value>
            <value>
                <fullName>Bridge Default</fullName>
            </value>
            <value>
                <fullName>VSR - AmWINS - Defense Only</fullName>
            </value>
            <value>
                <fullName>VSR - AmWINS - Funds Mgmt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimsProgressionTriggerFunction_Test.cls
@IsTest(SeeAllData=False)
public class ClaimsProgressionTriggerFunction_Test {
    Public Static TestMethod Void testMethod1(){
        Account acc=VG_TU.createAccount('Customer');
        VG_TU.policyCustomSetting(); 
        Policy__c pol=VG_TU.createPolicy('Edison Motor', acc.id);
        Policy_Schedule__c ps=new Policy_Schedule__c(Name='Test');
        ps.Policy__c=pol.id;
        Insert ps;
        claim__c c=new Claim__c();
        c.Name='test';
        c.Account__c=acc.id;
        c.Policy_Number__c=pol.id;
        Insert c;  
        Test.startTest();
        VG_UMR__c u=VG_TU.createUMR(acc.id);      
        System.debug('paper::'+u.VG_Capacity_Paper__c);
        claim__c cl=VG_TU.createClaim(acc.id,pol.id);
        Claims_Schedule__c cs1=VG_TU.createClaimSchedule(acc.id,ps.id,cl.id);
        Claims_Progression__c cp=new Claims_Progression__c();
        cp.RecordTypeId=Schema.SObjectType.Claims_Progression__c.getRecordTypeInfosByName().get('Claim Financial').getRecordTypeId();        
        cp.Name='Test';
        cp.VG_Claims_Schedule__c=cs1.id;
        Insert cp;        
        Claims_Progression__c cp1=VG_TU.createClaimProgression('Claim Recovery',cs1.id);        
        Claims_Progression__c cp2=VG_TU.createClaimProgression('Claim Financial',cs1.id);        
   	    Test.stopTest();
    }
}