force-app/main/default/objects/VG_Attachment__c/VG_Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Policy__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DocumentFixClass.cls
global class DocumentFixClass implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        String query = 'Select Id, Name, VG_Attachment__c, VG_Policy__c from VG_Attachment__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<VG_Attachment__c> records){
        // process each batch of records
        Set<Id> docIds = new Set<Id>();
        Set<Id> attachmentIds = new Set<Id>();
        for(VG_Attachment__c att : records){
            if(att.VG_Attachment__c != null){
                if(att.VG_Attachment__c.substring(0,3) == '00P'){
                    //attachmentIds.add(att.VG_Attachment__c); 
                }else{
                    docIds.add(att.VG_Attachment__c);
                } 
            }
        }
        List<contentversion> versions = [select id,title,ContentDocument.ParentId, ContentDocumentId,FileExtension from contentversion where Id IN: docIds];
        System.debug('versions'+versions.size());
        Map<Id, Id> versionMap = new Map<Id, Id>();
        for(contentversion ver : versions){
            System.debug(ver.ContentDocumentId);
            versionMap.put(ver.Id, ver.ContentDocumentId);
        }
        Map<Id, String> docNames = new Map<Id, String>();
        Map<Id, ContentDocumentLink> docsList = versionMap.IsEmpty() ? new Map<Id, ContentDocumentLink>() : new Map<Id, ContentDocumentLink>([SELECT ContentDocumentID, ContentDocument.Title, LinkedEntity.type, LinkedEntityId FROM ContentDocumentLink where ContentDocumentID IN: versionMap.values()]);
        for(ContentDocumentLink CDL : docsList.values()){
            CDL.ShareType = 'I';
            CDL.Visibility = 'AllUsers';
        }
        Update docsList.values();
    }    
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    
}