force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/LS_AccName_with_Ass_Name__c.field-meta.xml
<CustomField>
    <fullName>LS_AccName_with_Ass_Name__c</fullName>
    <externalId>true</externalId>
    <label>Asset External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>Launcher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Actual_GWP__c.field-meta.xml
<CustomField>
    <fullName>Actual_GWP__c</fullName>
    <formula>Gross_Written_Premium__c - VG_Brokerage_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <formula>IF( ISPICKVAL( Policy_Status__c , &quot;Prospect&quot;), VG_Prospect_Premium__c , Gross_Written_Premium_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <summarizedField>Policy_Schedule__c.Levies__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Technical_UW_Premium__c.field-meta.xml
<CustomField>
    <fullName>Technical_UW_Premium__c</fullName>
    <label>Technical UW Premium</label>
    <summarizedField>Policy_Schedule__c.Technical_UW_Premium__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <summarizedField>Policy_Schedule__c.VG_Brokerage_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <summarizedField>Policy_Schedule__c.VG_Fee_Income__c</summarizedField>
    <summaryFilterItems>
        <field>Policy_Schedule__c.VG_Co_Insurance_type__c</field>
        <operation>notEqual</operation>
        <value>Child</value>
    </summaryFilterItems>
    <summaryForeignKey>Policy_Schedule__c.Policy__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Policy__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/Policy__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Actual_GWP__c.field-meta.xml
<CustomField>
    <fullName>Actual_GWP__c</fullName>
    <label>Actual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_or_Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_or_Net_Premium__c</fullName>
    <label>Gross or Net Premium</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gross</fullName>
            </value>
            <value>
                <fullName>Net</fullName>
                <default>true</default>
                <label>Net</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Gross_Written_Premium__c.field-meta.xml
<CustomField>
    <fullName>Gross_Written_Premium__c</fullName>
    <label>Gross Written Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/IPT_Percent__c.field-meta.xml
<CustomField>
    <fullName>IPT_Percent__c</fullName>
    <label>IPT (%)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Levies__c.field-meta.xml
<CustomField>
    <fullName>Levies__c</fullName>
    <label>Levies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Premium_Adjustment_2__c.field-meta.xml
<CustomField>
    <fullName>Premium_Adjustment_2__c</fullName>
    <label>Commercial Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Share__c.field-meta.xml
<CustomField>
    <fullName>Share__c</fullName>
    <label>Signed Share (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Brokerage_Amount__c.field-meta.xml
<CustomField>
    <fullName>VG_Brokerage_Amount__c</fullName>
    <label>Brokerage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_Fee_Income__c.field-meta.xml
<CustomField>
    <fullName>VG_Fee_Income__c</fullName>
    <label>Fee Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_MTA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>VG_MTA_Start_Date__c</fullName>
    <label>MTA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/VG_VAT__c.field-meta.xml
<CustomField>
    <fullName>VG_VAT__c</fullName>
    <label>VAT (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/Risk_Capture__c/Risk_Capture__c.object-meta.xml
<CustomObject>
    <label>Risk Details</label>
    <nameField>
        <label>Risk Capture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Capture__c/fields/Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipLabel>Risk Details</relationshipLabel>
    <relationshipName>Risk_Captures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Capture__c/fields/VG_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>VG_Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/Annual_Rate_100__c.field-meta.xml
<CustomField>
    <fullName>Annual_Rate_100__c</fullName>
    <label>Annual Premium Share</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Risk Rating</relationshipLabel>
    <relationshipName>Risk_Rating</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/Technical_UW_Premium__c.field-meta.xml
<CustomField>
    <fullName>Technical_UW_Premium__c</fullName>
    <label>Technical UW Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Sum_Insured__c.field-meta.xml
<CustomField>
    <fullName>VG_Sum_Insured__c</fullName>
    <label>Sum Insured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/classes/VG_ReviseAesirStepsController_Test.cls
@IsTest(SeeAllData=False)
public class VG_ReviseAesirStepsController_Test {
    public static testMethod void TestMethod1(){
        VG_TU.policyCustomSetting();
        Test.startTest();
        Account acc=VG_TU.createAccount('Customer');
        Utilities.SkipMethods('Bridge Context');        
        Policy__c pol=VG_TU.createPolicy('Aesir',acc.id);
        List<Policy_Schedule__c> psList2=new List<Policy_Schedule__c>();
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        ps.Gross_Written_Premium__c=5000;
        ps.Technical_UW_Premium__c=5487;
        ps.Premium_Adjustment_2__c=48752;
        ps.Gross_or_Net_Premium__c='Gross';
        ps.Actual_GWP__c=1540;
        ps.VG_Brokerage_Amount__c=450;
        ps.IPT_Percent__c=45;
        ps.VG_Fee_Income__c=4500;
        ps.Levies__c=4500;
        ps.VG_VAT__c=20;        
        update ps;
        ps.VG_MTA_Start_Date__c=Date.newInstance(2017, 12, 15);
        ps.VG_Brokerage_Amount__c = 4000;
        ps.Share__c=20;
        update ps;
        Policy_Schedule__c ps1=VG_Tu.createPolicySchedule(pol.id);
        psList2.add(ps);
        psList2.add(ps1);
        Risk_Capture__c rc=new Risk_Capture__c();
        rc.Name='Test';
        rc.Policy_Schedule__c=ps.id;  
        //rc.VG_Additional_Information__c='Notice of Event Limit :2000<br>Proof of Loss Limit :2000<br>Payment after POL limit :2000<br>Sunset Clause :2000<br>Salvage Provisions :2000<br>CTL Provisions :2000<br>Loss Minimisation :2000<br>Power Margin :2000<br>Propellant Margin :2000<br>Loss Formula :2000<br>AVN 41/21:2000<br>';
        Insert rc;
        Asset__c ass=VG_TU.createAsset(acc.id); 
        ass.LS_AccName_with_Ass_Name__c='Test1';
        update ass;
        VG_Policy_Schedule_Asset__c rr=VG_TU.createPolicyScheduleAsset(ps.id);     
        rr.Asset__c=ass.id;
        update rr;
        ApexPages.currentPage().getParameters().put('Id', ps.id);   
        ApexPages.currentPage().getParameters().put('MTAStartDate', String.valueOf(Date.newInstance(2019, 7, 17)));                
        ApexPages.currentPage().getParameters().put('MTAType', 'Revision of Cover');                
        VG_ReviseAesirStepsController aes=new VG_ReviseAesirStepsController();        
        aes.gotostep1();
        aes.gotostep2a();
        aes.fileName='test';
        aes.fileBody=blob.valueOf('Asset External id,Risk Start Date,Risk End Date,Coverage,Coverage Type,Limit,Attachment,AVG SI,Rate(%),Signed Shared(%),Annual Premium,Sum Insured\n Test1,14-08-19,31-08-19,Marine Cargo Treaty,Full cover,5000,5520,2900,25,15,0,0\n');       
        VG_ReviseAesirStepsController.RRWrapper RRW =new VG_ReviseAesirStepsController.RRWrapper();
        RRW.psa=rr;
        RRW.techPremium=4500;
        RRW.sumInsured=470;
        RRW.assName=ass.LS_AccName_with_Ass_Name__c;
        aes.addedRRList.add(RRW);           
        aes.RRCalc();
        aes.gotostep2b();                
        aes.gotostep5();
        aes.Cancel();
        aes.gotostep2();
        aes.SummaryCalc();
        aes.finish();
        Utilities.clearMethods();
        Test.stopTest();
    }
    public static testMethod void TestMethod2() {
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Aesir',acc.id);
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        Asset__c ass=new Asset__c();
        ass.VG_Asset_Type__c='Launcher';
        ass.Name='Test456';
        ass.LS_AccName_with_Ass_Name__c='Test456';
        ass.VG_Account__c=acc.id;
        Insert ass;
        VG_Policy_Schedule_Asset__c rr=new VG_Policy_Schedule_Asset__c();   
        rr.VG_Policy_Schedule__c=ps.id;
        rr.Asset__c=ass.Id;
        rr.Annual_Rate_100__c=4500;
        rr.VG_Premium__c=780;
        rr.VG_Sum_Insured__c=8000;
        insert rr;
        Risk_Capture__c rc=new Risk_Capture__c();
        rc.Name='Test';
        rc.Policy_Schedule__c=ps.id;  
        rc.VG_Additional_Information__c=+'RDInfo :'+'aa'+'<br>'
        +'Notice of Event Limit :'+'2000'+'<br>'
        +'Proof of Loss Limit :'+'2000'+'<br>'
        +'Payment after POL limit :'+'2000'+'<br>'
        +'Sunset Clause :'+'2000'+'<br>'
        +'Salvage Provisions :'+'2000'+'<br>'
        +'CTL Provisions :'+'2000'+'<br>'
        +'Loss Minimisation :'+'2000'+'<br>'
        +'Power Margin :'+'2000'+'<br>'
        +'Propellant Margin :'+'2000'+'<br>'
        +'Loss Formula :'+'2000'+'<br>'
        +'AVN 41/21:'+'2000'+'<br>';
        Insert rc; 
        ApexPages.currentPage().getParameters().put('Id', ps.id);   
        ApexPages.currentPage().getParameters().put('MTAStartDate', String.valueOf(Date.newInstance(2019, 7, 17)));                
        ApexPages.currentPage().getParameters().put('MTAType', 'Revision of Cover');    
        ApexPages.currentPage().getParameters().put('Currency', pol.CurrencyIsoCode);        
        VG_ReviseAesirStepsController asr=new VG_ReviseAesirStepsController();
        asr.gotostep1();
        asr.rc.VG_Additional_Information__c='';
        asr.gotostep2a(); 
        asr.fileName='test';
        asr.fileBody=blob.valueOf('Asset External id,Risk Start Date,Risk End Date,Coverage,Coverage Type,Limit,Attachment,AVG SI,Rate(%),Signed Shared(%),Annual Premium\nTest456,31-08-2018,31-08-2019,CAT,Full cover,1500,5000,1300,25,25,1200\nTest456,,01-08-2019,,,,,,,,190\n');               
        asr.gotostep2b();          
        //asr.Index='1';
        asr.gotostep2a();
        VG_ReviseAesirStepsController.RRWrapper RRW =new VG_ReviseAesirStepsController.RRWrapper();
        RRW.techPremium=4500;
        RRW.sumInsured=470;
        RRW.assName=ass.LS_AccName_with_Ass_Name__c;
        asr.addedRRList.add(RRW);
        asr.RRCalc();       
        asr.finish();
    }
}