force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/VG_Component_Details__c.field-meta.xml
<CustomField>
    <fullName>VG_Component_Details__c</fullName>
    <label>Component Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Equipments__c.field-meta.xml
<CustomField>
    <fullName>VG_Equipments__c</fullName>
    <label>Equipments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AOCS - CMG</fullName>
            </value>
            <value>
                <fullName>AOCS - Earth Sensor</fullName>
            </value>
            <value>
                <fullName>AOCS - FMW</fullName>
            </value>
            <value>
                <fullName>AOCS - GPS receiver</fullName>
            </value>
            <value>
                <fullName>AOCS - Gyro Assembly</fullName>
            </value>
            <value>
                <fullName>AOCS - Magnetotorquer</fullName>
            </value>
            <value>
                <fullName>AOCS - Reaction wheel</fullName>
            </value>
            <value>
                <fullName>AOCS - Star Tracker</fullName>
            </value>
            <value>
                <fullName>AOCS - Sun Sensor</fullName>
            </value>
            <value>
                <fullName>C and C - Beacon</fullName>
            </value>
            <value>
                <fullName>C and C - Central computer</fullName>
            </value>
            <value>
                <fullName>C and C - Crypto module</fullName>
            </value>
            <value>
                <fullName>C and C - RIU/PIU</fullName>
            </value>
            <value>
                <fullName>C and C - TC Receiver</fullName>
            </value>
            <value>
                <fullName>C and C - TM Transmitter</fullName>
            </value>
            <value>
                <fullName>EO Payload - Data Formatting Unit</fullName>
            </value>
            <value>
                <fullName>EO Payload - Data transmitter</fullName>
            </value>
            <value>
                <fullName>EO payload - Imaging Instrument</fullName>
            </value>
            <value>
                <fullName>EO Payload - Solid State Recorder</fullName>
            </value>
            <value>
                <fullName>EO Payload - TR Module (SAR)</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Deployable Antenna</fullName>
            </value>
            <value>
                <fullName>Mechanisms - HOP actuator</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Kevlar cutter</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Other actuator</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Pyro actuator</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Robotic arm</fullName>
            </value>
            <value>
                <fullName>Mechanisms - SADM</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Solar Array deployment</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Steerable Antenna</fullName>
            </value>
            <value>
                <fullName>Mechanisms - Unfurlable Antenna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddComponentDetailsController.cls
Public Class AddComponentDetailsController{
    public String assId{get;set;}
    public List<ComponentWrapper> compList{get;set;}
    public AddComponentDetailsController(){
        assId=apexpages.currentpage().getparameters().get('Id');
        Asset__c ass=[select id,Name,VG_Equipments__c from Asset__c where id=:assId limit 1];
        String[] equips;
        compList=new List<ComponentWrapper>();
        if(ass.VG_Equipments__c != null){
            equips=ass.VG_Equipments__c.split(';');
            System.debug('16-01::'+equips);
            for(Integer i=0;i<equips.size();i++){
                ComponentWrapper cw=new ComponentWrapper();
                cw.compName=equips[i];
                cw.para1='';
                cw.para2='';
                cw.para3='';
                compList.add(cw);
            }
            System.debug('16-01::'+compList);
        }
    }
    public PageReference Save(){
        Asset__c tmpass=new Asset__c();
        tmpass.id=assId;
        String compDetails='';
        if(compList.size()>1)
            compDetails='S_NO | Component Name | Parameter1 | Parameter2 | Parameter3\n';
        Integer i=1;
        for(ComponentWrapper cw:compList){
            compDetails+=i+'.'+cw.compName+';'+cw.para1+';'+cw.para2+';'+cw.para3+'\n';
            i++;
        }
        tmpass.VG_Component_Details__c=compDetails;
        update tmpass;
        return new PageReference('/'+assId);
    }
    public PageReference cancel(){
        return new PageReference('/'+assId);
    }
    public Class ComponentWrapper{
        public String compName{get;set;}
        public String para1{get;set;}
        public String para2{get;set;}
        public String para3{get;set;}
    }
}