force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/LS_AccName_with_Ass_Name__c.field-meta.xml
<CustomField>
    <fullName>LS_AccName_with_Ass_Name__c</fullName>
    <externalId>true</externalId>
    <label>Asset External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>Launcher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Certificate Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/Policy_Schedule__c/Policy_Schedule__c.object-meta.xml
<CustomObject>
    <label>Policy Schedule</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Schedule__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policy Schedules</relationshipLabel>
    <relationshipName>Policy_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/fields/Split_Type__c.field-meta.xml
<CustomField>
    <fullName>Split_Type__c</fullName>
    <label>Split Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>EEA</fullName>
            </value>
            <value>
                <fullName>Non EEA</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Schedule__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/VG_Policy_Schedule_Asset__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <label>Risk Rating Ref.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Rating</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/Annual_Rate_100__c.field-meta.xml
<CustomField>
    <fullName>Annual_Rate_100__c</fullName>
    <label>Annual Premium Share</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Risk Rating</relationshipLabel>
    <relationshipName>Risk_Rating</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Policy_Schedule__c.field-meta.xml
<CustomField>
    <fullName>VG_Policy_Schedule__c</fullName>
    <label>Policy Schedule</label>
    <referenceTo>Policy_Schedule__c</referenceTo>
    <relationshipName>Policy_Schedule_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/fields/VG_Premium__c.field-meta.xml
<CustomField>
    <fullName>VG_Premium__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VG_Policy_Schedule_Asset__c/recordTypes/Aesir.recordType-meta.xml
<RecordType>
    <fullName>Aesir</fullName>
    <active>true</active>
    <label>Aesir</label>
</RecordType>

force-app/main/default/classes/VG_AesirStepsController_Test.cls
@IsTest(SeeAllData=False)
public class VG_AesirStepsController_Test {
    public static testMethod void TestMethod1() {
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Aesir',acc.id);
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        Asset__c ass=new Asset__c();
        ass.VG_Asset_Type__c='Satellite';
        ass.Name='test';
        ass.VG_Account__c=acc.id;
        ass.LS_AccName_with_Ass_Name__c='Test';
        Insert ass;
        VG_Policy_Schedule_Asset__c psa = VG_TU.createPolicyScheduleAsset(ps.id);
        psa.Asset__c=ass.id;
        psa.Annual_Rate_100__c=500;
        update psa; 
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        ApexPages.currentPage().getParameters().put('Currency', pol.CurrencyIsoCode);        
        VG_AesirStepsController asr=new VG_AesirStepsController();
        asr.gotostep1();
        asr.rc.VG_Additional_Information__c='';
        asr.gotostep2a(); 
        asr.fileName='test';
        asr.fileBody=blob.valueOf('Selected Asset,Risk Start Date,Risk End Date,Coverage,Coverage Type,Limit,Attachment,AVG SI	Rate(%),Signed Shared(%),Annual Premium,Sum Insured\n Test1,14-08-19,31-08-19,Marine Cargo Treaty,Full cover,5000,5520,2900,25,15,0,0\n');               
        asr.gotostep2b();      
        asr.Index='1';
        VG_AesirStepsController.RRWrapper RRW =new VG_AesirStepsController.RRWrapper();
        RRW.psa = psa;
        RRW.techPremium=4500;
        RRW.sumInsured=470;
        RRW.assName=ass.LS_AccName_with_Ass_Name__c;
        asr.addedRRList.add(RRW);
        asr.RRCalc();
        asr.gotostep5();
        asr.gotostep2();
        asr.Cancel();
        asr.SummaryCalc();
        //asr.finish();
    }
    public static testMethod void TestMethod2() {
        VG_TU.policyCustomSetting();
        Account acc=VG_TU.createAccount('Customer');
        Policy__c pol=VG_TU.createPolicy('Aesir',acc.id);
        Policy_Schedule__c ps=VG_Tu.createPolicySchedule(pol.id);
        ps.Split_Type__c= 'EEA';
        ps.Name=ps.Name+'/EEA';
        update ps;
		Asset__c ass=new Asset__c();
        ass.VG_Asset_Type__c='Launcher';
        ass.Name='Test456';
        ass.LS_AccName_with_Ass_Name__c='Test456';
        ass.VG_Account__c=acc.id;
        Insert ass;
        VG_Policy_Schedule_Asset__c rr=new VG_Policy_Schedule_Asset__c();   
        rr.VG_Policy_Schedule__c=ps.id;
        rr.Asset__c=ass.Id;
        rr.Annual_Rate_100__c=4500;
        rr.VG_Premium__c=780;
        insert rr;
        ApexPages.currentPage().getParameters().put('Id', pol.id);
        ApexPages.currentPage().getParameters().put('Currency', pol.CurrencyIsoCode);        
        VG_AesirStepsController asr=new VG_AesirStepsController();
        asr.gotostep1();
        asr.rc.VG_Additional_Information__c='';
        asr.gotostep2a(); 
        asr.fileName='test';
        asr.fileBody=blob.valueOf('Asset External id,Risk Start Date,Risk End Date,Coverage,Coverage Type,Limit,Attachment,AVG SI,Rate(%),Signed Shared(%),Annual Premium\nTest456,31-08-2018,31-08-2019,CAT,Full cover,1500,5000,1300,25,25,1200\nTest456,,01-08-2019,,,,,,,,190\n');               
        asr.gotostep2b();          
        asr.Index='1';
        asr.gotostep2a();   
        asr.RRCalc();
        asr.SummaryCalc();
        asr.finish();
        
    }
}