force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Automatic_Fire_alarm__c.field-meta.xml
<CustomField>
    <fullName>VG_Automatic_Fire_alarm__c</fullName>
    <label>Automatic Fire alarm?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Level</fullName>
            </value>
            <value>
                <fullName>Low level</fullName>
            </value>
            <value>
                <fullName>Medium Level</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_BI_Indemnity_Period__c.field-meta.xml
<CustomField>
    <fullName>VG_BI_Indemnity_Period__c</fullName>
    <label>BI Indemnity Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Months</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Block_ID__c.field-meta.xml
<CustomField>
    <fullName>VG_Block_ID__c</fullName>
    <label>Block ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Building_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Building_SI__c</fullName>
    <label>Building SI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_City__c.field-meta.xml
<CustomField>
    <fullName>VG_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Comment__c.field-meta.xml
<CustomField>
    <fullName>VG_Comment__c</fullName>
    <label>Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Company_Division__c.field-meta.xml
<CustomField>
    <fullName>VG_Company_Division__c</fullName>
    <label>Company/Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Contents_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Contents_SI__c</fullName>
    <label>Contents SI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Coverage__c.field-meta.xml
<CustomField>
    <fullName>VG_Coverage__c</fullName>
    <label>Coverage</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M3 - Fully Comprehensive</fullName>
            </value>
            <value>
                <fullName>M6 - Fire &amp; Theft Only</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Fire &amp; Theft</fullName>
            </value>
            <value>
                <fullName>M6 - Third Party Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Customer_Property_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Customer_Property_SI__c</fullName>
    <label>TSI Customer Property</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Description__c.field-meta.xml
<CustomField>
    <fullName>VG_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_EML_BI__c.field-meta.xml
<CustomField>
    <fullName>VG_EML_BI__c</fullName>
    <label>EML BI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_EML_PD__c.field-meta.xml
<CustomField>
    <fullName>VG_EML_PD__c</fullName>
    <label>EML PD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Full_Value_Building_P__c.field-meta.xml
<CustomField>
    <fullName>VG_Full_Value_Building_P__c</fullName>
    <label>Full Value Building</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <default>true</default>
                <label>F</label>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Goods_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Goods_SI__c</fullName>
    <label>TSI Goods</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Machinery_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Machinery_SI__c</fullName>
    <label>TSI Machinery</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_MB_BI_Indemnity_Period__c.field-meta.xml
<CustomField>
    <fullName>VG_MB_BI_Indemnity_Period__c</fullName>
    <label>MB BI Indemnity Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 Months</fullName>
            </value>
            <value>
                <fullName>15 Months</fullName>
            </value>
            <value>
                <fullName>18 Months</fullName>
            </value>
            <value>
                <fullName>21 Months</fullName>
            </value>
            <value>
                <fullName>24 Month</fullName>
            </value>
            <value>
                <fullName>36 Months</fullName>
            </value>
            <value>
                <fullName>3 Month</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
            <value>
                <fullName>9 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_MB_PD_Deductible__c.field-meta.xml
<CustomField>
    <fullName>VG_MB_PD_Deductible__c</fullName>
    <label>MB PD Deductible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_MB_Waiting_Period__c.field-meta.xml
<CustomField>
    <fullName>VG_MB_Waiting_Period__c</fullName>
    <label>MB Waiting Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>120 Hours</fullName>
            </value>
            <value>
                <fullName>144 Hours</fullName>
            </value>
            <value>
                <fullName>168 Hours</fullName>
            </value>
            <value>
                <fullName>24 Hours</fullName>
            </value>
            <value>
                <fullName>48 Hours</fullName>
            </value>
            <value>
                <fullName>72 Hours</fullName>
            </value>
            <value>
                <fullName>96 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Other_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Other_SI__c</fullName>
    <label>TSI Other</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_PD_Deductible__c.field-meta.xml
<CustomField>
    <fullName>VG_PD_Deductible__c</fullName>
    <label>PD Deductible</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>VG_Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Street__c.field-meta.xml
<CustomField>
    <fullName>VG_Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Street_Number__c.field-meta.xml
<CustomField>
    <fullName>VG_Street_Number__c</fullName>
    <label>Street Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Total_BISI_for_the_indemnity_period__c.field-meta.xml
<CustomField>
    <fullName>VG_Total_BISI_for_the_indemnity_period__c</fullName>
    <label>Total BISI  (for the indemnity period)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Total_Business_Interruption_SI__c.field-meta.xml
<CustomField>
    <fullName>VG_Total_Business_Interruption_SI__c</fullName>
    <label>Total Business Interruption SI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Total_MBBISI_for_the_indemnity_period__c.field-meta.xml
<CustomField>
    <fullName>VG_Total_MBBISI_for_the_indemnity_period__c</fullName>
    <label>Total MBBISI (for the indemnity period)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Waiting_Period__c.field-meta.xml
<CustomField>
    <fullName>VG_Waiting_Period__c</fullName>
    <label>Waiting Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>120 Hours</fullName>
            </value>
            <value>
                <fullName>144 Hours</fullName>
            </value>
            <value>
                <fullName>168 Hours</fullName>
            </value>
            <value>
                <fullName>24 Hours</fullName>
            </value>
            <value>
                <fullName>48 Hours</fullName>
            </value>
            <value>
                <fullName>72 Hours</fullName>
            </value>
            <value>
                <fullName>96 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/VG_Water_sprinklers__c.field-meta.xml
<CustomField>
    <fullName>VG_Water_sprinklers__c</fullName>
    <label>Water sprinklers?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Level</fullName>
            </value>
            <value>
                <fullName>Low level</fullName>
            </value>
            <value>
                <fullName>Medium Level</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/VG_Attachment__c.object-meta.xml
<CustomObject>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Account__c.field-meta.xml
<CustomField>
    <fullName>VG_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Attachments</relationshipLabel>
    <relationshipName>Attachments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment__c</fullName>
    <label>Attachment</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>VG_Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assets File</fullName>
                <default>true</default>
                <label>Assets File</label>
            </value>
            <value>
                <fullName>TOBA</fullName>
            </value>
            <value>
                <fullName>Sanctions Search Certificate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/fields/VG_Description__c.field-meta.xml
<CustomField>
    <fullName>VG_Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VG_Attachment__c/recordTypes/Bridge.recordType-meta.xml
<RecordType>
    <fullName>Bridge</fullName>
    <active>true</active>
    <label>Bridge</label>
</RecordType>

force-app/main/default/classes/VG_NordicsAssetsUploadController.cls
public class VG_NordicsAssetsUploadController{
    Public VG_Attachment__c obj {get; set;}
    Public Id id {get;set;}
    public String description {get;set;} 
    public String AttName {get;set;}
    public String fileName {get;set;}
    public String updatedFileBody {get;set;}
    public string nameFile{get;set;}
    String[] filelines = new String[]{};
    public Blob fileBody {get;set;}
    Public Static Boolean coverCatchBlocks = False;
    Public Static Boolean AssetAttachment = True;
    public List<Asset__c> NordicsAssetsupload;
    public List < SelectOption > statusOptions {get;set;}
    public String sObjectType {get; set;}
    public String attType {get; set;}
    public Boolean isAttTypeGiven {get; set;}
    public Document templateFile {get; set;}
    Public Account AccName {get; set;}
    
    public VG_NordicsAssetsUploadController(){
        obj = new VG_Attachment__c();
        NordicsAssetsupload=new List<Asset__c>();
        id = apexpages.currentpage().getparameters().get('id');
        sObjectType = apexpages.currentpage().getparameters().get('sObjectType');
        attType = apexpages.currentpage().getparameters().get('attType');       
        templateFile = [Select Id from Document where Name = 'Bridge Asset Upload Template'];        
        if(sObjectType=='Account')
            AccName=[Select Id,Name From Account where Id=:id];
        if(attType == null){
            isAttTypeGiven = False;
        }else{
            isAttTypeGiven = True;
            obj.VG_Attachment_Type__c = attType;
        }
        Id attRecordTypeId = Schema.SObjectType.VG_Attachment__c.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        obj.RecordTypeId = attRecordTypeId;
        statusOptions = new List <SelectOption>();
        Schema.DescribeFieldResult statusFieldDescription = Schema.VG_Attachment__c.VG_Attachment_Type__c.getDescribe();
        for (Schema.Picklistentry picklistEntry: statusFieldDescription.getPicklistValues()) {
            if(picklistEntry.getValue() != 'Assets File'){
                statusOptions.add(new SelectOption(pickListEntry.getValue(), pickListEntry.getLabel()));            
            
            }
            if (picklistEntry.isDefaultValue()) {
                obj.VG_Attachment_Type__c = picklistEntry.getValue();
            }
        }
   }
   
   
   public Database.SaveResult saveCustomAttachment(){
            obj.Id = null;
            obj.VG_Account__c=id;
            obj.VG_Attachment_Type__c = attType;
            if(Description !=null && Description!='' )
                obj.VG_Description__c=Description;
            if(attType == 'Assets File')
                ReadFile();                
            if(AssetAttachment){
                return Database.insert(obj);
            }else{
                return null;   
            }        
    }
    
    
    public Database.SaveResult saveStandardAttachment(Id parentId){       
        System.debug('coverCatchBlocks:'+coverCatchBlocks+parentId);
        if(coverCatchBlocks){
            Database.SaveResult result=null;
            return result;
        }else{
            Database.SaveResult result;
            Attachment attachment = new Attachment();
            attachment.body = this.fileBody;
            if(AttName !=null && AttName != ''){
                String ext =this.fileName.substringAfter('.');
                if(AttName.length() > 80){
                    AttName=AttName.left(80);
                }
               attachment.Name = AttName+'.'+ext;
            }else{
                if(fileName.length() > 80){
                    String ext =this.fileName.substringAfter('.');
                    fileName=fileName.left(75)+'.'+ext;
                }
               
                attachment.Name = this.fileName;
            }
            
            attachment.parentId = parentId;
            System.debug('attachment.body::'+attachment.body);
            result = Database.insert(attachment);
            fileBody = Blob.valueOf(' ');
            return result;
        }
    }
    
    public PageReference processUpload(){
        if(fileBody == null){
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,  'Please Upload a file'));
            return null;
        }
        Database.SaveResult customAttachmentResult = saveCustomAttachment();        
        if (customAttachmentResult == null || !customAttachmentResult.isSuccess()){
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,  'Could not save attachment.'));
            return null;
        }       
        Database.SaveResult attachmentResult = saveStandardAttachment(id);        
        if (attachmentResult == null || !attachmentResult.isSuccess()){
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Could not save attachment.'));            
            return null;
        }else{
            VG_Attachment__c customAttachment = [select id from VG_Attachment__c where id = :customAttachmentResult.getId()];
            /*if(AttName !=null && AttName != ''){
                System.debug('AttName.length:'+AttName.length()+AttName.left(80));
                if(AttName.length() > 80){
                    System.debug('Hi:'+AttName.left(80));
                    AttName=AttName.left(80);
                }
                String ext =this.fileName.substringAfter('.');
                customAttachment.Name = AttName+'.'+ext;
            }
            else{
                if(fileName.length() > 80){
                    String ext =this.fileName.substringAfter('.');
                    fileName=AttName.left(75)+'.'+ext;
                }
               customAttachment.name = this.fileName;
            }*/
            
            customAttachment.VG_Attachment__c = attachmentResult.getId();
            update customAttachment;
            System.debug('Type::'+obj.VG_Attachment_Type__c);
            if(obj.VG_Attachment_Type__c == 'TOBA'){
                Account acc = new Account();
                acc.Id = id;
                acc.VG_TOBA_Uploaded__c = True;
                Update acc;
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'File Successfully Attached..','File Successfully Attached..'));
            description = '';
            return null;
        }
    }  
    
    
    public PageReference back(){
        return new PageReference('/'+id);
    } 
    
    
    public Pagereference ReadFile(){ 
        try{  
            nameFile=fileBody.toString();
        }
        catch(Exception e){                                  
           AssetAttachment=false;
           ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,  'CSV File Format only Accepted. Please check your file format.'));
           return null;
        }
        String regNum;
        if(nameFile!=null)
        filelines = nameFile.split('\n');
        System.debug('Filelines1::'+filelines+'Filelines::'+filelines.size()+'nameFile::'+nameFile);        
        updatedFileBody = '';
        for (Integer i=1;i<filelines.size();i++){
                String[] inputvalues = new String[]{};
                String[] headervalues = new String[]{};                             
                inputvalues = filelines[i].split(',');                             
                headervalues = filelines[0].split(',');
                System.debug('header::'+headervalues[0]);            
            Asset__c ass = new Asset__c();
            ass.VG_Account__c = id;
            Map<ID,Schema.RecordTypeInfo> ass_rt_Map = Asset__c.sObjectType.getDescribe().getRecordTypeInfosById();        
            Id NordicsRecordTypeId = Schema.SObjectType.Asset__c.getRecordTypeInfosByName().get('Nordics Property').getRecordTypeId();
            ass.RecordTypeId=NordicsRecordTypeId;
            System.debug('recordtype::'+NordicsRecordTypeId);
          if(headervalues[0]=='Company'){          
            if(inputvalues[0] != '' && inputvalues[0] !=null)
               ass.VG_Company_Division__c=inputvalues[0].trim(); 
            if(inputvalues[1] != '')
                ass.VG_Street__c = inputvalues[1].trim();                
            if(inputvalues[2] != '')   
                ass.VG_Street_Number__c = inputvalues[2].trim();
            if(inputvalues[3] != '')     
                ass.VG_Postal_Code__c = inputvalues[3].trim();
            if(inputvalues[4] != '')
                ass.VG_City__c = inputvalues[4].trim();
            if(inputvalues[5] != '')
                ass.VG_Country__c = inputvalues[5].trim();
            if(inputvalues[6] != '')
                ass.VG_Block_ID__c = inputvalues[6].trim();
            if(inputvalues[7] != '')
                ass.CurrencyIsoCode = inputvalues[7].trim();
            if(inputvalues[8] != '')
                ass.VG_Full_Value_Building_P__c = inputvalues[8].trim();
            if(inputvalues[9] != '')
                ass.VG_Building_SI__c = Decimal.valueOf(inputvalues[9].trim());
            if(inputvalues[10] != '')
                ass.VG_Machinery_SI__c = Decimal.valueOf(inputvalues[10].trim());
            if(inputvalues[11] != '')
                ass.VG_Goods_SI__c = Decimal.valueOf(inputvalues[11].trim());
            if(inputvalues[12] != '')
                ass.VG_Contents_SI__c = Decimal.valueOf(inputvalues[12].trim());
            if(inputvalues[13] != '')
                ass.VG_Customer_Property_SI__c = Decimal.valueOf(inputvalues[13].trim());
            if(inputvalues[14] != '')
                ass.VG_Other_SI__c = Decimal.valueOf(inputvalues[14].trim());
            if(inputvalues[15] != '')
                ass.VG_Total_Business_Interruption_SI__c = Decimal.valueOf(inputvalues[15].trim());
            if(inputvalues[16] != '')
                ass.VG_Total_BISI_for_the_indemnity_period__c = Decimal.valueOf(inputvalues[16].trim());
            if(inputvalues[17] != '')   
                ass.VG_Coverage__c=inputvalues[17].trim();
            if(inputvalues[18] != '')   
                ass.VG_Comment__c=inputvalues[18].trim();
            if(inputvalues[19] != '')
                ass.VG_EML_PD__c=Decimal.valueOf(inputvalues[19].trim());
                if(ass.VG_EML_PD__c==null){
                    ass.VG_EML_PD__c=ass.VG_Customer_Property_SI__c;
                }
            if(inputvalues[20] != '')
                ass.VG_EML_BI__c=Decimal.valueOf(inputvalues[20].trim());
                if(ass.VG_EML_BI__c==null){
                    ass.VG_EML_BI__c=ass.VG_Building_SI__c;
                }
            if(inputvalues[21] != '')
                ass.VG_PD_Deductible__c=Decimal.valueOf(inputvalues[21].trim());
            if(inputvalues[22] != '')
                ass.VG_Waiting_Period__c=inputvalues[22].trim();
            if(inputvalues[23] != '')
                ass.VG_BI_Indemnity_Period__c=inputvalues[23].trim();
            if(inputvalues[24] != '')
                ass.VG_Total_MBBISI_for_the_indemnity_period__c = Decimal.valueOf(inputvalues[24].trim());
                if(inputvalues[25] != '')   
                ass.VG_MB_PD_Deductible__c=Decimal.valueOf(inputvalues[25].trim());
            if(inputvalues[26] != '')   
                ass.VG_MB_Waiting_Period__c=inputvalues[26].trim();
            if(inputvalues[27] != '')
                ass.VG_MB_BI_Indemnity_Period__c=inputvalues[27].trim();
            if(inputvalues[28] != '')
                ass.VG_Automatic_Fire_alarm__c = inputvalues[28].trim();
            if(inputvalues[29] != '')
                ass.VG_Water_sprinklers__c = inputvalues[29].trim();
            if(inputvalues[30] != '')
                ass.VG_Foam_supression_system__c = inputvalues[30].trim();
            if(inputvalues[31] != '')
                ass.VG_Smoke_and_heat_venting_system__c = inputvalues[31].trim();
            if(inputvalues[32] != '')
                ass.VG_Full_time_public_Fire_Brigade_staff__c = inputvalues[32].trim(); if(ass_rt_Map.get(ass.RecordTypeId).getName()=='Nordics Property'){                   
                System.debug('assName::'+ass.RecordType.Name+':'+ass_rt_Map.get(ass.RecordTypeId).getName()+ass.RecordTypeId);               
                ass.Name=ass.VG_Street__c+','+ass.VG_Street_Number__c+','+ass.VG_City__c;
                System.debug('assName::'+ass.Name);
            }
        }else if(headervalues[0]=='SFDC Record Id'){
            if(inputvalues[0] != '')
                ass.id = inputvalues[0].trim();
            if(inputvalues[1] != '' && inputvalues[1] !=null)
               ass.VG_Company_Division__c=inputvalues[1].trim(); 
            if(inputvalues[2] != '')
                ass.VG_Street__c = inputvalues[2].trim();                
            if(inputvalues[3] != '')   
                ass.VG_Street_Number__c = inputvalues[3].trim();
            if(inputvalues[4] != '')     
                ass.VG_Postal_Code__c = inputvalues[4].trim();
            if(inputvalues[5] != '')
                ass.VG_City__c = inputvalues[5].trim();
            if(inputvalues[6] != '')
                ass.VG_Country__c = inputvalues[6].trim();
            if(inputvalues[7] != '')
                ass.VG_Block_ID__c = inputvalues[7].trim();
            if(inputvalues[8] != '')
                ass.CurrencyIsoCode = inputvalues[8].trim();
            if(inputvalues[9] != '')
                ass.VG_Full_Value_Building_P__c = inputvalues[9].trim();
            if(inputvalues[10] != '')
                ass.VG_Building_SI__c = Decimal.valueOf(inputvalues[10].trim());
            if(inputvalues[11] != '')
                ass.VG_Machinery_SI__c = Decimal.valueOf(inputvalues[11].trim());
            if(inputvalues[12] != '')
                ass.VG_Goods_SI__c = Decimal.valueOf(inputvalues[12].trim());
            if(inputvalues[13] != '')
                ass.VG_Contents_SI__c = Decimal.valueOf(inputvalues[13].trim());
            if(inputvalues[14] != '')
                ass.VG_Customer_Property_SI__c = Decimal.valueOf(inputvalues[14].trim());
            if(inputvalues[15] != '')
                ass.VG_Other_SI__c = Decimal.valueOf(inputvalues[15].trim());
            if(inputvalues[16] != '')
                ass.VG_Total_Business_Interruption_SI__c = Decimal.valueOf(inputvalues[16].trim());
            if(inputvalues[17] != '')
                ass.VG_Total_BISI_for_the_indemnity_period__c = Decimal.valueOf(inputvalues[17].trim());
            if(inputvalues[18] != '')   
                ass.VG_Coverage__c=inputvalues[18].trim();
            if(inputvalues[19] != '')   
                ass.VG_Comment__c=inputvalues[19].trim();
            if(inputvalues[20] != '')
                ass.VG_EML_PD__c=Decimal.valueOf(inputvalues[20].trim());
                if(ass.VG_EML_PD__c==null){
                    ass.VG_EML_PD__c=ass.VG_Customer_Property_SI__c;
                }
            if(inputvalues[21] != '')
                ass.VG_EML_BI__c=Decimal.valueOf(inputvalues[21].trim());
                if(ass.VG_EML_BI__c==null){
                    ass.VG_EML_BI__c=ass.VG_Building_SI__c;
                }
            if(inputvalues[22] != '')
                ass.VG_PD_Deductible__c=Decimal.valueOf(inputvalues[22].trim());
            if(inputvalues[23] != '')
                ass.VG_Waiting_Period__c=inputvalues[23].trim();
            if(inputvalues[24] != '')
                ass.VG_BI_Indemnity_Period__c=inputvalues[24].trim();
            if(inputvalues[25] != '')
                ass.VG_Total_MBBISI_for_the_indemnity_period__c = Decimal.valueOf(inputvalues[25].trim());
                if(inputvalues[26] != '')   
                ass.VG_MB_PD_Deductible__c=Decimal.valueOf(inputvalues[26].trim());
            if(inputvalues[27] != '')   
                ass.VG_MB_Waiting_Period__c=inputvalues[27].trim();
            if(inputvalues[28] != '')
                ass.VG_MB_BI_Indemnity_Period__c=inputvalues[28].trim();
            if(inputvalues[29] != '')
                ass.VG_Automatic_Fire_alarm__c = inputvalues[29].trim();
            if(inputvalues[30] != '')
                ass.VG_Water_sprinklers__c = inputvalues[30].trim();
            if(inputvalues[31] != '')
                ass.VG_Foam_supression_system__c = inputvalues[31].trim();
            if(inputvalues[32] != '')
                ass.VG_Smoke_and_heat_venting_system__c = inputvalues[32].trim();
            if(inputvalues[33] != '')
                ass.VG_Full_time_public_Fire_Brigade_staff__c = inputvalues[33].trim(); if(ass_rt_Map.get(ass.RecordTypeId).getName()=='Nordics Property'){                   
                System.debug('assName::'+ass.RecordType.Name+':'+ass_rt_Map.get(ass.RecordTypeId).getName()+ass.RecordTypeId);               
                ass.Name=ass.VG_Street__c+','+ass.VG_Street_Number__c+','+ass.VG_City__c;
                System.debug('assName::'+ass.Name);
            } 
            
        }
        if(ass.VG_Street__c !=null && ass.VG_Street_Number__c!=null && ass.VG_City__c !=null)
        //if(ass.VG_Street__c !=null || ass.VG_Street_Number__c!=null || ass.VG_Postal_Code__c !=null || ass.VG_City__c !=null || ass.VG_Country__c !=null || ass.VG_Block_ID__c != null || ass.CurrencyIsoCode !=null || ass.VG_Building_SI__c !=null || ass.VG_Machinery_SI__c !=null || ass.VG_Contents_SI__c !=null || ass.VG_Customer_Property_SI__c !=null || ass.VG_Other_SI__c !=null || ass.VG_Total_Business_Interruption_SI__c !=null || ass.VG_Full_Value_Building__c !=null || ass.VG_Automatic_Fire_alarm__c !=null || ass.VG_Foam_supression_system__c !=null || ass.VG_Smoke_and_heat_venting_system__c!=null || ass.VG_Full_time_public_Fire_Brigade_staff__c !=null)          
             NordicsAssetsupload.add(ass);
        }
        updatedFileBody = 'SFDC Record Id,Company,Street,Street Number,Postal Code,City,Country,Block ID,CurrencyISOCode,F/S/FL* Building,TSI Building,TSI Machinery,TSI Goods,TSI Contents,TSI Customer Property,TSI Other,Total Business Interruption SI (12 months),Total Business Interruption SI (for the indemnity period),Coverage,Comment,EML PD,EML BI,PD Deductible,Waiting Period,BI Indemnity Period,Total MB Business Interruption SI (for the indemnity period),MB PD Deductible,MB Waiting Period,MB BI Indemnity Period,Automatic Fire alarm?,Water sprinklers?,Foam supression system?,Smoke and heat venting system?,Full time public Fire Brigade staff?\n';        
        List<Asset__c> insAss=new List<Asset__c>();
        List<Asset__c> updAss=new List<Asset__c>();
        try{
        for(Asset__c ass:NordicsAssetsupload){
            if(ass.id==null){
                System.debug(':if:');
                ass.VG_Acc_Name_with_St_City__c=AccName.Name+'_'+ass.VG_Street__c+','+ass.VG_Street_Number__c+','+ass.VG_City__c;     
                insAss.add(ass);
            }else{
                System.debug(':else:');
                updAss.add(ass);
            }
        }
        
        if(!insAss.IsEmpty()){
            upsert insAss VG_Acc_Name_with_St_City__c;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Assets created successfully...'));                  
        
        }
        }catch(Exception e){
            AssetAttachment=false;
            if(e.getMessage().contains('Duplicate external id specified')){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Please check the file ....the combination of Street,Street Number and City already available.'));
                return null;
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Error::'+e.getMessage()));
                return null;
            }    
            
        }
        if(!updAss.IsEmpty()){
            try{
                update updAss;
            }catch(Exception e){
                System.debug('Exp::'+e);
            }
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Assets Updated successfully...'));                  
       
        }
        for(Asset__c a : NordicsAssetsupload){ 
            updatedFileBody = updatedFileBody + a.Id;
            updatedFileBody = updatedFileBody + ',' + a.VG_Company_Division__c;                                              
            updatedFileBody = updatedFileBody + ',' + a.VG_Street__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Street_Number__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Postal_Code__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_City__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Country__c;                  
            updatedFileBody = updatedFileBody + ',' + a.VG_Block_ID__c;
            updatedFileBody = updatedFileBody + ',' + a.CurrencyIsoCode;
            updatedFileBody = updatedFileBody + ',' + a.VG_Full_Value_Building_P__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Building_SI__c;                                  
            updatedFileBody = updatedFileBody + ',' + a.VG_Machinery_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Goods_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Contents_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Customer_Property_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Other_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Total_Business_Interruption_SI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Total_BISI_for_the_indemnity_period__c ;
            updatedFileBody = updatedFileBody + ',' + a.VG_Coverage__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Comment__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_EML_PD__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_EML_BI__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_PD_Deductible__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Waiting_Period__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_BI_Indemnity_Period__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_MB_PD_Deductible__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_MB_Waiting_Period__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_MB_BI_Indemnity_Period__c;          
            updatedFileBody = updatedFileBody + ',' + a.VG_Automatic_Fire_alarm__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Water_sprinklers__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Foam_supression_system__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Smoke_and_heat_venting_system__c;
            updatedFileBody = updatedFileBody + ',' + a.VG_Full_time_public_Fire_Brigade_staff__c+'\n';
            
        }
        fileBody = Blob.valueOf(updatedFileBody);                
        AssetAttachment=True;
        return null;
    }                  
}